### ISSUE TITLE
My Analytics Net work calculation

### ISSUE THREAD

**Issue by zhangv6** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#10]
I'd like to verify the net work calculation, my colleague Anthony has no business connection with me but it was marked as number 1 in my time investment.

**Comment by madehmer** [comment]
**@zhang6** -Top collaborators are ranked by time spent based on two-way (reciprocal) email communication and meetings. Is it possible that you emailed Anthony with your business email account? If you truly have no emails or meetings with your top collaborator, it could be a bug. If you think it is a bug, please share your contact information with us and we'll follow up with you. Thanks so much for your feedback and time on this!

**Comment by zhangv6** [comment]
Hi, Michele,
Thank you for your feed back.
I just feel curious that I didn’t email Anthony with my business email account, but each week there is 3 hours actions with him. I’m not sure it’s due to some meeting (actually no meeting with him) or sth else, if you can help to find it, I appreciate. Then I’ll cancel the non-use meeting / actions so that it can reflect real status for me.

**Comment by madehmer** [comment]
@zhang6 -Thanks for your response. Please share your contact information and my team will work with you to investigate this further.

**Comment by madehmer** [comment]
I'm going to close this for now in hopes that Zhang6 eventually reaches out for help with this issue.
