### ISSUE TITLE
Has the availability recently changed to just E5?

### ISSUE THREAD

**Issue by jmountforduk** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#100]
I've always had an E3 licence and for a few weeks after my email was moved to Exchange Online I was receiving prompts to book in focus time. This stopped and in looking on the internet to find out why, I came across this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40f032f9-30a5-b801-b3c2-602a6ef552d3
* Version Independent ID: bffa68c6-76a6-3de4-ec42-ab75c6a264d2
* Content: [Focus plan - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/focus-plan#feedback)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/focus-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/focus-plan.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **paul9955**

**Comment by madehmer** [comment]
@jmountforduk -Thank you for your feedback! Maybe your admin changed the setting for the prompt? However, it might be a bug. Would you please go to [your dashboard](https://myanalytics.microsoft.com/), select **Feedback** near the bottom of the left navigation pane, and then fill out and submit your issue there? Please select the **Allow Microsoft to contact you** checkbox. Then the team can follow up and confirm if it's a bug and/or how they can help you get your focus scheduling prompts back! 
![feedback](https://user-images.githubusercontent.com/39922363/76039139-58a3f400-5f00-11ea-9e9f-a410f07218ff.png)
