### ISSUE TITLE
Wrong step description to access MyAnalytics settings

### ISSUE THREAD

**Issue by oldengod** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#101]
In the section "To enable access to the dashboard and digests" the description of the steps are wrong to access the MyAnalytics settings. The steps 3 and 4 need to be adjusted correctly like this:

3. In the left pane, expand "Settings", and then select "Settings".

4. Under "Services" select MyAnalytics. This opens a page to configure access to MyAnalytics elements.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 381cb456-e75f-04fb-f4eb-2d6aa4d7a3a8
* Version Independent ID: 1908491e-d901-90a0-e29a-33327cfa1a2d
* Content: [MyAnalytics configuration for Office 365 administrators - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/setup/configure-myanalytics#to-enable-access-to-the-dashboard-and-digests)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Setup/configure-myanalytics.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Setup/configure-myanalytics.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **madehmer**

**Comment by paul9955** [comment]
Hello oldengod,

Thank you for your observation! I've looked into this. It appears that the configuration of the Settings pages is being updated but the changes haven’t yet been rolled out to all Office 365 subscribers. I don’t have access to the distribution schedule, but if you check back over the upcoming weeks, the functionality as described in [the documentation](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/setup/configure-myanalytics#configure-access-at-the-tenant-level) should appear. In the meantime, you can continue to use the steps that you listed in your initial comment. 

Thanks again, 
Paul (MyAnalytics documentation team)

**Comment by oldengod** [comment]
Thanks Paul for the quick reply!

**Comment by paul9955** [comment]
You're very welcome!
