### ISSUE TITLE
API for Analytics

### ISSUE THREAD

**Issue by LG40000** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#102]
I would like to extract a real time feed of activities on a Windows 10 machines and it looks like this workspace analytics tool is actually doing that an aggregating the data up.  How do I access the feed so I can pull it into my own app?

**Comment by madehmer** [comment]
@LG40000 -You can use the Microsoft Graph analytics API.  For details, see [MS Graph analytics API](https://docs.microsoft.com/graph/api/resources/social-overview?view=graph-rest-beta#help-users-gain-insights-into-their-work-patterns).
