### ISSUE TITLE
Use of the word Pseudonymized vs. De-identified

### ISSUE THREAD

**Issue by JeremyTyers** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#105]
We need to ensure that these terms are defined and consistent within the docs for WpA.   could we please have someone review all the docs and fix this.   Pseudonymized in particular should be defined for the audience who maybe learning about WpA and looking for how we handle this data.   This has been escalated several times to WpATRUST team.

**Comment by madehmer** [comment]
@JeremyTyers - Thanks for your feedback! I'm going to close this issue and ask you for more information via email.
