### ISSUE TITLE
This Product is utter crap

### ISSUE THREAD

**Issue by TurtleBeach** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#106]
1) I did not sign up for it.
2) It does not appear in any supposedly Admin dashboards that I can find; yet
3) I get unwanted and useless e-mails from MyAnalytics.

From other comments, it appears to be supposedly for enterprise accounts. SO WHY DO I GET E-MAILS as administrator for 5 e-mail accounts.

I resent spending even milliseconds slogging through shoddy or non-existent documentation to turn this insanity off; spending 10s of minutes going down multiple rat-holes is unacceptable.

Come on MS - quit shoving this junk to customers who are already paying for other marginally useful services.

**Comment by paul9955** [comment]
Hi TurtleBeach,
I’m sorry you aren’t finding MyAnalytics beneficial. You can opt out of it with these steps:

1.	Open myanalytics.microsoft.com.
2.	Select Settings (the gear icon at upper right).
3.	In the Settings panel, under MyAnalytics, select Settings.
4.	Under MyAnalytics, turn off the slider to the Off position.

 - paul9955, MyAnalytics documentation

**Comment by TurtleBeach** [comment]
@paul9955 
Thank you. However, the problem is that I have several MS accounts on my 'primary' computer - one account is for Azure development, and has an associated e-mail account with 2FA; the other account has an Office 365 subscription that is UNUSED, except for e-mail; e-mail goes to desktop Outlook 2019, which also has other MS and non MS accounts. It has proven to be impossible to get to the Analytics dashboard on that computer because MS/Windows 10/myanalytics.com does NOT (at least that I have found) allow me to select an account for myanalytids. So the 'dashboard' never appears. I had to use a computer that I happened never to have logged on to the Azure account, in order to get to myanalytics.com. Hence my extreme frustration.

**Comment by paul9955** [comment]
Hi TurtleBeach.
I looked into this a bit more and found something you can try:
  1. Decide which accounts you want to dissociate from MyAnalytics, and which one (if any) that you want to keep opted in for the MyAnalytics features. 
  2. Open a browser in incognito mode and log into myanalytics.microsoft.com. 
  3. In that incognito browser session, enter the credentials of one of the accounts that you want to dissociate.
  4. Follow the steps I gave earlier to opt out of MyAnalytics. 
  5. End this browser session. 
  6. Repeat steps 2-5 for each account that you want to dissociate from MyAnalytics. 
This should end the excess email that you're receiving. If this doesn't work for you, please let me know. 
Thank you,
 -- paul9955
