### ISSUE TITLE
Focus Time isn't booked in a separate color

### ISSUE THREAD

**Issue by jachea** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#107]
My Focus Time is no longer being booked in a separate color. How do I change that? There doesn't seem to be a way to do it in the configuration settings on MyAnalytics.

**Comment by paul9955** [comment]
Hi jachea,
I looked into this a bit and found one possibility. Have you renamed or deleted "Green category" from your categories list in the Outlook calendar? That's the color category that we use for focus time; if they delete it or rename it, it can no longer be used for this purpose, and focus time defaults to the standard blue color. You can find the category settings, on the Home ribbon of Outlook, in the Tags group. 
 - paul9955, MyAnalytics documentation

**Comment by jachea** [comment]
I did rename it, because I wanted to give the category a more descriptive name. It’s a little disappointing that I can’t rename the category, but this did fix my problem, so thanks for the help!

**Comment by marcodenic** [comment]
This is still a bug.
