### ISSUE TITLE
Change Subject of Focus Time

### ISSUE THREAD

**Issue by wgardner6** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#108]
I love the MyAnalytics tools. Can you enable configuration of reminder length and subject for the Focus Time? I generally hold time on my calendar under a very specific name and would love the ability to use that same naming convention. In addition, I use default reminders of 10 minutes prior to the event and Focus Time appears to use 15 minutes as the reminder length.

**Comment by paul9955** [comment]
Hi wgardner6,
I'm looking into this for you now. I'll post the answer here as soon as I find it. 
Thank you for your patience,
 - paul9955, MyAnalytics documentation team

**Comment by wgardner6** [comment]
Thanks, paul9955! Let me know if there's anything I can do to help!

**Comment by paul9955** [comment]
Hi wgardner6, 
Unfortunately, at the moment, these settings cannot be configured. You can, of course, change the label of a focus-time block after it exists, but you cannot configure those labels beforehand. As for the reminder, it is set to 15 minutes for all focus blocks, regardless of your other settings. I have passed your config ideas on to the product team, but I can make no forecasts of feature enhancements. 
Thank you! - Paul

**Comment by wgardner6** [comment]
Thanks for your help, Paul. I created a VBA script for this that runs when the Focus time is booked and makes the necessary modifications so I think I'm set. Thanks!

**Comment by paul9955** [comment]
I appreciate your reply, and I'm happy to hear about your resourceful action on this. 
Thank you, - Paul
