### ISSUE TITLE
adding important people

### ISSUE THREAD

**Issue by SarahBeacock** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#109]
[I can't seem to make this work by typing in the name of the person in my contacts - it just says Person not known or lists their name but I can't select it in any way.

The suggested list is useful and once I figured out how to get more names added to it more useful that the six random people it selected but it ran out of names pretty quickly without finding many that were actually important!

Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73d69671-f4f5-6fb5-2679-63cad245e1d4
* Version Independent ID: 47c6f7c8-9794-b353-3dae-8b9767115f63
* Content: [MyAnalytics Team Adoption --Introduction - Workplace Intelligence](https://docs.microsoft.com/en-gb/Workplace-Analytics/myanalytics/use/mya-adoption/team-adopt-intro)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/MyA-Adoption/Team-adopt-intro.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/MyA-Adoption/Team-adopt-intro.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-pascha**

**Comment by paul9955** [comment]
Hi SaraBeacock,
Sorry about the delay. I'm looking into this for you now. First, I'd like to verify the steps that you are taking. Are you following the steps in [this procedure](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/network#important-people), specifically the sentence that starts with, "If the person is not listed..."? 
Thank you!
-- Paul9955, MyAnalytics documentation

**Comment by SarahBeacock** [comment]
Yes I tried that and there doesn't seem to be any names/contacts in there, it just creates a new one. Presume this should be drawing from my Contacts or other recent emails?
<img width="355" alt="Annotation 2020-05-15 094458" src="https://user-images.githubusercontent.com/63855954/82030783-cc951200-9690-11ea-9981-c733c3ba76c7.png">
