### ISSUE TITLE
Incorrect definition of Conflicting Meeting Hours

### ISSUE THREAD

**Issue by racoonery** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#11]
Current definition: Number of meeting hours where the person had overlapping meetings in their calendar. The count includes the entire duration of all overlapping meetings, not just the amount of time that overlaps. (This number includes all accepted meeting times.).

I believe the "all accepted meeting times" should be changed to "all non-declined meeting times" unless the definition has changed recently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e59345bb-9abb-9e5d-8613-01c0226dfc2e
* Version Independent ID: 493ac915-2a6a-a271-825a-43f40d1863e8
* Content: [Workplace Analytics metric definitions - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/workplace-analytics/use/metric-definitions#feedback)
* Content Source: [WorkplaceAnalytics/Use/Metric-definitions.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics-pr/blob/live/WorkplaceAnalytics/Use/Metric-definitions.md)
* Product: **wpa**
* GitHub Login: @paul9955
* Microsoft Alias: **v-pascha**

**Comment by madehmer** [comment]
You're correct. The number of conflicting meeting hours does include all "non-declined" meetings. I’ve updated this topic accordingly. Thank you so much for your feedback!
