### ISSUE TITLE
Cannot find Workplace Analytics in A5 for EDU tenant

### ISSUE THREAD

**Issue by Darrelo365** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#110]
Hi, I've tried to enable this but it doesn't exist under Enterprise Apps in AAD. The licence SKU is listed as Education Analytics and my users have it. This page errors https://workplaceanalytics.office.com/ . Is Workplace Analytics something EDU can use or is it a different product used in Teams for Teaching? Thanks

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2f31d04-cc99-73e3-f057-647a895e4297
* Version Independent ID: b241adc5-0eba-64d8-eabd-cce6e31aac0c
* Content: [Environment and support aspects of Workplace Analytics - Workplace Intelligence](https://docs.microsoft.com/en-gb/workplace-analytics/setup/environment-requirements#feedback)
* Content Source: [WorkplaceAnalytics/Setup/Environment-Requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Setup/Environment-Requirements.md)
* Product: **wpa**
* GitHub Login: @paul9955
* Microsoft Alias: **v-midehm**

**Comment by paul9955** [comment]
Hello Darrelo365,
I'm looking into this for you now. I'll post the answer here as soon as I find it. Thank you for your patience. 
 - paul9955, Workplace Analytics documentation

**Comment by paul9955** [comment]
Hi Darrelo365,
I'd like to confirm which product you are trying to activate. 
 - Are you looking for Workplace Analytics? This product can be licensed through the Enterprise plans E1, E3, E4, or E5. 
 - Or are you looking for "Predictive Analytics"? This is a capability that is included in the A3 and A5 plans. See [Predictave Analytics](https://microsoft.sharepoint.com/sites/Infopedia_G04/Pages/DTI-Predictive-Analytics-for-Education.aspx) for a summary.
Thank you, - Paul

**Comment by Darrelo365** [comment]
Appreciate the reply. I cannot access the link you shared. Thanks

**Comment by paul9955** [comment]
Hello again, Darrelo365,
I looked into this some more, and this is what I found: Yes, Workplace Analytics is available for EDU but only analysis of faculty is supported at this time. For more information, the best thing to do is have your admin reach out to your Microsoft account team or use [this form](https://go.microsoft.com/fwlink/?linkid=851487) to inquire about Workplace Analytics.

**Comment by YesPrepDataCenter** [comment]
Any update on when this we ready for students, and not just faculty?
