### ISSUE TITLE
Auditory alarm notification for work start/stop and lunch break times

### ISSUE THREAD

**Issue by obryonj** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#111]
As part of 'My Analytics' application used to schedule focus time, work time, quiet time, I often lose track of time (or even forget to look at the clock) while I am working. It would help me stick to the scheduled work/break/quiet scheduled times if I could set an alarm for an auditory reminder.

**Comment by paul9955** [comment]
Hi obryonj,
Thanks for your question. I'm looking into this for you and will respond here with what I find.  
First, I have a question: For your scheduling app, are you using Outlook in Office 365?
Thanks, 
 -- paul9955, MyAnalytics documentation

**Comment by paul9955** [comment]
Hello obryonj, 
Have you tried the options that are described in [Turn sound effects on or off in Outlook](https://support.office.com/en-us/article/turn-sound-effects-on-or-off-in-outlook-e37d6cb4-5313-4d60-87fd-c4a7c2e4df59)? This might work for at least some of what you're seeking.
 -- paul9955, MyAnalytics documentation
