### ISSUE TITLE
doesn't cover removal of the button and its re-activating code from outlook desktop

### ISSUE THREAD

**Issue by RCGms** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#112]
Here again I search for exactly how to disable and remove this button from my ribbon in outlook 2016 for the desktop app.  Its been more than a week since I disabled the MyAnalytics option in the web site, and like before, if I remove the button from the ribbon, the next time I start outlook the button re-appears.  Its like a rash you can't get rid of no matter how many creames and salves you throw at it.. And I'm sorry but Insights and the MyAnalytics components are just garbage to 99% of the people in the first place.  Do you really REALLY need to know most of your time is wasted on meetings, etc.. and you can't tell this yourself?  If you really want it, you should have to install something... not the other way around.

**Comment by paul9955** [comment]
Hi RCGms,
Thanks for your comment. I'll look into this for you and respond on this page when I've found an answer. 
 -- paul9955, MyAnalytics documentation

**Comment by paul9955** [comment]
Hi RCGms,
Have you tried this? [Opt out of MyAnalytics](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/opt-out-of-mya)? If it doesn't work, please let me know. 
Thanks,
 -- paul9955

**Comment by paul9955** [comment]
After we discussed the matter, RCGims closed the other issue (related to this one) that they had posted: https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/issues/113.
