### ISSUE TITLE
unwanted MyAnalytics

### ISSUE THREAD

**Issue by RowanGoss** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#114]
I must have signed up for MyAnalytics at some time, I can't recall. My mistake.
I get emails from microsoft re "Your month in review" and there is at the bottom an unsubscribe button, along with buttons for Documentation and Feedback.
Thinking it will be easy to stop these emails and tracking by hitting unsubscribe, I did just that, but I get a page that says "Sorry, you don't have a licence".  Curious, because I'm getting regular emails.
So I hit Feedback and get the same thing.
So I can't stop the emails, unsub or give feedback.
MS is notoriously hard to contact unless you're paying them.
So I appeal to the Github community for help.

**Comment by paul9955** [comment]
Hi Rowan,
Thanks for your comment. Here are the steps for [opting out of MyAnalytics](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/opt-out-of-mya). This should work but if it doesn't, please let me know what happens and I'll keep looking for an answer for you. 
 -- paul9955, MyAnalytics documentation

**Comment by RowanGoss** [comment]
Hi Paul
Thanks so much for your reply.
I tried your suggestion, but it came to the same result as before.
"Sorry, you don't have a license"
and a tipped over ice cream.
This is what puzzles me.
Look forward to hearing from you again.
Kind regards
Rowan

**Comment by paul9955** [comment]
Hi Rowan,
Is it possible that you have more than one account that is subscribed to MyAnalytics? If that might be the case, let's try one other thing. Try the steps in [If you have multiple accounts](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/opt-out-of-mya#if-you-have-multiple-accounts) and if that doesn't work, please let me know. 
Thank you,
 - Paul

**Comment by RowanGoss** [comment]
Hi Paul,
I don't know what changed but I followed the link in your email to log on
to MyAnalytics, and yes I have multiple MS accounts, which were displayed
for me to choose, and logged on.
Once in MyAnalytics it was easy enough to flick the switch and turn it off,
I think it turned off for all accounts.
I didn't have to go incognito.
Maybe if I had I might have been able to turn it off for selected accounts,
leaving it on for others.
Anyway I'm happy to have achieved the result, with your valuable help.
Thank you!
Can I ask, are you an MS employee? or volunteer? or something?

Regards,
Rowan
0451 099 533

**Comment by paul9955** [comment]
Hi Rowan,
I am a contract employee who writes technical documentation for Microsoft -- specifically, the MyAnalytics and Workplace Analytics docs. I'm glad this info worked for you!  
 - Paul
