### ISSUE TITLE
Preferred rule for all analysts or just me?

### ISSUE THREAD

**Issue by juchacz** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#115]
Hi! The documentation doesn't specify, but if I set a meeting exclusion rule as preferred, does it only apply to my own Explore and Plans pages, or everyone in my partition?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6df4140f-7d3e-1223-9796-a4286d1a4f88
* Version Independent ID: 42d7105a-3e49-771c-8875-af7509a33442
* Content: [Meeting exclusion rules concepts - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/tutorials/meeting-exclusion-concept#feedback)
* Content Source: [WorkplaceAnalytics/Tutorials/meeting-exclusion-concept.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Tutorials/meeting-exclusion-concept.md)
* Product: **wpa**
* GitHub Login: @paul9955
* Microsoft Alias: **v-midehm**

**Comment by paul9955** [comment]
Greetings, juchacz! 
The rule applies to everyone. Thank you for pointing this out. We have updated the documentation to explain this. Please see: [Published rules](https://docs.microsoft.com/en-us/Workplace-Analytics/tutorials/meeting-exclusion-concept#published-rules). 
Thanks again,
 -- paul9955
