### ISSUE TITLE
Requirement for mailbox location

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#116]
Is it required to have mailbox in Exchange Online to be able to use MyAnalytics? Is it supported for Exchange hybrid or with just add-on on to Outlook with mailbox on-prem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 381cb456-e75f-04fb-f4eb-2d6aa4d7a3a8
* Version Independent ID: 1908491e-d901-90a0-e29a-33327cfa1a2d
* Content: [MyAnalytics configuration for Office 365 administrators - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/setup/configure-myanalytics)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Setup/configure-myanalytics.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Setup/configure-myanalytics.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **v-pausch**

**Comment by paul9955** [comment]
Hello Larry,
I believe it needs to be Exchange Online, but I will check on this and verify it for you. I will reply back to this thread.
 -- paul9955, MyAnalytics documentation

**Comment by paul9955** [comment]
Hi Larry,
Yes, [Exchange Online is required](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/overview/plans-environments#prerequisites-and-exclusions). Hybrid systems and on-premises Exchange do not support the use of MyAnalytics. 
Thank you for your interest.
-- paul9955

**Comment by Larryngolog** [comment]
Thanks Paul!

**Comment by paul9955** [comment]
You're very welcome! Sorry for the delay in getting back to you.
