### ISSUE TITLE
Links don't work in Cortana briefing

### ISSUE THREAD

**Issue by TaraHanratty** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#118]
I received this for the first time today - it seems really useful but none of the actions (Done, Add to To Do, etc.) actually work.  I get a spinner and a message saying 'working on it' for quite a while and then an error message:
![image](https://user-images.githubusercontent.com/41435704/82657563-763e4b00-9c1d-11ea-91bc-a781b42d7037.png)
The same happens with all of the feedback links or I would have used those to pass this on.

**Comment by paul9955** [comment]
Hello Tara,
I will check into this for you, and post to this thread what I find. 
Thank you,
 -- paul9955, MyAnalytics documentation

**Comment by paul9955** [comment]
Hi Tara,
Thank you very much for bringing this issue to our attention. I have alerted the development team and they are looking into it now.
 -- paul9955
