### ISSUE TITLE
Microsoft insights

### ISSUE THREAD

**Issue by patienceisza** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#119]
Is it possible to have Microsoft Insights track how much time I spend in particular excel files? I'm trying to find how much time I typically spend on certain projects

**Comment by paul9955** [comment]
Hello patienceisza,
I don't believe that is currently possible with Insights but I will check to see if there's another way to accomplish it. I will post what I find in this thread.
Thank you,
-- paul9955, Workplace Analytics/MyAnalytics documentation

**Comment by paul9955** [comment]
Hi patienceisza,
The time spent in Office applications is tracked in [Windows 10 Activity History data](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/overview/privacy-guide#windows-10-activity-history-data), and MyAnalytics uses Windows 10 activity history data to compute insights, but it does not surface this information in a report view in which particular applications can be singled out. 
Thank you for expressing this need. We will consider this request for the future. 
 -- paul9955
