### ISSUE TITLE
Focus sounds nice, but we need more powerful stuff

### ISSUE THREAD

**Issue by audunknudsrod** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#120]
### This is our problem
The engineers in our team keep getting called into too many meetings, so setting up focus time seems to be a nice remedy, and the idea of also monitoring it sounds great.

But Focus time currently doesn't fix our problem because
* Two hours per day is luxury for a manager, but insufficient for a developer
* Eating lunch from 12:00 to 13:00 is not a universal concept. Norwegians (like me) have 30-minute lunches, usually from 11:00 to 11:30 or from 11:30 to 12:00.
* Booking two weeks in advance is a tad too short.

### This is what we want to do
Create a meeting budget for the team, by issuing time slots: Allow them to be called into meetings on specific days (e.g. Mondays, Thursdays and then Fridays before 09:30), or on specific times (Say, Mondays to Thursdays before 11:30).

As an example, let's say we used the latter solution: If you want to invite someone in my team and there only available after lunch or on Friday, they're actually not available. All their available meeting time has been taken; they need the rest of the time in their workweek to do individual work or do work exclusively within the team.

And we need much more than an hour or two undisturbed, three or four hours would be better.

We could probably work like that if we could do this
* Declare specific slots during the weeks as focus time (Tuesdays and Wednesdays, or each workday after 12:00, etc)
* Apply this rule for a whole department or for a set of employees (like a team): Persons X, Y, and Z (the three developers in team Omega) are on the same focus calendar. Available at the same time and unavailable at the same time
* Configure how far in advance it books focus, for example 6 months in advance. This is needed to stop recurring meetings from being set up in the focus time slots.

### This is what we want to know
* How many meetings were people from the team invited to in their focus time?
* How many of these meetings did they go to?
* Who is inviting to meetings in the focus time? Colleagues? Managers? People from other sites?

Each individual might want to see their own numbers, but the team (and scrum masters, leads, managers, whatever) might also want to see the team numbers.

### Summary
The current solution is probably good enough for stressed-out managers, but not for developers. Perhaps what I'm suggesting is an entirely different feature, I don't know. But if there was a "power user" configuration for the Focus Time concept, I would very much like it to be like this.

**Comment by AYacus** [comment]
Good feedback you provided on Microsoft MyAnalytics - I hope they listen to you.

**Comment by paul9955** [comment]
Hello audunknudsrod, 
Thank you for taking the time to share this detailed feedback. The MyAnalytics engineering team is actively exploring adding user preferences for the focus plan, which would include letting users customize their plan with respect to the number of focus hours assigned per day. Any new capabilities for the use of focus time will appear in the MyAnalytics documentation here: [Focus](https://docs.microsoft.com/workplace-analytics/myanalytics/use/focus).
We have also noted your feature suggestion for creating the focus plan at a team level and will review it further.
Thanks again,
 -- Paul9955, MyAnalytics documentation
