### ISSUE TITLE
Broken Markdown tables in two sub-sections

### ISSUE THREAD

**Issue by dockeith** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#121]
Markdown tables in sub-sections [reduce-after-hours-work-and-team-impact](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/mya-notifications#reduce-after-hours-work-and-team-impact) and [build-better-collaboration-habits](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/mya-notifications#build-better-collaboration-habits) seem to be broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae5243bf-bda7-c9a6-1f36-7c011e17988b
* Version Independent ID: 5e5ff830-dc34-73e6-670d-acf9d5617b90
* Content: [Inline suggestions in Outlook - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/mya-notifications#reduce-after-hours-work-and-team-impact)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/mya-notifications.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/mya-notifications.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **paul9955**

**Comment by paul9955** [comment]
Thank you, dockeith, for your comment!
This has now been fixed: [Inline suggestions/Stay up-to-date with important relationships](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/mya-notifications#reduce-after-hours-work-and-team-impact)
 -- paul9955

**Comment by dockeith** [comment]
Hi @paul9955. The table shows up now, but it doesn't look right. See ![screenshot](https://imgur.com/a/YyHKD0o).

**Comment by paul9955** [comment]
Hi dockeith,
After publishing this fix, I haven't been able to reproduce the problem in the browsers I've tried (Chrome, Edge, IE) on Windows, or in Chrome or Safari on my iPhone. What browser are you seeing this in, and with what screen size?
Thank you!
 -- paul9955
