### ISSUE TITLE
What is the scope of Windows 10 Activity History?

### ISSUE THREAD

**Issue by ferringer** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#122]
Is the application data collected for MyAnalytics limited to applications tied to Microsoft 365 such as Apps for Enterprise, Teams, OneDrive, etc., or is it collected for all applications installed on the target Windows 10 device?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 591e6c92-6639-75d7-4152-2ef0f730b8e5
* Version Independent ID: cff84842-9b6a-861b-1d0e-fd8c30a49df8
* Content: [Privacy guide for MyAnalytics users - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/overview/privacy-guide-users?source=docs#windows-10-activity-history-data)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Overview/privacy-guide-users.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Overview/privacy-guide-users.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **madehmer**

**Comment by paul9955** [comment]
Hi ferringer,
Sorry about the delay in responding. I looked into this and found that MyAnalytics looks only at Windows 10 activities on Microsoft 365 apps such as Word, Excel, PowerPoint, and so on. 
Please let me know if you have any other questions about this. 
Thank you,
 -- paul9955, MyAnalytics documentation
