### ISSUE TITLE
Turn Off by Default

### ISSUE THREAD

**Issue by bryanmec** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#123]
We should have an option to turn off globally and by default. Better yet, this should be opt-in for existing customers. 

We train our users to be vigilant with phishing but Microsoft keeps emailing them this borderline pointless stuff which causes confusion among my end users. 

Being GCC we were forced to accept MyAnalytics emails for months because MS turned on the emails but didn't give GCC customers the ability to turn them off. That's pretty crazy, in my opinion. 

We do not want Microsoft communicating with or emailing our end users at all, period. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cee44a2-5742-83c0-ee3e-82a3a3f9417e
* Version Independent ID: ad800194-4e32-0529-6844-7529a0d670d7
* Content: [Configure Briefing email - Cortana](https://docs.microsoft.com/en-us/briefing/be-admin)
* Content Source: [Briefing/be-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Briefing/be-admin.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **madehmer**

**Comment by dennish78** [comment]
Fully agree this needs to be controlled for the entire tenant at the Admin Center with a single button.
And Opt-in, not Opt-out

**Comment by martin8777** [comment]
Totally agree. This should either be an opt-in email or we as admins should have the option to turn it off for the whole tenant. 
Our organisation is being bombarded with spam emails and phishing attempts on a daily basis and we've already had to field numerous requests and queries from people questioning the MyAnalytics emails which are of no interest to anyone. Another form of spam coming from Microsoft is not what we need especially now with everyone on edge and our IT resources already stretched so thin.

**Comment by laughey** [comment]
I couldn't agree more (with the previous comments). Why does Microsoft insist on enabling all this  "oooh, look, it's a new button...option...link...function...go ahead and try it" garbage by **default**? remember Contact Manager, Bookings, Clutter, etc.? Yeah...

**REQUEST:** If it isn't a new way to stop employees/devices from being compromised, I would much prefer Microsoft provide such announcement(s) and include a HOWTO (I.e., Here is how you enable it -- should the customer choose to do so).

**Comment by martin8777** [comment]
I just realised this is a **daily** email as well. The weekly my anal tics email that are querying is bad enough.

**Comment by madehmer** [comment]
Hello all, Thank you for your feedback. We hear you and are working on a global setting. In the meantime, users can _unsubscribe_ at the end of _any_ Briefing email they receive. Admins can also use [customizable resources](https://docs.microsoft.com/Briefing/be-pilot) to introduce the Briefing before their users receive it. In the meantime, admins can disable the Briefing email with PowerShell for one or multiple users. For details, see [Configure Briefing email](https://docs.microsoft.com/Briefing/be-admin).

**Comment by dennish78** [comment]
> Hello all, Thank you for your feedback. We hear you and are working on a global setting. In the meantime, users can _unsubscribe_ at the end of _any_ Briefing email they receive. Admins can also use [customizable resources](https://docs.microsoft.com/Briefing/be-pilot) to introduce the Briefing before their users receive it. In the meantime, admins can disable the Briefing email with PowerShell for one or multiple users. For details, see [Configure Briefing email](https://docs.microsoft.com/Briefing/be-admin).

Yeah that's cute, but the powershell instructions are wrong. The identity parameter only accepts userprincipalname as input. Another fine mess.

**Comment by martin8777** [comment]
I found the easiest solution was to just block the email address cortana@microsoft.com in ATP

**Comment by bryanmec** [comment]
Michele. I don't understand why MS releases things the way they do. The ability to turn this off globally should be there on day one. If it's not a day one feature, the product isn't ready Also, it should be opt-in which means it should be off by default. 

MyAnalytics was very annoying for us on GCC because you gave us a "feature" that was a headache with no way to turn it off for months. I couldn't even run the PS scripts to turn it off on a per-user basis because GCC didn't support those commands. None of our users found it useful at all and it just caused pain for the admins and security team because our end users thought they were being targeted and/or they thought they were hacked since the emails had personal information in them. 

Please, please, PLEASE. Quit emailing stuff to our end users. Hopefully you can pass this feedback to the PM for these products. Frankly, we find they're useless and offer no value at all.

**Comment by martin8777** [comment]
> Michele. I don't understand why MS releases things the way they do. The ability to turn this off globally should be there on day one. If it's not a day one feature, the product isn't ready Also, it should be opt-in which means it should be off by default.
> 
> MyAnalytics was very annoying for us on GCC because you gave us a "feature" that was a headache with no way to turn it off for months. I couldn't even run the PS scripts to turn it off on a per-user basis because GCC didn't support those commands. None of our users found it useful at all and it just caused pain for the admins and security team because our end users thought they were being targeted and/or they thought they were hacked since the emails had personal information in them.
> 
> Please, please, PLEASE. Quit emailing stuff to our end users. Hopefully you can pass this feedback to the PM for these products. Frankly, we find they're useless and offer no value at all.

I agreed with this 100%, I think this is a really inappropriate time to be targeting end users like this with so many people working from home and under a lot of stress already. 
At our company we have told our end users to consult us in IT on anything they are unsure of and want clarification as to whether its safe or a scam etc and the thought of a daily email going out to all our users like this just boggles my mind.

**Comment by madehmer** [comment]
Hello again, I'm sorry to hear you see no value in MyAnalytics or the Briefing email. Thanks for your feedback on your experience. I'll pass it on to the team.

**Comment by dennish78** [comment]
I dare you to find actual persons not employed by Microsoft that have been asking for this exact "feature"

**Comment by martin8777** [comment]
> I dare you to find actual persons not employed by Microsoft's Marketing Dept that have been asking for this exact "feature"

FTFY - I imagine it pisses off their IT guys too.

**Comment by martin8777** [comment]
> Hello again, I'm sorry to hear you see no value in MyAnalytics or the Briefing email. Thanks for your feedback on your experience. I'll pass it on to the team.

It's less about the value of the products and more the arrogance that you think you know our end users better than we do and think they will all want this in their inbox on a daily basis. 
We should be able to opt in to anything like this and roll it out (if we choose to) at our own pace. It's not like this is some freebie product that I would expect to get spammed by, this is a product that our organisations all spend a consideration amount of money on and I think we should be able to choose whether our end users get something or not. 
Microsoft's relationship is with the IT Dept and not the end users.

**Comment by martin8777** [comment]
Wonderful. Despite blocking the email address this comes from, I got my first "briefing" this morning which appears to just be a list of any instance I have use the phrase "I will..." in an email hightlighted as a "Task you may have missed". 
So now I have Microsoft scrutinising my emails and implying I'm not getting my work done. Wow. 

To cap it all at the top of the email it is going to tell the end users that I have enabled this for the organisation implying this is something we in IT are foisting on the users and not Microsoft. Classy. 

"Your administrator has allowed the email to be turned on for your organization"

![pbrush](https://user-images.githubusercontent.com/6841765/84502950-abbfdc80-ac8f-11ea-97ac-ef16adf10dfe.png)

**Comment by lmoreau** [comment]
Isn't there other things Microsoft could be spending their time on?  Like improving Teams to support more than 9 people on screen at once?  I'm pretty sure NO one said "hey Microsoft, any way you can spam me with more useless daily email?  I mean these emails you send me daily asking if I noticed these 3 Amazon order confirmations sent yesterday are just oh so helpful."
Like others suggested I just blocked cortana@microsoft.com and problem solved.

**Comment by lmoreau** [comment]
> Hello all, Thank you for your feedback. We hear you and are working on a global setting. In the meantime, users can _unsubscribe_ at the end of _any_ Briefing email they receive. Admins can also use [customizable resources](https://docs.microsoft.com/Briefing/be-pilot) to introduce the Briefing before their users receive it. In the meantime, admins can disable the Briefing email with PowerShell for one or multiple users. For details, see [Configure Briefing email](https://docs.microsoft.com/Briefing/be-admin).

Um just so you know PowerShell is only for Windows, so what do you expect those of us that use Mac's do?  The fact you also expect us to use PowerShell to turn something off is ridiculous, like what is this the 80s??  A command line interface to disable a daily spam email?  Just so you know as well, with Canada's anti spam law, it's illegal to email someone that didn't give you written permission to.  None of my users gave you written permission to spam them.  So I've also forwarded these emails to the CASL reporting mailbox and filed an official complaint.

**Comment by martin8777** [comment]
> Um just so you know PowerShell is only for Windows, so what do you expect those of us that use Mac's do? The fact you also expect us to use PowerShell to turn something off is ridiculous, like what is this the 80s?? A command line interface to disable a daily spam email? Just so you know as well, with Canada's anti spam law, it's illegal to email someone that didn't give you written permission to. None of my users gave you written permission to spam them. So I've also forwarded these emails to the CASL reporting mailbox and filed an official complaint.

Good point. I am also in Canada but I think by offering the unsubcribe option they have covered their asses there and by notifying us admins ahead of time I think that also covers them from the point of view of providing written notification. 

What does suck is that there is no means to turn this off for the tenant despite them implying in the briefing email that it's been enabled on the tenant by the admin and from the sounds of it, their script to disable multiple users doesn't work right if you have multiple domains (as we do) and their own documentation (that Michele has referred to above) states we should use 30 days for a pilot period and they have given us two weeks. 


Also, (playing devil's advocate here) if you're a global admin of an O365 tenant you should be able to use powershell. I would certainly expect that of anyone I was hiring to manage an email environment. 
Powershell is available for OSX and Linux and if you're a Mac user the terminal shouldn't be an alien environment to you. Just my 2c worth.

**Comment by bryanmec** [comment]
It's unacceptable to release this garbage without a way to turn it off globally. How can you go to this much effort to write the code to curate these emails and send them out to people but you can't be bothered to put a basic On/Off switch?

**Comment by dennish78** [comment]
> Wonderful. Despite blocking the email address this comes from, I got my first "briefing" this morning which appears to just be a list of any instance I have use the phrase "I will..." in an email hightlighted as a "Task you may have missed".
> So now I have Microsoft scrutinising my emails and implying I'm not getting my work done. Wow.
> 
> To cap it all at the top of the email it is going to tell the end users that I have enabled this for the organisation implying this is something we in IT are foisting on the users and not Microsoft. Classy.
> 
> "Your administrator has allowed the email to be turned on for your organization"
> 
> ![pbrush](https://user-images.githubusercontent.com/6841765/84502950-abbfdc80-ac8f-11ea-97ac-ef16adf10dfe.png)

I've files a formal complaint to the Dutch Privacy protection authority and a MS support ticket ordering them to turn it off for the whole tenant including any and all future users.
![image](https://user-images.githubusercontent.com/66772287/84518381-ebf37f00-acd0-11ea-9cbc-0f29fb8352c8.png)
Prepare to be rescued.... wow, the arrogance

**Comment by martin8777** [comment]
> I've filed a formal complaint to the Dutch Privacy protection authority and a MS support ticket ordering them to turn it off for the whole tenant including any and all future users.
> ![image](https://user-images.githubusercontent.com/66772287/84518381-ebf37f00-acd0-11ea-9cbc-0f29fb8352c8.png)
> Prepare to be rescued.... wow, the arrogance

Let me know how you get on with the ticket. 
Chances are they probably wont have heard of this release yet.

**Comment by lmoreau** [comment]
> > I've filed a formal complaint to the Dutch Privacy protection authority and a MS support ticket ordering them to turn it off for the whole tenant including any and all future users.
> > ![image](https://user-images.githubusercontent.com/66772287/84518381-ebf37f00-acd0-11ea-9cbc-0f29fb8352c8.png)
> > Prepare to be rescued.... wow, the arrogance
> 
> Let me know how you get on with the ticket.
> Chances are they probably wont have heard of this release yet and it looks like they are done replying on this page. The guy it's assigned to hasn't chimed in at all.

Yeah they are clueless, I opened one this morning and all it has been is "So if I understand correctly you need assistance with learning how to prevent receiving unwanted mail?"

**Comment by lmoreau** [comment]
I haven't tried this but I JUST got this response, not sure if this works but maybe it will help others:

The briefing email is configured to send tasks and commitments to users which includes a summary of your meetings and relevant documents for the day. It is a service provided by Cortona and it is provided automatically to all users on Exchange Online.

To disable it, users can simply click unsubscribe in the email. Click this link for more information. 

To turn off Cortona access to your organization's Microsoft hosted data kindly follow the steps below:

In the Microsoft 365 admin center, select Settings > Org Settings and select Cortana.
Unselect the checkbox for Allow these Cortana optional connected experiences to use your organization's Microsoft hosted data to disable Cortana connected experiences.
Select Save changes.
Kindly click this link below for further reference:
https://docs.microsoft.com/en-us/microsoft-365/admin/misc/cortana-integration?view=o365-worldwide

**Comment by madehmer** [comment]
Hi folks, This feedback channel is intended to provide us writers feedback specifically about the documentation. Contacting [Microsoft Support](https://support.microsoft.com/) directly is best for further technical assistance. Please send further product related feedback to [Briefing feedback](https://cortana.office.com/briefing?v=feedback ). Thanks for your time on this!

**Comment by martin8777** [comment]
> Hi folks, This feedback channel is intended to provide us writers feedback specifically about the documentation. Contacting [Microsoft Support](https://support.microsoft.com/) directly is best for further technical assistance. Please send further product related feedback to [Briefing feedback](https://cortana.office.com/briefing?v=feedback). Thanks for your time on this!

Well, I clicked on the button that said "submit and view feedback for this product" and it brought me here so I guess you need to fix that aspect of the documentation then.

![image](https://user-images.githubusercontent.com/6841765/84526546-e3408000-acb3-11ea-9983-b464384df18d.png)

But yes, I'll log a ticket and copy and paste everything from here to the briefing feedback page too so what its worth....

**Comment by martin8777** [comment]
> I haven't tried this but I JUST got this response, not sure if this works but maybe it will help others:
> 
> The briefing email is configured to send tasks and commitments to users which includes a summary of your meetings and relevant documents for the day. It is a service provided by Cortona and it is provided automatically to all users on Exchange Online.
> 
> To disable it, users can simply click unsubscribe in the email. Click this link for more information.
> 
> To turn off Cortona access to your organization's Microsoft hosted data kindly follow the steps below:
> 
> In the Microsoft 365 admin center, select Settings > Org Settings and select Cortana.
> Unselect the checkbox for Allow these Cortana optional connected experiences to use your organization's Microsoft hosted data to disable Cortana connected experiences.
> Select Save changes.
> Kindly click this link below for further reference:
> https://docs.microsoft.com/en-us/microsoft-365/admin/misc/cortana-integration?view=o365-worldwide

Sadly turning off that Cortana option excludes the briefing email. 
They've thought of everything it seems, other than an option to turn it off at the tenant level. 

![image](https://user-images.githubusercontent.com/6841765/84527343-6366e580-acb4-11ea-89ea-5940c84c89fe.png)
