### ISSUE TITLE
Opt out

### ISSUE THREAD

**Issue by martin8777** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#125]
If I have read this page correctly, am I right in thinking that we need to opt out of the Briefing email per user and if we create new users we will have to opt out for them at the time of creation too? 

There needs to be a switch to turn this off for the domain so that it's off for all existing users and any newly created mailboxes too. 

Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0a83186-6909-edb8-7de3-7a5c9307a0a1
* Version Independent ID: 9ba1d4d8-60ba-1c4d-f7e8-e9a92e74727d
* Content: [Briefing email overview - Cortana](https://docs.microsoft.com/en-gb/briefing/be-overview)
* Content Source: [Briefing/be-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Briefing/be-overview.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **madehmer**

**Comment by lmoreau** [comment]
I agree, this is a total joke.  I just blacklisted cortana@microsoft.com as I hardly think I'm going to go through all of this just to block Microsoft from spamming us daily.  The one it sent me today saying "Did you miss these emails?" were all Amazon order confirmations.  Like wow real helpful.

**Comment by martin8777** [comment]
> I agree, this is a total joke. I just blacklisted [cortana@microsoft.com](mailto:cortana@microsoft.com) as I hardly think I'm going to go through all of this just to block Microsoft from spamming us daily. The one it sent me today saying "Did you miss these emails?" were all Amazon order confirmations. Like wow real helpful.

I blocked that address yesterday and the email still came through. It seems like they may be bypassing the email somehow and just dropping the email into inboxes directly. 

Doing a mail trace of inbound mail from cortana@microsoft.com for the past two days shows no results so that are being sneaky about it for sure. 

The content of my "briefing" was basically a list of any time I have said "I will do..." in an email titled as "Tasks you may have missed" like I now have Microsoft as a micro manager nitpicking my emails. 
Thanks a bunch.

**Comment by bryanmec** [comment]
You could not block MyAnalytics emails at all. They didn't route like normal emails and they were placed directly in a user's mailbox. I would not be shocked if MS is doing the same thing here.

**Comment by martin8777** [comment]
> You could not block MyAnalytics emails at all. They didn't route like normal emails and they were placed directly in a user's mailbox. I would not be shocked if MS is doing the same thing here.

Yes that seems to be what's happening here too.

**Comment by madehmer** [comment]
Hi folks -Thank you for your feedback. We've added a tenant-level configuration, so the admin can opt in or out the entire tenant. See [Tenant-level configuration](https://docs.microsoft.com/briefing/be-admin#tenant-level-configuration) for details.

**Comment by bryanmec** [comment]
Thanks for taking our feedback even though it was a bit harsh at times. Will this be available to GCC customers as well?

**Comment by martin8777** [comment]
> Hi folks -Thank you for your feedback. We've added a tenant-level configuration, so the admin can opt in or out the entire tenant. See [Tenant-level configuration](https://docs.microsoft.com/briefing/be-admin#tenant-level-configuration) for details.

When will this be made available?

**Comment by lmoreau** [comment]
Worked for me earlier, go to Settings > Org Settings and then it has Briefing right there where you can turn it off.  Make sure you're in the new admin panel before doing it.

Thank you Microsoft team for making such quick changes.  I'm definitely very impressed and happy!

**Comment by madehmer** [comment]
@martin8777 -It should be there, please try again. Thanks again for your feedback!

**Comment by martin8777** [comment]
No it's not there. Has it been rolled out worldwide or just the US ? 

![image](https://user-images.githubusercontent.com/6841765/84936316-757bc600-b0b0-11ea-9388-469ed0e60ff9.png)

**Comment by lmoreau** [comment]
> No it's not there. Has it been rolled out worldwide or just the US ?
> 
> ![image](https://user-images.githubusercontent.com/6841765/84936316-757bc600-b0b0-11ea-9388-469ed0e60ff9.png)

I'm in Canada and I have it.  Very strange!

![image](https://user-images.githubusercontent.com/26292349/84937056-3138f780-b0a9-11ea-90fd-5cf0e0c8eca8.png)

**Comment by martin8777** [comment]
We are a non profit tenant, I wonder if it's not been updated on all subscription types yet?

**Comment by madehmer** [comment]
@martin8777 - If you have a tenant that is not part of this first release, you won’t see it as an option for that tenant yet. When the Briefing is released to your tenant, the control will be exposed prior to  the users in that tenant receiving Briefing email. Thanks for asking!

**Comment by martin8777** [comment]
> @martin8777 - If you have a tenant that is not part of this first release, you won’t see it as an option for that tenant yet. When the Briefing is released to your tenant, the control will be exposed prior to the users in that tenant receiving Briefing email. Thanks for asking!

Yeah that would make sense, except I am already receiving the briefing emails. 

I've commented on them enough the past week or so!

**Comment by martin8777** [comment]
What's the powershell command to turn it off for the tenant?

**Comment by madehmer** [comment]
There is no PowerShell control at the tenant level. See [Configure Briefing email](https://docs.microsoft.com/Briefing/be-admin) for tenant-level configuration steps.

**Comment by martin8777** [comment]
But the settings don't appear in our admin console so how do we turn this off?

**Comment by madehmer** [comment]
I'm sorry to hear you're still having issues. Please contact [Support](https://support.microsoft.com/) for immediate assistance and/or [send the team feedback](https://cortana.office.com/briefing) about this issue, so they can follow up with you directly.

**Comment by martin8777** [comment]
Thanks but I've tried both of those avenues and not had any success. 

The 3rd party support company who responded to my ticket just repeated the published steps to disable users one by one or by using a list and then closed the support request. 

I have had no response by using the feedback but then I have never had any follow up from the feedback tool so that was no surprise.

**Comment by Jjack-666** [comment]
I'm surprised that Microsoft spend so much time creating something like this, which is basically scraping through Outlook, when there are already enough features to enable people to organise their day....Categories, Flags, To Do list etc.  Perhaps more energy could be expended on answering the multitudinous question/queries and suggestions for changes to existing facilities, such as 'Why can't I change the category name or colour or delete a category for a shared mailbox' - need to be a rocket surgeon to have even half a quarter of a chance of editing this.  Don't need MS Cortana micromanaging my day thanks very much.
