### ISSUE TITLE
Add -Append to 'Export-CSV' in loop.

### ISSUE THREAD

**Issue by bergengineering** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#126]
[Enter feedback here]
Section '[Set access for multiple users](https://docs.microsoft.com/en-us/briefing/be-admin#set-access-for-multiple-users)', Step 2:

`Export-CSV` command should have `-Append` parameter to avoid overwriting your csv and ending up with result for only the last run of the loop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cee44a2-5742-83c0-ee3e-82a3a3f9417e
* Version Independent ID: ad800194-4e32-0529-6844-7529a0d670d7
* Content: [Configure Briefing email - Cortana](https://docs.microsoft.com/en-us/briefing/be-admin)
* Content Source: [Briefing/be-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Briefing/be-admin.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **madehmer**

**Comment by madehmer** [comment]
@bergengineering -Thank you so much for your feedback. The documentation has been updated accordingly!
