### ISSUE TITLE
Hi the BUSY option does not put anything in my calendar?

### ISSUE THREAD

**Issue by PeterJSY** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#127]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88acd6f6-1d23-442b-a17c-21d34325d6f6
* Version Independent ID: d2f15c2e-17f9-6b97-9ac8-c01086acc985
* Content: [Book focus time with the Briefing email - Cortana](https://docs.microsoft.com/en-gb/briefing/be-focus)
* Content Source: [Briefing/be-focus.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Briefing/be-focus.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **madehmer**

**Comment by madehmer** [comment]
@PeterJSY -Thanks for your feedback. I forwarded it to the team. If you still need Support for this issue, please use [this feedback form](https://cortana.office.com/briefing) and include your contact info, so the team can follow up with you if necessary.
