### ISSUE TITLE
This action could not be completed

### ISSUE THREAD

**Issue by davidslight** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#128]
Error box appears within email when I click on 
Did you find this helpful
![Annotation 2020-06-15 071943](https://user-images.githubusercontent.com/25210376/84668526-9a1d4580-aed8-11ea-944a-5231dd6799d5.jpg)

**Comment by madehmer** [comment]
Ok, I'll pass your feedback on to the team. Thank you!
