### ISSUE TITLE
Issue with verbage

### ISSUE THREAD

**Issue by sysadmin-scs** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#129]
"You are receiving the Briefing email because your admin has enabled this email for your organization" 

I take issue with that statement. As an admin, I took no action. Microsoft pushed this feature and turned it to "enabled" as default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0a83186-6909-edb8-7de3-7a5c9307a0a1
* Version Independent ID: 9ba1d4d8-60ba-1c4d-f7e8-e9a92e74727d
* Content: [Briefing email overview - Cortana](https://docs.microsoft.com/en-us/briefing/be-overview)
* Content Source: [Briefing/be-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Briefing/be-overview.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **madehmer**

**Comment by madehmer** [comment]
Thanks again for your feedback. The docs have been updated accordingly.
