### ISSUE TITLE
Manually installing.

### ISSUE THREAD

**Issue by dr-ivan** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#13]
"If the MyAnalytics Outlook add-in is not installed, you can install it manually with these instructions. You can also view the MyAnalytics manifest."
- no instructions available.
- manifest file produces errors in portal when run:
"Errors Detected
XML Schema Violation. This is an invalid xsi:type 'http://schemas.microsoft.com/office/mailappversionoverrides/1.1:MessageComposeAutoRun'.
XML Schema Violation. This is an invalid xsi:type 'http://schemas.microsoft.com/office/mailappversionoverrides/1.1:AppointmentOrganizerAutoRun'."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3b42c92-57c3-ea33-0f79-507eeca00128
* Version Independent ID: ffa95980-81ad-2fc4-7200-d3d2916eca35
* Content: [Confirm the installation of the MyAnalytics Outlook add-in - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/setup/verify-add-in)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Setup/Verify-Add-in.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics-pr/blob/live/WorkplaceAnalytics/MyAnalytics/Setup/Verify-Add-in.md)
* Product: **wpa**
* GitHub Login: @rodonahu
* Microsoft Alias: **v-pascha**

**Comment by paul9955** [comment]
Thank you, dr-ivan, for your comment!  The process of installing the Outlook add-in is automatic; there are no steps for MyAnalytics participants to follow. We will remove the text that refers to a manual installation. Again, we appreciate your alerting us of this!
