### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by sysadmin-scs** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#130]
"You are receiving the Briefing email because your admin has enabled this email for your organization" 

I take issue with that statement. As an admin, I took no action. Microsoft pushed this feature and turned it to "enabled" as default. At least that's how I understand it. Can you clarify what the default is?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0a83186-6909-edb8-7de3-7a5c9307a0a1
* Version Independent ID: 9ba1d4d8-60ba-1c4d-f7e8-e9a92e74727d
* Content: [Briefing email overview - Cortana](https://docs.microsoft.com/en-us/briefing/be-overview)
* Content Source: [Briefing/be-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Briefing/be-overview.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **madehmer**

**Comment by martin8777** [comment]
Yes, I queried that too. Don't expect any response on here though from anyone at MS.

**Comment by madehmer** [comment]
@sysadmin-scs and @martin8777 - Thank you so much for your valuable feedback. The docs are now reworded to: "You are receiving the Briefing email because this email is currently on for your organization."

**Comment by martin8777** [comment]
Will the actual email that goes out get changed? That's the issue, is that the email that the users are going to get implies we are to blame for it.

**Comment by madehmer** [comment]
@martin8777 -I'll pass your feedback on to the team and ask that the email is reworded accordingly. Thanks!
