### ISSUE TITLE
Script missing -Append

### ISSUE THREAD

**Issue by ii-batman** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#131]
Hi Team, 
The step 2- the script is missing _-Append_ on the Export-Csv command.
Otherwise you will only get on line on the exported file.
`Get-UserBriefingConfig –Identity $upn | Export-Csv $outFileName -Append
![Capture](https://user-images.githubusercontent.com/60931858/84676451-703e4000-af25-11ea-9de0-bf34d703d79a.PNG)
`
Thanks, ii

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cee44a2-5742-83c0-ee3e-82a3a3f9417e
* Version Independent ID: ad800194-4e32-0529-6844-7529a0d670d7
* Content: [Configure Briefing email - Cortana](https://docs.microsoft.com/en-us/briefing/be-admin)
* Content Source: [Briefing/be-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Briefing/be-admin.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **madehmer**

**Comment by madehmer** [comment]
@ii-batman -You're correct. I've updated the docs accordingly. Thank you so much for your time on this!

**Comment by martin8777** [comment]
> @ii-batman -You're correct. I've updated the docs accordingly. Thank you so much for your time on this!
When can we expect to get an option to turn this off for the entire tenant?

**Comment by madehmer** [comment]
@martin8777 - You can now opt out a tenant. See [Tenant-level configuration](https://docs.microsoft.com/Briefing/be-admin#tenant-level-configuration) for details.

**Comment by ii-batman** [comment]
@madehmer @martin8777 
Great! A day after I Powershell the lot! 
I can't see it on my Tenancy yet... will keep checking...
