### ISSUE TITLE
Incorrect WPA url

### ISSUE THREAD

**Issue by rpanday** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#133]
In section https://docs.microsoft.com/en-us/Workplace-Analytics/tutorials/power-bi-bc#odata-request-failed

Url is listed as https://workplace.analytics.office.com , there is an extra dot between workplace & analytics.

It should be https://workplaceanalytics.office.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 208c8848-3e5a-2c94-d89f-fba11efdd208
* Version Independent ID: 054b67b2-f71f-4f71-f055-1b47362dc6e3
* Content: [Power BI Business continuity - Workplace Intelligence](https://docs.microsoft.com/en-us/Workplace-Analytics/tutorials/power-bi-bc#odata-request-failed)
* Content Source: [WorkplaceAnalytics/Tutorials/power-bi-bc.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Tutorials/power-bi-bc.md)
* Product: **wpa**
* GitHub Login: @madehmer
* Microsoft Alias: **madehmer**

**Comment by paul9955** [comment]
Hi rpanday,
Thanks much for this correction! We've made the fix in the documentation:
[OData request failed](https://docs.microsoft.com/en-us/Workplace-Analytics/tutorials/power-bi-bc#odata-request-failed)
 -- paul9955
