### ISSUE TITLE
User can override briefing email tenant-level setting?

### ISSUE THREAD

**Issue by mheptinstall** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#134]
> If you disable the Briefing email at the tenant level, users in your organization will not receive the Briefing email, **but individual users can override this tenant-level setting.**

How does an individual user override the tenant-level setting? 
How would an administrator know whether they have overridden this setting?

In our tenant the briefing email has been disabled at the tenant level, if I check `Get-UserBriefingConfig` for my account the property `IsEnabled` is True. Will I receive the briefing email or not?

Checking https://briefing.microsoft.com/ it says I am subscribed. If I unsubscribe and do `Get-UserBriefingConfig` again the property `IsEnabled` is still True.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cee44a2-5742-83c0-ee3e-82a3a3f9417e
* Version Independent ID: ad800194-4e32-0529-6844-7529a0d670d7
* Content: [Configure Briefing email - Cortana](https://docs.microsoft.com/en-us/briefing/be-admin)
* Content Source: [Briefing/be-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Briefing/be-admin.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **madehmer**

**Comment by madehmer** [comment]
@mheptinstall - Yes, individual users can choose to opt out or back in to receiving Briefing email at any time at [cortana.office.com](cortana.office.com) regardless of the tenant setting.
