### ISSUE TITLE
Automatic reply date values

### ISSUE THREAD

**Issue by johnbergin-amtsybex** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#135]
Under "Set automatic replies", are [START DATE] and [END DATE] placeholders for manual inputs or variables based on the preceding out of office date range?

The latter could be a handy feature if it is not already.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bbb07c4-2770-4b71-f563-e8f9f5d3c157
* Version Independent ID: 9801de76-e9c2-9308-7a41-d517172c3e46
* Content: [Use Insights - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/use-the-insights#plan-your-time-away)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/use-the-insights.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/use-the-insights.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-pausch**

**Comment by paul9955** [comment]
Hi John! 
I'm looking into this for you now. I've contacted the owners of this feature and I'll let you know what I find. 
Thank you,
 - Paul

**Comment by paul9955** [comment]
Hi John,
Thank you for your comment. It prompted us to add a clarifying note to the documentation about what text appears in this field when you want to set automatic replies. I've also passed on to the product team your idea to prepopulate [START DATE] and [END DATE] placeholders with the preceding values for a person's OOF time.
Thanks again,
 -- Paul

**Comment by paul9955** [comment]
Hello John,
I checked one aspect of this again. If you do NOT have an automatic reply from a previous OOF period, the [Start date] and [End date] fields should be pre-populated based on the OOF dates that you selected in the "Plan your time away" card. 
Is this the behavior you're seeing? If not, then it's a bug and I'll report it to the product team. 
Thanks!
 -- Paul

**Comment by johnbergin-amtsybex** [comment]
Just did a test and the [START DATE] and [END DATE] were **not** updated with the OOF dates.

However, I did notice that the "Set automatic replies" card **did** autofill the dates from the preceding "Select dates" card so that's close enough i.e. if you set the OOF dates _then_ fill in the auto reply, it should autofill your preceding dates.

**Comment by paul9955** [comment]
Thank you, John,
I've passed your observation on to the product team. 
 -- Paul
