### ISSUE TITLE
Refresh/Update details

### ISSUE THREAD

**Issue by laughey** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#136]
Needs updating to reflect Microsoft 365 name change.

Also, reference to how a tenant admin finds such settings is incorrect (for me anyway). I don't see:

I see (and can): _Expand_ **Settings**
I don't see (and can't): _Select_ **Services & add-ins**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 381cb456-e75f-04fb-f4eb-2d6aa4d7a3a8
* Version Independent ID: 1908491e-d901-90a0-e29a-33327cfa1a2d
* Content: [MyAnalytics configuration for Office 365 administrators - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/setup/configure-myanalytics)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Setup/configure-myanalytics.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Setup/configure-myanalytics.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **v-pausch**

**Comment by madehmer** [comment]
@laughey - The MyAnalytics documentation will be updated soon to reflect the new Microsoft 365 brand name change. To get help with not seeing **Services & add-ins**, confirm you are logged in with the applicable admin credentials. If you're still unable to see it:
1. Go to [MyAnalytics](https://myanalytics.microsoft.com/) and select **Feedback** at the lower left of the page. 
2. Complete the form and provide your contact info, so the team can follow up with you directly for this issue. 
Thank you for your feedback!
