### ISSUE TITLE
Edit

### ISSUE THREAD

**Issue by racheljameson** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#137]
"The file will include any standard or customized metrics you specify. The IsActive column in the output file is True if the employee sent at least one email during the specified time period for the query."

should be updated to:

The file will include any standard or customized metrics you specify. The IsActive column in the output file is True if the employee sent at least one email or one instant message during the specified time period for the query.

it looks like its updated further down in the article, but not earlier on.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93ccb74d-da5f-bb1e-c496-88a1b07b5237
* Version Independent ID: 24b36380-cb72-4514-3377-43c2eb692ac0
* Content: [Person queries in Workplace Analytics - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/tutorials/person-queries)
* Content Source: [WorkplaceAnalytics/Tutorials/Person-queries.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Tutorials/Person-queries.md)
* Product: **wpa**
* GitHub Login: @paul9955
* Microsoft Alias: **v-midehm**

**Comment by paul9955** [comment]
Hi Rachel,
Thank you much for finding this and pointing it out!
We've just fixed the omission: [Person queries](https://docs.microsoft.com/workplace-analytics/tutorials/person-queries).
-- Paul
