### ISSUE TITLE
Linking the tasks from Cortana Analytics

### ISSUE THREAD

**Issue by n4niamh** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#138]
Is there anyway the "Follow up on tasks" in the new "Briefing emails" from Cortana can be added into the Task list on MS Outlook?

**Comment by madehmer** [comment]
@n4niamh - This functionality is not yet available. However, the team is working on it, so it'll be available soon. Thank you for asking!

**Comment by madehmer** [comment]
@n4niamh - Thanks again for your feedback! Please use [cortana.office.com/briefing?v=feedback](cortana.office.com/briefing?v=feedback) to send us feedback about Briefing. The FAQ doc has been updated accordingly.
