### ISSUE TITLE
Feedback option

### ISSUE THREAD

**Issue by sysadmin-scs** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#139]
Q7 of the FAQ takes me to a page where I cannot provide feedback - I can only click the unsubscribe link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2a78fb8-beb3-d0d0-fb44-0ba3de4832d1
* Version Independent ID: 546ca6cf-7d18-39be-20d2-f27a01b85976
* Content: [Briefing FAQs - Cortana](https://docs.microsoft.com/en-us/briefing/be-faqs)
* Content Source: [Briefing/be-faqs.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Briefing/be-faqs.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **madehmer**

**Comment by madehmer** [comment]
@sysadmin-scs - You're right, I'll pass this on to the team to fix this. Thank you so much for pointing it out!
