### ISSUE TITLE
Link to Workplace Analytics is not correct

### ISSUE THREAD

**Issue by MSFTEfeedback** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#14]
In the section of this page called "MyAnalytics vs. Workplace Analytics", the link to Workplace Analytics takes you to a page that shows how the admin can set up MyAnalytics. It appears to me that this link should really direct the user to information about the Workplace Analytics tool.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ede52900-0a1f-1713-9f9b-44af2fd64dbd
* Version Independent ID: fc2b7ff3-f708-c5ec-15da-c2cf7e01c677
* Content: [Privacy guide for Microsoft MyAnalytics - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/Workplace-Analytics/myanalytics/overview/privacy-guide)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Overview/Privacy-Guide.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics-pr/blob/live/WorkplaceAnalytics/MyAnalytics/Overview/Privacy-Guide.md)
* Product: **mya**
* GitHub Login: @buntus
* Microsoft Alias: **v-pascha**

**Comment by madehmer** [comment]
Thanks for the feedback! You're correct. That should link to a Workplace Analytics overview. and will be fixed by end of today.
