### ISSUE TITLE
Add SharePoint Tasks to Insights Outlook add-in

### ISSUE THREAD

**Issue by SheTriedIt** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#140]
Out of the blue this Insights pops up in my Inbox at work. I didn't ask for it, so either Microsoft pushed it or my company did.

It was way off base in reading my emails and trying to determine what tasks there might be. Not at all helpful and very annoying.

It created a distraction and extra work and I clicked through to see what it was.

My team does, however, have a SharePoint site with tasks and other information. How about adding SharePoint functionality to ACTUAL tasks. I would love for the team to get reminders about tasks coming due in their Inbox once or twice a week (Monday morning and Friday afternoon).

**Comment by madehmer** [comment]
Thanks for your feedback. I'll pass it on to the development team.
