### ISSUE TITLE
Adaptive or HTML version

### ISSUE THREAD

**Issue by ivandretvic** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#141]
Under Adaptive or HTML version, you should make it more obvious that ActiveSync mobile mail clients will also get HTML format. Obvious to me but others may question it.
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0a83186-6909-edb8-7de3-7a5c9307a0a1
* Version Independent ID: 9ba1d4d8-60ba-1c4d-f7e8-e9a92e74727d
* Content: [Briefing email overview - Cortana](https://docs.microsoft.com/en-au/briefing/be-overview)
* Content Source: [Briefing/be-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Briefing/be-overview.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **madehmer**

**Comment by madehmer** [comment]
Thanks for your feedback. I'll update the overview doc accordingly.
