### ISSUE TITLE
Look back at historical data

### ISSUE THREAD

**Issue by buddyblair** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#142]
I would like to be able to compare my data from this week to this week last year or last quarter. Is there a way to do this?

**Comment by paul9955** [comment]
Hi Buddy,
I checked into this for you. Unfortunately, there currently is no way to get historical data from MyAnalytics. But I've passed your idea on to the product team for future consideration. 
Thank you,
 -- Paul (MyAnalytics documentation)
