### ISSUE TITLE
Availability in GCC

### ISSUE THREAD

**Issue by greenchevy65** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#143]
Being an GCC tenant admin I find it useful if there is some sort of mention of the availability of this from a GCC tenant standpoint somewhere at the top of the document.  Otherwise we read clear to the bottom and then follow all the directions to only find that it is not available in our tenant.  Our users also find this documentation and wonder why they are not receiving these emails and want us to activate it but we can't.

Thank you for listening,
Dana White

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cee44a2-5742-83c0-ee3e-82a3a3f9417e
* Version Independent ID: ad800194-4e32-0529-6844-7529a0d670d7
* Content: [Configure Briefing email - Cortana](https://docs.microsoft.com/en-us/briefing/be-admin)
* Content Source: [Briefing/be-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Briefing/be-admin.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**

**Comment by madehmer** [comment]
@greenchevy65 - Thank you for asking about this. The new Briefing is being released in stages and unfortunately, the GCC release is not ready yet. When Briefing is available in GCC, you should see a product announcement about it. In the interim, we very much appreciate your feedback and your patience!
