### ISSUE TITLE
Docs reference an Insights icon that doesn't exist

### ISSUE THREAD

**Issue by drk-mtr** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#144]
I want to disable Outlook Insights but cannot see how. Update: I can see an Insights icon in the Ribbon after opening a new email message. I can also disable it by going to the "feedback" link access by clicking the "insight" itself and disable it from here. It is just the Insights icon referred to in the instructions (that I interpreted to be referring to the main ribbon) that is a bit confusing i.e. I can't see that option in the ribbon on the main view.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae5243bf-bda7-c9a6-1f36-7c011e17988b
* Version Independent ID: 5e5ff830-dc34-73e6-670d-acf9d5617b90
* Content: [Inline suggestions in Outlook - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/mya-notifications)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/mya-notifications.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/mya-notifications.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-pausch**

**Comment by paul9955** [comment]
Hi drk-mtr,

First, I'd like to ask whether you tried the steps in the procedure [Opt out of the Insights Outlook add-in](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/add-in#opt-out-of-the-insights-outlook-add-in)? 
If so, the Insights add-in should be disabled. But are you still seeing the icon in the ribbon at this point?

Thank you,
 - Paul
