### ISSUE TITLE
Missing Settings Option From Steps

### ISSUE THREAD

**Issue by AndyH16** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#145]
The steps to configure the briefing email mention switching on the new admin center UI, which I have. It then says to navigate to the Settings option in the left pane which is missing for me! I have seen screenshots where this is listed so not sure why this is the case! I have tried different browsers and different devices all with the 'Settings' option missing.

If I turn off the new UI I can see a 'Settings' option but then I don't have the options require for the briefing email.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cee44a2-5742-83c0-ee3e-82a3a3f9417e
* Version Independent ID: ad800194-4e32-0529-6844-7529a0d670d7
* Content: [Configure Briefing email - Cortana](https://docs.microsoft.com/en-gb/Briefing/be-admin#tenant-level-configuration)
* Content Source: [Briefing/be-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Briefing/be-admin.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**

**Comment by AndyH16** [comment]
I have since found out how to get to the Settings menu. It seems there is a bug in the admin portal:

1.     From the new Admin Center if I click on the name of our organization (in the main screen, to the left of the search box).
2.     This brings up the Organization Information window, but behind it has some additional settings.
3.     If I close this window and click on ‘Services’ the ‘Settings’ option now appears in the left bar!!

It disappears as soon as I refresh the page but at least I have a workaround.

**Comment by madehmer** [comment]
@AndyH16 - I'm glad you found a workaround. I'll pass your feedback on to the team. Thanks for following through with this feedback!
