### ISSUE TITLE
cortana breifing emails

### ISSUE THREAD

**Issue by dogdaynoon** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#146]
Long pause... tilts head down and shakes...

What the **** is wrong with you Microsoft?

made account to post this.

**Comment by dstrome** [comment]
We appreciate your feedback, however, we ask that you abide by the [Code of Conduct](https://opensource.microsoft.com/codeofconduct/). Inappropriate language will not be tolerated.
