### ISSUE TITLE
Book Focus Time Feature

### ISSUE THREAD

**Issue by KEJorgensen** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#147]
For the Focus Plan.

I'm not getting an option to "Book time now" only the "Review" feature. It worked fine until last week and also removed all the Focus Time meetings on my calendar.  

No change turning the plan on/off or automatic/reminders.

**Comment by madehmer** [comment]
@KEJorgensen - Thank you for asking. I'm sorry to hear about this issue. It might be a bug. Would you please open [your dashboard](https://myanalytics.microsoft.com/), select **Feedback** near the bottom in the left navigation pane, and then fill out and submit your issue there? Be sure to select the checkbox that allows them to contact you about your feedback. Then the team can follow up and confirm if it's a bug and/or how they can help you get your focus plan back on track!
