### ISSUE TITLE
Only 'Do Not Disturb' for Teams Status, Ability to choose default status shown during focus time desired with alternate options of Busy or Away 

### ISSUE THREAD

**Issue by acbee76** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#148]
Our business unit's customer-service focus policies discourage the use of the Teams status 'Do Not Disturb' unless presenting materials in meetings. As such, have not been able to promote the My Analytics tool because there is no ability to determine what your status appears as only whether you're able to be booked for that time on others' calendars. Enhancement request for displayed user status options aside from only DND--at minimum Busy even better if Away is also available.

**Comment by paul9955** [comment]
Hi acbee76,
I contacted the product team about this. I heard back that they are working on adding focus plan settings that will address the circumstance that you describe. However, I don't know how soon the feature will appear, but new features are frequently announced in the [techcommunity blog](https://techcommunity.microsoft.com/t5/workplace-analytics-myanalytics/bg-p/Office365AnalyticsBlog). 
Thank you for your interest in MyAnalytics and for your comment,
 -- Paul
