### ISSUE TITLE
How to control timing of Cortana briefing

### ISSUE THREAD

**Issue by n6rno** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#149]
My organization has enabled the Cortana daily briefing... I am finding it useful.
However, the briefing starts too late in my day.
I often start around 4am, but the briefing shows up in my inbox around 7:10 each morning.
It would be nice to grant users control over when the briefing is created.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cee44a2-5742-83c0-ee3e-82a3a3f9417e
* Version Independent ID: ad800194-4e32-0529-6844-7529a0d670d7
* Content: [Configure Briefing email - Cortana](https://docs.microsoft.com/en-us/briefing/be-admin)
* Content Source: [Briefing/be-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Briefing/be-admin.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**

**Comment by madehmer** [comment]
@n6rno - I'm super glad to hear you're getting value from your Briefings. I'll forward this great idea to the Team to consider for a future release. For now, your [Briefing](https://docs.microsoft.com/briefing/be-overview) should show up within the first two hours of the time period you have set for **Meeting hours** in [Outlook](https://outlook.office.com/calendar/options/calendar/view/appearance). Thank you for your feedback!
