### ISSUE TITLE
Transcription for Video: Overview for admins

### ISSUE THREAD

**Issue by TonyCarlin** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#15]
Is it possible to get a transcription for the initial Overview video?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a311b001-b100-2cc5-2651-9324178605d7
* Version Independent ID: a687cfbe-9693-d0ae-1207-4a23ff7e26cf
* Content: [Workplace Analytics Setup Checklist - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/workplace-analytics/setup/set-up-workplace-analytics#feedback)
* Content Source: [WorkplaceAnalytics/Setup/Set-up-Workplace-Analytics.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics-pr/blob/live/WorkplaceAnalytics/Setup/Set-up-Workplace-Analytics.md)
* Product: **wpa**
* GitHub Login: @madehmer
* Microsoft Alias: **paul9955**

**Comment by paul9955** [comment]
Hi Tony,
Yes, I will try to attach a transcription of that video to this comment area. 
I hope the video was helpful. 
[admin-overview.txt](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/files/2350853/admin-overview.txt)

**Comment by TonyCarlin** [comment]
It was great, at the moment is hard to get really good MSFT collateral on this subject.

Regards,

Tony

TONY CARLIN  |  Principal Solution Architect and National Practice Lead, Continuous Services<https://www.insight.com/en_US/solve/services/workforce-applications/continuous-services.html> |  BlueMetal, a division of Insight
617.216.7754  |  tcarlin@bluemetal.com<mailto:tcarlin@bluemetal.com>  |  bluemetal.com<http://bluemetal.com/>  |  insight.com<http://insight.com/>

Microsoft 2018 Worldwide Partner of the Year - AI
Microsoft 2017 Worldwide Partner of the Year  – Mobile App Development
Microsoft 2016 Worldwide Partner of the Year – IoT

**Comment by TonyCarlin** [comment]
It was great, at the moment is hard to get really good MSFT collateral on this subject. 

Regards,
