### ISSUE TITLE
MyAnalitics features disabled for the whole company but still receiving Focus edition

### ISSUE THREAD

**Issue by ChaDess** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#150]
Hello, 
I have disabled all 3 MyAnalytics options from the 365 Admin center> Services and Add-ins > MyAnalytics, as our organisation is not yet ready for it.

Normally, no user should receive the digest, or see the Outlook add-in, right?
![image](https://user-images.githubusercontent.com/64793222/87793364-0f17ce00-c83d-11ea-83c7-4b3f4c650391.png)

However, I still receive the digest, and still see the Outlook add-in. How is that possible? What can I do to completely stop this?

Thanks for your help,
Kind regards,
Charlotte

**Comment by paul9955** [comment]
Hi Charlotte,
I've contacted the product team about this and they'd like to help you troubleshoot it. They can do this better if they can contact you. Here's a way to safely share your contact information with them:
1. Open the MyAnalytics dashboard at [myanalytics.microsoft.com](https://myanalytics.microsoft.com/).
2. At the bottom of the left navigation pane, select **Feedback**. 
3. In the **Feedback** dialog box, briefly describe the problem, as you have here.
4. Select **Allow Microsoft to contact <your user ID> about this feedback** and select **Submit**.
Thank you Charlotte,
 - Paul (MyAnalytics documentation)

**Comment by ChaDess** [comment]
Thanks Paul, will do now!
