### ISSUE TITLE
Including 500 Error in the FAQ section

### ISSUE THREAD

**Issue by karleesm** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#151]
Are we able to add an Error 500 reason to the FAQ section here (and other relevant places in the Docs for WpA?  I have had a couple of customers activate licenses and then try to access the site, so they come directly to me.  Would be great to provide a searchable response that doesn't require reaching out to MSFT team.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2848ac8e-89bc-c960-21a3-f7132b6d546c
* Version Independent ID: d576e83f-a91b-ac37-eea5-f3b6bab99102
* Content: [Assign Workplace Analytics user roles and groups in Azure Active Directory (AAD) - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/use/assigning-wpa-user-and-group-roles-in-azure-ad)
* Content Source: [WorkplaceAnalytics/Use/Assigning-wpa-user-and-group-roles-in-azure-ad.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Use/Assigning-wpa-user-and-group-roles-in-azure-ad.md)
* Product: **wpa**
* GitHub Login: @paul9955
* Microsoft Alias: **v-mideh**

**Comment by madehmer** [comment]
Because we're working on doc edits via email, I'm closing the issue here. Thanks for your time on this Karlee!
