### ISSUE TITLE
Workplace Analytics by role

### ISSUE THREAD

**Issue by LynneThomson** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#152]
Hi
Our team wants to use Workplace Analytics to coach employees to better manage their time esp. during pandemic/WAH. Are there any norms for % of focus time especially by level (Execs should spend more time in meetings than a lower level IC.)  
Thanks

**Comment by madehmer** [comment]
@LynneThomson - Hi. Thank you for asking about Workplace Analytics! Does your team currently use Workplace Analytics? If so: 
* Your managers can use [Workplace Analytics Plans](https://docs.microsoft.com/workplace-analytics/tutorials/solutionsv2-intro) to help coach their employees. 
* You can also use this list of [Best Practices](https://docs.microsoft.com/workplace-analytics/tutorials/gm-best-practices) for different work patterns, such as [Focus](https://docs.microsoft.com/workplace-analytics/tutorials/gm-focus) and [Manager coaching](https://docs.microsoft.com/workplace-analytics/tutorials/gm-coaching) for ideas. 
* Your analysts can also use Workplace Analytics [Explore data](https://docs.microsoft.com/workplace-analytics/use/explore-intro) and [Queries](https://docs.microsoft.com/workplace-analytics/tutorials/query-basics) to analyze and report collaboration and focus activity for your organizational business leaders. 
* Your analysts can also use [Power BI templates](https://docs.microsoft.com/workplace-analytics/tutorials/power-bi-templates) designed specifically to work with Workplace Analytics queries to visually evaluate and more broadly report current organizational work patterns through Power BI.

If you don't currently use it, see [Microsoft Workplace Analytics](https://www.microsoft.com/microsoft-365/business/workplace-analytics) to learn more about purchasing it.
