### ISSUE TITLE
Make Insights configuration settings more inclusive to allow for shift workers and those whose hours differ from day to day

### ISSUE THREAD

**Issue by SueSilv** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#153]
Can we introduce changes to configuration settings for Work week in Insights to allow the flexibility for shift workers to enter patterns 4 - 8 weeks ahead and for those with a static weekly working pattern but which differs day to day to be able to enter their distinct patterns and improve the inclusivity of this add in?
![image](https://user-images.githubusercontent.com/69040715/89032196-0b4f7580-d32c-11ea-9aba-5db4c2581914.png)

**Comment by madehmer** [comment]
@SueSilv - Thanks for reaching out. Insights currently uses your Outlook settings, so it might be worth providing Outlook this feedback as well. However, I'll also pass it on to our dev team as well to consider an additional level of calendar customization just for Insights for a future release. Happy Friday!
