### ISSUE TITLE
Office versions supported by the modern add-in Insight

### ISSUE THREAD

**Issue by javicartin** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#154]
Hello, just wanted to be clear on that article, we can see Office 365 under applies for, which I believe is C2R but under requirements, it is saying Outlook 2015 or later, Outlook 2015 doesn´t exist, so, this has to be fixed and the other thing just to be 100% clear, that add-in is NOT available for Office MSI, it would be good to add MSI not apply.
https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/add-in

**Comment by madehmer** [comment]
@javicartin - Thanks for your feedback. I'll work the team to update the docs as applicable.
