### ISSUE TITLE
Automatically book focus meetings could be set to be tentative

### ISSUE THREAD

**Issue by sebastienricher** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#155]
When using the auto-book focus time feature (which is very nice!) I would prefer to have meeting set as tentative, this way it's easier for my colleagues to book anyways if required and ask me if it's ok. Rather than have a hard time to find a spot and push a meeting to next week for nothing.

Thanks!

**Comment by madehmer** [comment]
@sebastienricher - Thanks for your feedback. I'll pass your great suggestion on to the team.
