### ISSUE TITLE
Focus time with Tentative option

### ISSUE THREAD

**Issue by jamieherrera** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#156]
I appreciate the Focus Plan feature, It does keep me on track and the pause of popup notifications is more helpful than I thought!

I would like my focus time to default to Tentative, or even better: to have a setting and icon in Office 365 that is for Focused which is different from Do Not Disturb (Teams) or Busy (Outlook). Most weeks my schedule looks open but one-off meetings are scheduled during the week, anywhere from 6 am to 3 pm my time. I want my calendar to be available to others for booking meetings that we need, and am concerned that showing 2-hour Focus time periods as "busy", or Teams status of "Do not disturb" force others to schedule our meetings during other times that are not ideal, when I could just as easily move my Focus time instead. It would be great to show that time as free to others when viewing my availability, and get an alert if it overlaps with a focus time, with a suggested other time in the same day to set my focus time to. Currently, there is an alert "do you want ti change focus time?" but no link or button to act on. 

Jamie

**Comment by madehmer** [comment]
@jamieherrera - Thank you for your feedback. This is definitely on the team's list to consider for future releases.

**Comment by jamieherrera** [comment]
Thank you!

Jamie
