### ISSUE TITLE
Can we get an option for focus time to be booked as tentative?

### ISSUE THREAD

**Issue by julesb2018** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#157]
We have found people have tried focus time - but it blocks out too much of their calendar and others can only see as busy.
Is there an option to have focus time block out but show as tentative?
This would allow others who need to send meeting requests at least the chance to see when people are genuinely busy.
[this might be a user voice request - but just following the prompts on the page to give feedback on the product]
Thanks

**Comment by madehmer** [comment]
@julesb2018 - Thank you for your great feedback. Yes, this is definitely on the team's list to consider for a future release.
