### ISSUE TITLE
"Focus time" loses special color in outlook 365 on Macbook 

### ISSUE THREAD

**Issue by ysybz** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#158]
The special "green color" of automatically booked "focus time" got lost once the green color was manually selected once as a category color in outlook 365. 
Now all "focus time" was automatically added to outlook without a special color, although the default "green" color is not in use as a category color. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40f032f9-30a5-b801-b3c2-602a6ef552d3
* Version Independent ID: bffa68c6-76a6-3de4-ec42-ab75c6a264d2
* Content: [Focus plan - Workplace Intelligence](https://docs.microsoft.com/en-us/Workplace-Analytics/myanalytics/use/focus-plan#automatic-booking-of-focus-time)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/focus-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/focus-plan.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-pausch**

**Comment by madehmer** [comment]
@ysybz - Thank you for your feedback. I'll pass it on to the team to consider fixing in a future release.
