### ISSUE TITLE
I would like to set focus time to tentative automaticly

### ISSUE THREAD

**Issue by Gullydwarf** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#159]
There currently is no way to change the setting of focus time to non-blocking. This means when people need to book an appointment with me the focus time shows up as taken, while in fact I can often still move it around my calendar.

**Comment by madehmer** [comment]
@Gullydwarf - Thanks for your feedback. This is definitely on the team's list to consider for a future release.

**Comment by Godsfunambulator** [comment]
I definitely want this time to come in automatically as tentative, and then I can change it if I have something specific that I don't want to have a meeting during...
