### ISSUE TITLE
Weekly Digest Email

### ISSUE THREAD

**Issue by toddjohnson39** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#16]
Is it possible to customize/brand the weekly digest email? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1531b80-1cd3-8654-27fd-1aa8f4a1c4cd
* Version Independent ID: ecc841f6-5f6b-8b26-0080-3f5288f92eaf
* Content: [MyAnalytics FAQ - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/overview/mya-faq)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Overview/MyA-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics-pr/blob/live/WorkplaceAnalytics/MyAnalytics/Overview/MyA-faq.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-pascha**

**Comment by paul9955** [comment]
Hi Todd, It's not possible to do such customization. However, we'd be interested in hearing what you visualize here. Beyond adding branding, are there other ways you might want to customize the weekly digest email? Thank you much! - Workplace Analytics documentation team

**Comment by paul9955** [comment]
Thank you for your response, Todd. If you don't mind sharing, I'd like to ask what the goal is of these customizations. Is the idea, for example, to improve the trust factor among MyAnalytics participants who might have privacy concerns? Knowing your reasoning here can help us identify solutions (such as the very customization functionality that you're requesting) that we could incorporate in future versions.

**Comment by paul9955** [comment]
Todd, we welcome any other feedback you have. Thanks again!
