### ISSUE TITLE
Adding Plugin Via URL/File option 

### ISSUE THREAD

**Issue by CyberColsar** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#161]
This page is not giving instructions to add plugin via url/file. Kindly add it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74c447e0-fae6-a016-c6bf-01438701ce17
* Version Independent ID: b6d82917-aee4-2808-00ce-df6c20b75766
* Content: [Insights Outlook add-in - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/add-in#open-the-insights-add-in)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/add-in.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/add-in.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-pausch**

**Comment by madehmer** [comment]
@CyberColsar - Thanks for your feedback. Per the team, this way of adding the plug-in will not be added to the documentation because the currently documented steps apply and are easier for all users.
