### ISSUE TITLE
Prepare for your meetings

### ISSUE THREAD

**Issue by helenphamova** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#162]
Hi Team,

I love the prepare for your meetings fuction and wanted to ask you wheather you could extend this function for various calendars? I am using various calendars and can only see the options for my default calendar. I have several calendars plus managing others calendars as well so I would highly appreciate the possibility of switching between the calendars.

Thanks!!

**Comment by madehmer** [comment]
@helenphamova - Thank you for your feedback! So glad to hear you love the Prepare for meetings feature. I've passed your question on to the team. The Briefing uses the mailbox account settings. I'll let you know if I learn of a way you can do set this up from Outlook. In the meantime, your great suggestion is at least on their list to consider for a future Briefing release.
