### ISSUE TITLE
Microsoft Teams MyAnalytics - Meeting Habits

### ISSUE THREAD

**Issue by PaulMika** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#163]
In the Meeting Habits section of MyAnalytics, is the "joined meetings on time" statistic based on joining meetings by the scheduled start time, or is there an allowance for joining a meeting within a few minutes of the start time still considered "on time"?

**Comment by paul9955** [comment]
Hi PaulMika,
I'm checking with the product team about this. I believe MyAnalytics gives five minutes of leeway after the scheduled meeting start time, but I'll confirm that number for you. I should have the answer soon, so please check back on this page. 
Thank you,
 -- Paul (MyAnalytics documentation)

**Comment by paul9955** [comment]
Hi PaulMika,
The product team informed me that there is a bit of leeway (five minutes) in this situation. I've updated the documentation to reflect this; see [Meeting habit metrics](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/collaboration#meeting-habit-metrics).
Thank you for your initial question, and for your patience,
-- Paul (MyAnalytics documentation)
