### ISSUE TITLE
GDPR and disable for all

### ISSUE THREAD

**Issue by wUEZRs** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#164]
Include information on this page on how to do this for an Enterprise Admin

It is not without discussion appoved for GDPR in Europe so information on how to disable it for the tenant should be easily documented

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8a67904-138f-f4f9-af2d-3861b45d606f
* Version Independent ID: 9b55a580-c1fb-d28c-d415-361ea74f53e7
* Content: [Opt out of MyAnalytics - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/opt-out-of-mya)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/opt-out-of-mya.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/opt-out-of-mya.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-pausch**

**Comment by paul9955** [comment]
Hi wUEZRs,
Thank you for pointing this out. I have added a link to the procedure that I believe you're looking for. It describes how an admin can configure (grant or deny) access to MyAnalytics for an entire tenant at once. Here is the updated page:
[Opt out of MyAnalytics / Related topics / For admins](https://docs.microsoft.com/workplace-analytics/myanalytics/use/opt-out-of-mya#for-administrators). 
 - Paul, MyAnalytics documentation
