### ISSUE TITLE
Cortana briefing mail.

### ISSUE THREAD

**Issue by seyffu** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#165]
I have only received one mail to date, but it seem to be useful.

I feel the color of the unsubscribe option in the mail should be set to something like 'orangered' to stand out. I clicked it by accident and was nearly unsubscribed, which brings me to my second point.

On the 'feedback' page when you unsubscribe, maybe start with: "Was this a mistake, click here to re-subscribe". Or make the re-subscribe option at the bottom of the page much more prominent. I nearly missed it.

Regards

Ulrich

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0a83186-6909-edb8-7de3-7a5c9307a0a1
* Version Independent ID: 9ba1d4d8-60ba-1c4d-f7e8-e9a92e74727d
* Content: [Briefing email overview - Cortana](https://docs.microsoft.com/en-us/briefing/be-overview)
* Content Source: [Briefing/be-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Briefing/be-overview.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**

**Comment by madehmer** [comment]
@seyffu - I'm glad you're using Briefing and finding it useful. I've passed your great feedback on to the Team. Thank you so much for your time and your feedback!
