### ISSUE TITLE
Book time to focus - auto sets Teams to "focusing/DND"

### ISSUE THREAD

**Issue by rogersda322** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#166]
I am a big fan of the Book time to focus feature with Insights. What I do want to do is change a setting so when I am in my scheduled focus time my Teams status is not set to Focusing or DND by default. Is there an option that I am missing to make this change?

**Comment by paul9955** [comment]
Hi rogersda322, 
Sorry about the delay. I've contacted the product team about this. I'll reply back here as soon as I have a definitive answer. 
Thanks for your interest in the feature,
 -- Paul

**Comment by paul9955** [comment]
Hi rogersda322,
The product team responded and said that a feature is being developed that will affect Focus-plan settings. After it ships (perhaps this year), it will let you configure whether your Teams "presence" state will show as DND or simply as "busy" during focus time. When it appears, this feature will be available on the Focus page of your MyAnalytics dashboard.
 -- Paul
