### ISSUE TITLE
can or can not

### ISSUE THREAD

**Issue by zniezelski** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#167]
[Enter feedback here]

Can users override the settings or can they not override the settings. Sentence before says it will disable for all user.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cee44a2-5742-83c0-ee3e-82a3a3f9417e
* Version Independent ID: ad800194-4e32-0529-6844-7529a0d670d7
* Content: [Configure Briefing email - Cortana](https://docs.microsoft.com/en-us/briefing/be-admin)
* Content Source: [Briefing/be-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Briefing/be-admin.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**

**Comment by madehmer** [comment]
@zniezelski  - Thanks for asking! According to [Set access for one user](https://docs.microsoft.com/briefing/be-admin#set-access-for-one-user), it depends: 
* If you set the **Enabled** parameter to **$false**, the Briefing email will be **Off** for that user. The user cannot override this setting or opt in to the Briefing email.
* If you set the **Enabled** parameter to **$true**, the Briefing email will be **On** for that user. Users can then opt-out from [cortana.office.com](https://cortana.office.com/). If no action occurs, this setting applies by default. 
Hope this helps. If it's not working as described, please post your issue at [Briefing feedback](https://cortana.office.com/briefing?v=feedback) for additional help.

**Comment by zniezelski** [comment]
what happens when I "deselect the checkbox for Let people in your organization receive the Briefing email, and then select Save changes" on step 5 on this page https://docs.microsoft.com/en-us/briefing/be-admin?

Will it turn off the briefing email for people that were receiving the email

**Comment by madehmer** [comment]
@zniezelski - Apologies for my delay. My SME was out of the office.  Yes, this turns off the Briefing for all the users in that tenant. After you deselect the checkbox, all users in your organization will not receive Briefing email, including all those who were receiving Briefing email. However, individuals can explicitly subscribe again at [cortana.office.com](https://cortana.office.com).

**Comment by zniezelski** [comment]
Michele, 

Thanks for the fix! makes sense to me now.

Take Care,

Zach
