### ISSUE TITLE
Meeting habits Questions + Roadmap

### ISSUE THREAD

**Issue by AhmedBar93** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#168]
Hello all,
From the document, I can see that myanalytics shows only the total number of meetings you organized or accepted to attend, but what about if the meeting was organized by another user (assistance) on behalf of me, would it count? as at the moment it doesn't.

My second question, I couldn't find any details if you are willing in the future to let customers manager myanalytics and customize the data inside, is there any information on that?

Thanks all!

**Comment by madehmer** [comment]
@AhmedBar93 - You're correct, MyAnalytics does not currently include events created and accepted on your behalf by your assistant in your MyAnalytics data. I'll pass this idea to the team to consider as a setting/feature enhancement for a future release.  

About your second question, can you give me an example? Are you asking if a manager can customize the data for their direct reports? Or who would customize what MyAnalytics data for an individual? MyAnalytics is designed to only be seen by an individual about their personal, private data, which is for their eyes only. So how could it be customized and kept private? 

Thanks for your feedback!

**Comment by AhmedBar93** [comment]
Hello Michele,
Thank you so much for the prompt response!

About my second questions, I totally agree that in order to keep the data private no should have access to view them, if I may explain my question was whether the IT admins can customize the data and change the shown reports, let's say for example if the management sees that they want to add other statics for the management team which are not shown in the collaboration section, I know it doesn't sound logical to add something there out of the blue, but my question, at the moment is there any plan to let the IT admins manage the data and add other statics other then one shown.

Thank you again and sorry if my question sounds silly to you.

**Comment by madehmer** [comment]
@AhmedBar93  - It's a great question, not silly at all. Ok, I understand. No, there's nothing currently available for IT Admins to add or customize. However, your analysts or managers can use [Workplace Analytics Teamwork plans](https://docs.microsoft.com/workplace-analytics/tutorials/teamwork-solution), such as for Focus or Collaboration goals, for a specific team, which adds a custom section for tracking those specific goals in an individual's MyAnalytics data.  What type of statistics does your company want to add? And I'll pass your feedback to the team to consider for future releases. Thanks again for your questions and feedback!

**Comment by AhmedBar93** [comment]
Hello Michele,
Thank you for your response and sorry for the late reply!
I am completely satisfied with the information you provided! Thank you so much

Enjoy the weekend and I wish you a pleasant week ahead!
