### ISSUE TITLE
Status for Teams and Skype do not appear to change to "Focusing"

### ISSUE THREAD

**Issue by jason-collab** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#169]
Hi there.  We are not experiencing that the status changings during a "Focus" block as referenced [https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/focus-plan#chats-are-muted-during-focus-time](url)

Our scenario is a Teams user in "Teams Only" Coex mode and a Teams user in "SfB w/Collaboration" Coex mode.  Does it not work for interoperability modes?  If not, you may want to highlight that on your document.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40f032f9-30a5-b801-b3c2-602a6ef552d3
* Version Independent ID: bffa68c6-76a6-3de4-ec42-ab75c6a264d2
* Content: [Focus plan - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/focus-plan)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/focus-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/focus-plan.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-pausch**

**Comment by madehmer** [comment]
@jason-collab  - I've passed your feedback on to the team, but haven't heard back yet. It might be a bug they can fix. Thank you for your time on this!

**Comment by madehmer** [comment]
@jason-collab - We need more information about this issue. Would you please briefly describe your issue and give your contact info at [Briefing feedback](https://cortana.office.com/briefing?v=feedback)? Thanks again for your time on this!

**Comment by jason-collab** [comment]
I went ahead and submitted my explanation there as you requested.


Jason Hughes
Systems Analyst
The Greenheck Group
715-355-2258 Office

715-432-7867 Mobile
jason.hughes@greenheck.com<mailto:jason.hughes@greenheck.com>

________________________________

**Comment by madehmer** [comment]
@jason-collab -Thank you for your diligent follow up! Since this can be accessed by the public, I'm removing your info from here to be on the safe side. Have a great weekend!
