### ISSUE TITLE
Incorrect location of MyAnalytics settings at the tenant level

### ISSUE THREAD

**Issue by chrisblackstonedart** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#170]
To find the MyAnalytics settings at the tenant level, you need to go to Office 365 Admin -> Org Settings -> MyAnalytics

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 381cb456-e75f-04fb-f4eb-2d6aa4d7a3a8
* Version Independent ID: 1908491e-d901-90a0-e29a-33327cfa1a2d
* Content: [MyAnalytics configuration for Office 365 administrators - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/setup/configure-myanalytics)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Setup/configure-myanalytics.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Setup/configure-myanalytics.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **v-pausch**

**Comment by paul9955** [comment]
Hi chrisblackstonedart,
I'm sorry it's taken me so long to respond. I appreciate this correction. I've reviewing the steps our documentation on this now and I'll fix them as appropriate. 
Thank you, -- paul9955

**Comment by paul9955** [comment]
Hello chrisblackstonedart,

I appreciate your alerting me to this. I've now corrected the documentation accordingly, and many people will benefit: [Configure access at the tenant level](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/setup/configure-myanalytics#configure-access-at-the-tenant-level). 

Thank you again for your observation and comment! 
-- Paul
