### ISSUE TITLE
Linking to MS Learn modules that are about each PBI dashboard

### ISSUE THREAD

**Issue by m-m-powers** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#171]
[Enter feedback here]
Some of the PBI dashboard have additional training available on MS Learn:

- Business Continuity Dashboard at [aka.ms/wpa-bcd](HTTPS://aka.ms/wpa-bcd)
- Ways of Working Assessment at [aka.ms/wpa-collab](https://aka.ms/wpa-collab)
- Teams Insights at [aka.ms/wpa-teams](https://aka.ms/wpa-teams)
- Ways of Working Tracker at [aka.ms/wpa-i2a](https://aka.ms/wpa-i2a)

For each of these dashboards, would it make sense to link to their MS Learn training modules under the "Tips and FAQs" section, or under "About the reports"?

This way users could find more training and info on each dashboard beyond what is in the documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f956ef4d-db6f-aa40-3ed6-572893e49b68
* Version Independent ID: bef0b537-6004-ad42-1227-dea193ea8d27
* Content: [Ways of working assessment dashboard - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/tutorials/power-bi-collab-assess)
* Content Source: [WorkplaceAnalytics/Tutorials/power-bi-collab-assess.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Tutorials/power-bi-collab-assess.md)
* Product: **wpa**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**

**Comment by paul9955** [comment]
Thank you, Mark!
I've added these links. They will help people come up to speed. 
 -- Paul Schafer
