### ISSUE TITLE
Amend lunch hour to custom time

### ISSUE THREAD

**Issue by CravenCMS** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#172]
Lunch hour is fixed between 12:00 - 13:00.

Personally, my lunch is 13:00-14:00, however the ability to customise the lunch hour would be beneficial for many. 

Now with focus time being automatically distributed into my calendar, I find it covering my lunch hour many days in the week.

**Comment by madehmer** [comment]
@CravenCMS - Thanks for your feedback! You can change the default lunch hour on your calendar in [**Insights** > **Settings**](https://docs.microsoft.com/workplace-analytics/myanalytics/use/use-the-insights#set-lunch-hours-in-settings). This change should prevent focus time from covering your lunch hour.
