### ISSUE TITLE
The "Open Rate" feature of insights does not recognize group email addresses

### ISSUE THREAD

**Issue by hmozaffari** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#174]
The open rate feature of insights does not recognize group email addresses (and most likely is not aware of number of users who are member of that group). So it consider it as one recipient and doesn't produce open rate for it even though it may have more than 5 members. It is reasonable for external addresses but I assume My Analytics is aware of members of internal emails groups.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bbb07c4-2770-4b71-f563-e8f9f5d3c157
* Version Independent ID: 9801de76-e9c2-9308-7a41-d517172c3e46
* Content: [Use Insights - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/use-the-insights#open-rate)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/use-the-insights.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/use-the-insights.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-pausch**

**Comment by paul9955** [comment]
Hi hmozaffari,
Thank you for your interest in this feature of MyAnalytics. I'd like to clarify what you're asking about. When you refer to "group email" addresses, do you mean "shared mailboxes"? If so, this is something that the Insights open-rates feature does not report on. (For this and other details, see the section [Exceptions to qualifying messages](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/use-the-insights#exceptions-to-qualifying-messages) in the documentation).
If you're referring to something other than shared mailboxes, please let me know and I'll look into this further for you.
Thank you,
 -- Paul

**Comment by hmozaffari** [comment]
Thanks @paul9955 for looking into this. I checked and the exact technical term for it is "Distribution List". For example email addresses of employees of marketing department are added to marketing@mycompany.com distribution list and when someone sends an email to marketing@mycompany.com all marketing department employees receive the email. But seems MyAnalytics recognize it as only one recipient and doesn't produce  insights for it even though dozens or hundreds of user receive that email.

**Comment by paul9955** [comment]
Hi @hmozaffari , Thanks for the clarification. I believe MyAnalytics counts the number of recipients after expanding distribution lists, but I'm verifying that now with the product team.   -- paul9955

**Comment by paul9955** [comment]
Hi @hmozaffari , I just heard back from an engineer on the product team. Here's the response: "MyAnalytics read statistics supports distribution lists. If there are more than 5 people in DL the open rate is shown. The users in the distribution list should be in the same tenant as of user to view the open rate." 
hmozaffari, are you seeing a behavior that differs from this?
Thank you, -- paul9955

**Comment by hmozaffari** [comment]
Thanks @paul9955! I found the problematic email.  That email was sent to 2 recipients and CCed a distribution list with 10 users (total 12 recipients) and MyAnalytics mentioned it is not qualified as minimum 5 recipients. However documents mentions CCs and BCCs are counted as recipients.

**Comment by paul9955** [comment]
Hi hmozaffari, I've passed this latest info on to the product team. I'll let you know what I hear back. 
Thanks, -- paul9955

**Comment by paul9955** [comment]
Hello hmozaffari,
I heard back from the product team. They said that if the users in DL are in the same tenant as a person who sent the email, that person should be able to see the open rate. The emails need to be no older than seven days. They are advising that you submit a ticket for this problem. They will need the following information in the ticket: Tenant info/ID, ID of person who sent the email, and the IDs of the emails that were sent. 
 -- paul9955
