### ISSUE TITLE
Cant open "Learn More" link from "MyAnalytics | Focus Edition" mail

### ISSUE THREAD

**Issue by BennyHerlambang** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#175]
Hi,
Regularly I received "MyAnalytics | Focus Edition" mail but currently cant open the link.
The page opened will show "Critical resource not found".
Any idea what to check?
Thanks

**Comment by madehmer** [comment]
@BennyHerlambang - Thanks for asking. I'm sorry you're having problems opening the Focus page with the link in the email. It's possible that you aren't signed in with the account licensed for MyAnalytics. You might ask your admin. However, it also could be a link error on our end too. Please report this issue through the **Feedback** link near the bottom of the left navigation in [MyAnalytics](https://myanalytics.microsoft.com/). Be sure to include contact information in case the team needs to contact you for more information.

**Comment by BennyHerlambang** [comment]
@madehmer 
Sorry for late reply. Unfortunately, even opening https://myanalytics.microsoft.com/ showed same error "Critical resource not found". 
Had also tried:
1. Open in private window in browser > sign in outlook for web > open the MyAnalytics email > click Learn more to check whether you can open the link. <-- still got same error message.
2. Open in private window in browser > sign in portal > click your head portrait > My Office profile > MyAnalytics > Focus. <-- failed on step "MyAnalytics" , got same error message.

I'm also reaching our admin, still awaiting for the response.

**Comment by madehmer** [comment]
@BennyHerlambang - Hello. Was your admin able to help you? It sounds like the MyAnalytics app has been turned off for your organization.  Your admin will need to turn it back on for you to use it. Please give your admin [this link](https://docs.microsoft.com/workplace-analytics/myanalytics/setup/configure-myanalytics) to confirm MyAnalytics is turned on and you are opted in.  Thanks again for reaching out!
