### ISSUE TITLE
Top Collaborators - Total Time

### ISSUE THREAD

**Issue by R-Catling** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#176]
The Calculation details for 'Total Time' in the top collaborators section is not explained. 
This information is useless if I don't know what it is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c80bdb40-6f61-b9e4-0098-5354d399f083
* Version Independent ID: 56239348-0977-4220-c8ab-40ab1e7f33a0
* Content: [MyAnalytics network page - Workplace Intelligence](https://docs.microsoft.com/en-us/Workplace-Analytics/myanalytics/use/network#network-tips)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/network.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/network.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **v-pausch**

**Comment by paul9955** [comment]
Hi R-Catling, 
Total time is defined in the [About the metrics](https://docs.microsoft.com/Workplace-Analytics/myanalytics/use/network#about-the-metrics) section on this page. Do you need more exact calculation details for this metric than this definition provides?
Thank you,
 -- paul9955
