### ISSUE TITLE
API/Automation Access

### ISSUE THREAD

**Issue by PylotLight** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#177]
Hi Team,

Was looking through the docs, and didn't see a way to have an automation tool schedule/book times for users in bulk at all.
Is this possible?

Regards,
Lochy.

**Comment by madehmer** [comment]
@PylotLight - Thanks for asking. No, MyAnalytics does not have an API or option that enables you to do that. However, individual users can automatically book focus time on their calendars through a [Focus plan](https://docs.microsoft.com/workplace-analytics/myanalytics/use/focus-plan).

**Comment by PylotLight** [comment]
Hi @madehmer,
Ideally there would be a better way to do this for our 200 staff to match their timetables, as this would be a great feature to use, we just can't do this on an individual basis.
