### ISSUE TITLE
Invalid github content source reference

### ISSUE THREAD

**Issue by lesterw1** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#178]
The source reference for the [Configure Briefing email](https://docs.microsoft.com/en-us/briefing/be-admin) at [https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Briefing/be-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Briefing/be-admin.md) is invalid. Neither the file nor the directory path exist in the referenced repository. Perhaps it is in a different repo (which one)? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cee44a2-5742-83c0-ee3e-82a3a3f9417e
* Version Independent ID: ad800194-4e32-0529-6844-7529a0d670d7
* Content: [Configure Briefing email - Cortana](https://docs.microsoft.com/en-us/briefing/be-admin)
* Content Source: [Briefing/be-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Briefing/be-admin.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**

**Comment by madehmer** [comment]
@lesterw1 - Apologies for just reading this. What is your question? The live doc is published here: https://docs.microsoft.com/briefing/be-admin
