### ISSUE TITLE
Add feature to disable automatic Do-not-disturb on Focus time

### ISSUE THREAD

**Issue by sergetherriault** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#179]
Add the possibility to disable/enable automatic Do Not Disturb status while on Focus time.

**Comment by paul9955** [comment]
Hi sergetherriault,
You can change some settings for your focus time. Open the MyAnalytics [Focus](https://myanalytics.microsoft.com/?v=focus) page and then select **Plan configuration**. On the **Configurations** page, in the **Plan configuration** area, you can select **Yes** or **No** for **Silence Teams notifications during focus time?** Does this cover what you want to do, or are there sources of notifications other than Teams that you'd like to allow/disallow while in your focus time?
Thank you,
 -- paul9955

**Comment by sergetherriault** [comment]
Hello Paul,

I have none of those options.  What I would like to do is have my status to be “Busy” instead of “Do not disturb” in Teams while I am on focus time which was automatically scheduled.

Here is a screenshot of the configuration available in MyAnalytics.  As you can see, there is almost nothing that is customizable.
[cid:image001.jpg@01D6C4EF.D1A074F0]
Thanks,
Serge


[Logo Desjardins 2018]

Serge Therriault, M. Sc., PSPO, PSM
Analyste d’affaires
Analyse d’affaires, Bancaire
Stratégie, Marketing Mouvement et Services aux particuliers

Montréal

514 281-7000, poste 5554513
1 866 866-7000, poste 5554513
Mobile : 514 242-7128

Faites bonne impression et imprimez seulement au besoin!

Ce courriel est confidentiel, peut être protégé par le secret professionnel et est adressé exclusivement au destinataire. Il est strictement interdit à toute autre personne de diffuser, distribuer ou reproduire ce message. Si vous l'avez reçu par erreur, veuillez immédiatement le détruire et aviser l'expéditeur. Merci.


De : Paul Schafer <notifications@github.com>
Envoyé : 27 novembre 2020 18:01
À : MicrosoftDocs/OfficeDocs-WorkplaceAnalytics <OfficeDocs-WorkplaceAnalytics@noreply.github.com>
Cc : Serge Therriault <serge.c.therriault@desjardins.com>; Author <author@noreply.github.com>
Objet : Re: [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics] Add feature to disable automatic Do-not-disturb on Focus time (#179)


Sécurité –  Ce courriel provient d'un expéditeur externe. Merci d'être vigilant, particulièrement avec les liens et pièces jointes, et de ne jamais donner des informations personnelles.

Warning – This email is from outside Desjardins. Don’t click any links or attachments unless you trust the source. Never share personal information.



Hi sergetherriault,
You can change some settings for your focus time. Open the MyAnalytics Focus<https://myanalytics.microsoft.com/?v=focus> page and then select Plan configuration. On the Configurations page, in the Plan configuration area, you can select Yes or No for Silence Teams notifications during focus time? Does this cover what you want to do, or are there sources of notifications other than Teams that you'd like to allow/disallow while in your focus time?
Thank you,
-- paul9955

**Comment by paul9955** [comment]
Hi Serge,
I've passed your request on to the product team. I'll respond here when I find out more from them. 
Thank you,
 - paul9955

**Comment by paul9955** [comment]
Hello again Serge,
I just heard back from a program manager on the product team. Here's what she said: "Currently, users do not have a way of modifying their Status to Busy during Focusing Time.  This is a request that customers have made and we are looking into how we can incorporate this feedback." 
So, we know that this is on their radar, and you have added weight to this request. If that capability appears, I will update the MyAnalytics documentation with a full description.
Thank you,
 -- paul9955

**Comment by sergetherriault** [comment]
Hello Paul,

Great news.  Thanks for the followup !

Serge


[Logo Desjardins 2018]

Serge Therriault, M. Sc., PSPO, PSM, PMI-ACP
Analyste d’affaires
Analyse d’affaires, Bancaire
Stratégie, Marketing Mouvement et Services aux particuliers

Montréal

514 281-7000, poste 5554513
1 866 866-7000, poste 5554513
Mobile : 514 242-7128

Faites bonne impression et imprimez seulement au besoin!

Ce courriel est confidentiel, peut être protégé par le secret professionnel et est adressé exclusivement au destinataire. Il est strictement interdit à toute autre personne de diffuser, distribuer ou reproduire ce message. Si vous l'avez reçu par erreur, veuillez immédiatement le détruire et aviser l'expéditeur. Merci.


De : Paul Schafer <notifications@github.com>
Envoyé : 1 décembre 2020 19:47
À : MicrosoftDocs/OfficeDocs-WorkplaceAnalytics <OfficeDocs-WorkplaceAnalytics@noreply.github.com>
Cc : Serge Therriault <serge.c.therriault@desjardins.com>; Author <author@noreply.github.com>
Objet : Re: [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics] Add feature to disable automatic Do-not-disturb on Focus time (#179)


Sécurité –  Ce courriel provient d'un expéditeur externe. Merci d'être vigilant, particulièrement avec les liens et pièces jointes, et de ne jamais donner des informations personnelles.

Warning – This email is from outside Desjardins. Don’t click any links or attachments unless you trust the source. Never share personal information.



Hello again Serge,
I just heard back from a program manager on the product team. Here's what she said: "Currently, users do not have a way of modifying their Status to Busy during Focusing Time. This is a request that customers have made and we are looking into how we can incorporate this feedback."
So, we know that this is on their radar, and you have added weight to this request. If that capability appears, I will update the MyAnalytics documentation with a full description.
Thank you,
-- paul9955

**Comment by paul9955** [comment]
You're welcome, Serge!
- Paul
