### ISSUE TITLE
Could be life changing 

### ISSUE THREAD

**Issue by justhearbubbles** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#18]
Should i. . A man with absolutely. 0 computer skills  but the drive to learn. Self teaching on my moble device has been a crazy experience u can only imagine the deep corners of internet and analytics. Page after page. Code after code term after term.. but learning. Not sure how or  why  buts its calling me so be kind be gentle. Plz... lol. 😇

**Comment by justhearbubbles** [comment]
Thank u for your kind and encouraging  words. As a 15 yr military vet I
never sleep so might as well learn to compute  Lol

**Comment by AndreaBarr** [comment]
@justhearbubbles I am going to go a head and close this. If you find an issue with our documents this is the place to let us know so we can fix it. If you are having issues with an application or have found a potential bug in one of our application follow the video below to create a support ticket so we can get it addressed for you. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y
