### ISSUE TITLE
Change Focus Time default availability

### ISSUE THREAD

**Issue by jamieherrera** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#180]
Focus time defaults to find the first available 2 hour free period for every day and assumes a 1 hour lunch from 12-1 local time. Neither default setting is helpful. These defaults should be user-driven. 
1) Focus time should be user-driven and able to customize defaults according to user interest - or habits. My calendar shows that my day may be bookable from 7 to 5, but that is for my colleagues, not or Workplace Analytics. I want to set Focus Time as any afternoon block. Other users may specifically want to schedule for a set 2 hour block every Monday that is different from their Thursday focus time. As it is, at the beginning of the week, I have to look at next week's calendar and move all morning Focus Times to an afternoon space, otherwise it looks like I'm unavailable to colleagues during prime morning meeting time. If Workplace Analytics was set up well enough, it would now be able to suggest afternoon times since I've moved ALL my focus times for the last 90 days. I like the feature, I just don't like that it assumes I want to focus for two hours and receive no alerts at the very beginning of my day. 

2) If I have a lunch time I should be able to a. set it myself, and b. also be able to delete "lunch time" altogether for Workplace Analytics purposes. I don't have a set lunch time every day, but if I did it would be in a different time zone.

**Comment by paul9955** [comment]
Hi Jamie,

Thank you for your interest in focus time and for your well-considered suggestions. I'll pass them on to the product team, but I'd like to point out that you can make at least one of the settings that you're requesting: Open the MyAnalytics [Focus](https://myanalytics.microsoft.com/?v=focus) page and then select **Plan configuration**. In the **Plan configuration** card, you can make several settings, including **When would you prefer to schedule your focus time?**, for which you can select **morning** or **afternoon**. There are no settings for lunch-time preferences, but I'm making sure that the product team knows about this request.  
-- paul9955
