### ISSUE TITLE
Exchange Admin does not have access to the Org Settings

### ISSUE THREAD

**Issue by jadesolis** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#181]
"You must have either an Exchange Administrator or a Global Administrator role to configure users for Briefings."
Exchange Admin roles do not have access to the Org Settings in the old or new (O365) admin center

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cee44a2-5742-83c0-ee3e-82a3a3f9417e
* Version Independent ID: ad800194-4e32-0529-6844-7529a0d670d7
* Content: [Configure Briefing email - Cortana](https://docs.microsoft.com/en-us/Briefing/be-admin)
* Content Source: [Briefing/be-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Briefing/be-admin.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**

**Comment by madehmer** [comment]
@jadesolis - Thank you for your feedback! I'm forwarding it on to the team and will update the documentation accordingly.
