### ISSUE TITLE
If I deactivate MyAnalytics, you'll still read and analyze all my data?

### ISSUE THREAD

**Issue by bitsim-nicke** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#183]
I mean, you may still read, process and analyze all my data even though you don't give my a summary.
Or?

Can I avoid this, someone unknown reading my private stuff?

**Comment by paul9955** [comment]
Hi bitsim-nicke,
I'm checking on this for you and I'll respond here.
Thank you,
 -- paul9955

**Comment by paul9955** [comment]
Hi bitsim-nicke,
I communicated with someone on the product team about this. They responded that no one reads any user's private data. The underlying data used for MyAnalytics is part of the core Office 365 offering. The insights shown in MyAnalytics are computed automatically and will stop (processing of that data stops) when the user opts out.  
Please let me know if you have more questions about this.
 -- paul9955

**Comment by bitsim-nicke** [comment]
Thanks, it looks great. 
But, reading the Privacy guide for MyAnalytics” (https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/overview/privacy-guide)

It says:
	• Microsoft will not mine customer data in Exchange Online for advertising.
	• Microsoft will not voluntarily disclose Exchange Online customer data to law enforcement agencies.

What does the first sentence actually means?
"Microsoft will not mine customer data in Exchange Online for advertising.”
 But then they can use it for other purposes, or?

Why can't they have a clear agreement, like skipping the "for advertising".

**Comment by paul9955** [comment]
Hi bitsim-nicke,
Thank you for the additional feedback. I see your concern about the wording of that sentence and I've passed all of your comments on to the product team. If I get further clarification from them about this (or any other) product behavior, I'll update the documentation to reflect it. I appreciate your interest in the product and your eye for detail. 
 -- Paul

**Comment by bitsim-nicke** [comment]
This is a good initiative!
https://www.trustedreviews.com/news/apple-adds-privacy-labels-to-app-store-listings-and-you-wont-like-what-you-see-4114408

Från: Paul Schafer <notifications@github.com>
Skickat: den 14 december 2020 22:28
Till: MicrosoftDocs/OfficeDocs-WorkplaceAnalytics <OfficeDocs-WorkplaceAnalytics@noreply.github.com>
Kopia: Niclas Jansson <niclas.jansson@bitsim.com>; Author <author@noreply.github.com>
Ämne: Re: [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics] If I deactivate MyAnalytics, you'll still read and analyze all my data? (#183)


Hi bitsim-nicke,
Thank you for the additional feedback. I see your concern about the wording of that sentence and I've passed all of your comments on to the product team. If I get further clarification from them about this (or any other) product behavior, I'll update the documentation to reflect it. I appreciate your interest in the product and your eye for detail.
-- Paul

**Comment by paul9955** [comment]
Thanks again, bitsim-nicke! 
I sent this link on to the product team. 
 -- Paul
