### ISSUE TITLE
Insights Hiding Emails from Inbox

### ISSUE THREAD

**Issue by aaciil** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#184]
Hello. I haven't changed any settings and lately Insights is deciding which emails to put in Insights as "Unread Important Emails" but I can't see them in my inbox or move them out of Insights.  I can see that I have unread messages because my inbox lists the number of unread messages, but after some hunting, realized they were in Insights. There isn't a way to turn off or disable this function that I can see. 

This is causing problems for me and others on my team.

**Comment by paul9955** [comment]
HI aaciil,
Let me be sure I understand the problem. In the navigation pane, **Inbox** shows one or more unread messages, but in the main pane, no unread messages are appearing? And, when you open the **Insights** pane, the card for "Unread important email" shows a number of messages that matches the number shown for your **Inbox**? Is that correct? 
In other words, it's acting as if those unread messages are visible only to the **Insights** feature; they are not appearing in your general email pane?
Thank you,
 -- paul9955

**Comment by aaciil** [comment]
Hi Paul -

Yes that’s exactly it. 

Thanks

Alicia

**Comment by paul9955** [comment]
Hi Alicia,

I contacted someone on the product team about this. He recommended that you describe this odd behavior directly in the Feedback pane in Insights. Here are the steps to do that:
1. Open the Insights add-in in Outlook. 
2. In the upper-right corner, click the feedback (smiley-face) icon. 
3. Click **I don't like something**.
4. Under **Have more to say?** describe this problem as you've described it to me. Feel free to copy and paste the following paragraph. (This is the summary of your problem that I sent to my contact on the product team.) Edit or add to it, of course, if you'd like.

     In the navigation pane, **Inbox** shows one or more unread messages, but in the main pane, no unread messages are appearing. When I open the Insights pane, the card for "Unread important email" shows a number of messages that matches the number shown for my Inbox. It’s acting as if these unread messages are visible only to the Insights feature; they are not appearing in the general email pane. This is causing problems for me and others on my team.

5. Click **Allow Microsoft to contact me about feedback**.
6. Click **Submit**. 

Best of luck with this, Alicia, 
-- Paul

**Comment by aaciil** [comment]
Thank you!

I've done that now and also had a chat with Microsoft today and this was
their "fix"....

Here are the instructions to the repair of your Office application :)
https://support.microsoft.com/en-us/office/repair-an-office-application-7821d4b6-7c1d-4205-aa0e-a6b40c5bb88b

I appreciate your help!
-Alicia

**Comment by paul9955** [comment]
You're welcome! 
 -- Paul
