### ISSUE TITLE
Focus plan configuration availability

### ISSUE THREAD

**Issue by mheptinstall** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#186]
None of the plan configuration options shown in the documentation are available when I go to plan configuration.

The article does not mention when these features might be available:

![image](https://user-images.githubusercontent.com/10913145/103620008-a62b2c00-4f2a-11eb-87b2-c757825b00a2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40f032f9-30a5-b801-b3c2-602a6ef552d3
* Version Independent ID: bffa68c6-76a6-3de4-ec42-ab75c6a264d2
* Content: [Focus plan - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/focus-plan?source=docs)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/focus-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/focus-plan.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-pausch**

**Comment by paul9955** [comment]
Hi mheptinstall,
Sorry about this late response. 
I have a question about what you do see. Let's say you start at the MyAnalytics dashboard and then select **Focus**.
On the **Focus** page, select **Plan configuration**. 
What options do you see on that page? 
Thank you,
 -- paul9955

**Comment by paul9955** [comment]
Hi again mheptinstall,
I'm closing this issue till I hear back from you. (I had a question in my response from earlier in January.) 
Feel free to re-open if you'd like to pursue this. 
Thank you,
 -- paul9955

**Comment by mheptinstall** [comment]
@paul9955 the options I see on Plan Configuration are the same as those in the original screenshot:

![image](https://user-images.githubusercontent.com/10913145/106106362-5280bc80-613d-11eb-9584-77f9cd2a1ff9.png)

I don't see options like this:

![image](https://docs.microsoft.com/en-us/workplace-analytics/images/mya/use/plan-config-pane.png)

**Comment by huntermaxfield** [comment]
I'm seeing this same issue and woulld love to change the amount of focus time booked each day.

**Comment by paul9955** [comment]
Hello mheptinstall, huntermaxfield, and beychok-j,
Thank you for your interest in this feature and these config options and I'm sorry that they haven't shown up for you. The page with the expanded set of options is currently rolling out worldwide but it hasn't reached all users. Unfortunately, I do not know the ETA for general availability. 
 -- paul9955

**Comment by paul9955** [comment]
Hello,
The product team has informed me that the rollout of this new design has been continuing to users worldwide. Have you noticed that the new **Plan configuration** options are available to you now? 
Thank you,
 -- paul9955

**Comment by mheptinstall** [comment]
> Hello mheptinstall and huntermaxfield,
> Thank you for your interest in this feature and these config options and I'm sorry that they haven't shown up for you. The page with the expanded set of options is currently rolling out worldwide but it hasn't reached all users. Unfortunately, I do not know the ETA for general availability.
> -- paul9955

Yes, those options are now available.
