### ISSUE TITLE
Customize category used for Focus time

### ISSUE THREAD

**Issue by carlo-quinonez** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#187]
Right now, focus time shows up as the same default category used for all my other meetings. Is there any way to customize my Focus plan to set what category (ie. color) to use when it schedules time?

**Comment by madehmer** [comment]
@carlo-quinonez - Thanks for your feedback! This is definitely on the team's list to consider for a future release. In the meantime, which you probably already know about, you can use [Outlook's color features to set the meeting color](https://support.microsoft.com/office/assign-a-color-category-to-a-calendar-appointment-meeting-or-event-750596d9-707d-4412-8c0e-7fdc0fc52527). Another alternative is to use [Microsoft Briefing](https://docs.microsoft.com/Briefing/be-overview), which sets different activities as different colors for the upcoming week with the [Plan your week feature](https://docs.microsoft.com/briefing/be-time).  Here's an example of how it automatically filled in open times in my schedule next week:
![plan-your-week](https://user-images.githubusercontent.com/39922363/104059812-c49f5a80-51aa-11eb-82bb-99b10bc84181.png)
