### ISSUE TITLE
Potentially contradictory Analyst access for Plans

### ISSUE THREAD

**Issue by m-m-powers** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#188]
I’ve got a hopefully easy question about the way Analyst permission are explained, especially regarding Plans. 

My understanding is that as an Analyst role, I can look at the Plans Analysis page to see the analysis of behaviors, but I can’t actually launch a plan. But when I go into the MS tenant and look at some of the Plans blades, it looks like I can submit a Plan.

Here in the documentation, I see a few potential contradictions in what Analysts get for Plans permissions

**1.	Role Description**
![image](https://user-images.githubusercontent.com/63008952/104251810-6500b380-5425-11eb-922e-a1de0fc8bfcb.png)
 
Does “full access” include the ability to launch Plans?

**2.	User Access chart**
 
> Create plans that help participants improve workplace behaviors
![image](https://user-images.githubusercontent.com/63008952/104251796-5fa36900-5425-11eb-9b0d-0b532a8abe1a.png)

Analysts appear to have access to Plans, with only the People Manager being limited in scope

**3.	Function Performed**
![image](https://user-images.githubusercontent.com/63008952/104251823-6b8f2b00-5425-11eb-840e-2146c9e89a3e.png)

Here, Analysts are not listed as being able to set up and manage change plans. 

Would it be possible to review and update the documentation for the current Plans functionality for the Analyst role so it's more clear on what the Analyst can and cannot do with regards to Plans?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d80edf7d-e15e-15fe-f2f7-ec92690e3832
* Version Independent ID: 9ea8d852-234a-62db-ae36-6e21a99d2344
* Content: [User roles in Workplace Analytics - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/use/user-roles)
* Content Source: [WorkplaceAnalytics/Use/User-Roles.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Use/User-Roles.md)
* Product: **wpa**
* GitHub Login: @madehmer
* Microsoft Alias: **v-pausch**

**Comment by paul9955** [comment]
Hi m-m-powers, 
You're absolutely right. Analysts can also create plans, and the docs did not reflect this correctly. This wasn't always an option for analysts, but it is now. I'm in the process of updating the documentation and I'll post a link here once that's done.
Thank you!
-- paul9955, Workplace Analytics documentation

**Comment by madehmer** [comment]
The docs have been updated accordingly. Thanks Paul for updating the dos and m-m-powers for your feedback. Closing this since the issue has been resolved.
