### ISSUE TITLE
Time allocation description

### ISSUE THREAD

**Issue by moralec** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#189]
The p2g  and g2g queries include a time allocation description that is the same (copy + paste) but in practice they work differently.  I believe the current version is correct for g2g but not for Pg2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7760a3c-9e8b-a188-be6f-eae95d924dd5
* Version Independent ID: 8f0738a0-14b9-a5e7-c968-eed4bfa92ff8
* Content: [Person-to-group queries in Workplace Analytics - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/tutorials/person-to-group-queries)
* Content Source: [WorkplaceAnalytics/Tutorials/Person-to-group-queries.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Tutorials/Person-to-group-queries.md)
* Product: **wpa**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**

**Comment by madehmer** [comment]
@moralec  - Excellent point. Thanks for your feedback. I'm updating the docs now accordingly.
