### ISSUE TITLE
Contradiction about privacy keyword exclusions 

### ISSUE THREAD

**Issue by juchacz** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#19]
On this page https://docs.microsoft.com/en-us/workplace-analytics/privacy/privacy-considerations we say the logic "Does not match multiple word terms, so you need to list each keyword as a separate term". However, on this page https://docs.microsoft.com/en-us/workplace-analytics/setup/set-up-workplace-analytics#step-4-configure-workplace-analytics-settings we say, "Terms can be any combination of letters, numbers and special characters, e.g. client attorney privilege; D&I". 

Which one is right? The second example suggests that it does accept and correctly apply multiple word strings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a311b001-b100-2cc5-2651-9324178605d7
* Version Independent ID: a687cfbe-9693-d0ae-1207-4a23ff7e26cf
* Content: [Workplace Analytics Setup Checklist - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/workplace-analytics/setup/set-up-workplace-analytics#step-4-configure-workplace-analytics-settings)
* Content Source: [WorkplaceAnalytics/Setup/Set-up-Workplace-Analytics.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Setup/Set-up-Workplace-Analytics.md)
* Product: **wpa**
* GitHub Login: @madehmer
* Microsoft Alias: **paul9955**

**Comment by madehmer** [comment]
@juchacz, According to the dev team "Privacy exclusions perform an exact string match for subject keywords," so I updated the logic for Privacy considerations accordingly. Thank you for your feedback!
