### ISSUE TITLE
98% of 25 (24.5 out of 25 people) should be 96% (24 out of 25 people)

### ISSUE THREAD

**Issue by Adampudsy** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#190]
You cannot have 98% of 25 recipients opening an email, it would have to be 96%. 98% would be 24.5 people opening the email.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bbb07c4-2770-4b71-f563-e8f9f5d3c157
* Version Independent ID: 9801de76-e9c2-9308-7a41-d517172c3e46
* Content: [Use Insights - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/use-the-insights#open-rate)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/use-the-insights.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/use-the-insights.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-pausch**

**Comment by paul9955** [comment]
Hi Adampudsy,
Thank you for noticing this and calling it to our attention!
It's now fixed. You can check it out in [Use the Insights / Open rate](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/use-the-insights#open-rate).
 -- paul9955
