### ISSUE TITLE
this question seems poorly worded- What happens with users who were not assigned a Workplace Analytics license? Are they ignored?  A7. No, they are not ignored. Employees in your organization who are not licensed for analysis but might collaborate with your measured employees (internal collaborators) through meetings, email, unscheduled calls, or instant messages. These employees are not measured and their data is not processed.

### ISSUE THREAD

**Issue by sawyerkelly** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#191]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11317be7-5ea8-ce6a-99bf-0a16f91de217
* Version Independent ID: c59ce92f-5eb7-957b-0d26-db5f33bd11d2
* Content: [Workplace Analytics insights for managers - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/use/pm-home)
* Content Source: [WorkplaceAnalytics/Use/pm-home.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Use/pm-home.md)
* Product: **wpa**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**

**Comment by madehmer** [comment]
@sawyerkelly  - I agree. I'll upate it accordingly. Thanks!

**Comment by sawyerkelly** [comment]
Thanks Michele!!

**Comment by sawyerkelly** [comment]
And the new response makes sense 😊

From: Sawyer Kelly <Sawyer.Kelly@microsoft.com>
Sent: Wednesday, January 27, 2021 8:59 AM
To: MicrosoftDocs/OfficeDocs-WorkplaceAnalytics <reply@reply.github.com>; MicrosoftDocs/OfficeDocs-WorkplaceAnalytics <OfficeDocs-WorkplaceAnalytics@noreply.github.com>
Cc: sawyerkelly <sawyerkelly@wustl.edu>; Mention <mention@noreply.github.com>
Subject: RE: [EXTERNAL] Re: [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics] this question seems poorly worded- What happens with users who were not assigned a Workplace Analytics license? Are they ignored? A7. No, they are not ignored. Employees in your organizatio

Thanks Michele!!
