### ISSUE TITLE
LicenseSku parameter is missing in running script example.

### ISSUE THREAD

**Issue by taisino** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#192]
In the example of running Add-WpALicense.ps1, LicenseSku parameter is missing as below.

----------
Start Windows PowerShell and run the following command:

 C:\Scripts\Add-WpALicense.ps1 -CSV <CSVLocation>
----------

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efd0452b-0749-f944-84eb-1ffafb152528
* Version Independent ID: 0a88d1d5-18fd-4e3d-dba5-0d0db39eebe2
* Content: [Assigning Workplace Analytics licenses with PowerShell - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/use/assigning-licenses-with-powershell#script-execution)
* Content Source: [WorkplaceAnalytics/Use/Assigning-licenses-with-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Use/Assigning-licenses-with-powershell.md)
* Product: **wpa**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**

**Comment by madehmer** [comment]
@taisino - Again, thank you so much for your great feedback. The docs have been updated accordingly!
