### ISSUE TITLE
Green Category is gray

### ISSUE THREAD

**Issue by Floriszz** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#193]
The default category that is applied to Focus Time calendar events is called 'Green Category', which has the color Gray.
It is possible to change the color manually. 
But once you change the name to a more valuable name like 'Focus Time', Outlook just generates a new category with that name and color and leaves the original as something '...not in the master list..'

It would be nice to set the color of the automatically applied category and the name to a more meaning full name, like; 'Focus Time'.
Also it would be nice to be able to set the 'status' of the Focus Time calendar items to 'Free' or 'Tentative' instead of 'Busy'. The reason for this is that the 'Busy' status has the effect that Microsoft Teams does not allow people to call you.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40f032f9-30a5-b801-b3c2-602a6ef552d3
* Version Independent ID: bffa68c6-76a6-3de4-ec42-ab75c6a264d2
* Content: [Focus plan - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/focus-plan#to-leave-or-change-your-focus-plan)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/focus-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/focus-plan.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-pausch**

**Comment by paul9955** [comment]
Hi Floris,
Thank you for your comment. These are all good points you make about configuring Focus time functionality. I contacted the product team and forwarded your message, and I've heard back. First, they called out your requests:

1. Manually change the color of a category without creating a new category.
2. Manually set the category name (to something like "focus time").
3. Manually set the status of focus time to a status other than "Busy." 

To address your third request, they mentioned that the status of focus time can be either 'Focusing' or 'Busy', based on whether or not you've chosen to mute notifications. More importantly, they also said that all of these points are known issues and are being considered for inclusion in a future version of this feature. Unfortunately, I have no ETA for the arrival of any product enhancements, but these requests are definitely on their radar.
Thank you,
 - paul9955
