### ISSUE TITLE
myAnalytics link doesn't work

### ISSUE THREAD

**Issue by mugwhumps** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#194]
The link to see more about myAnalytics redirects to a page with a sad upside down ice cream cone. This is second week in a row that the link is broken. I am signed into portal office and using the link.

**Comment by paul9955** [comment]
Hi mugwhumps,
I'm sorry to hear this. Could you please indicate which area or page of MyAnalytics you're seeing that contains this broken link?
Thank you! 
- Paul

**Comment by mugwhumps** [comment]
Hello,
Any of the pages. Clicking on the “learn more” button or any link in the myAnalytics weekly email leads me to a broken page.
Thanks!

Maggie Kennedy MN, RN
Coordonnatrice des politiques et procédures organisationnelles et des ensemble d’ordonnances, Soins continus Bruyère
Coordinator of corporate policies, procedures and order sets, Bruyère Continuing Care
613-562-6262, poste/ext. 1018 (temporarily off-site; please leave voicemail)

**Comment by paul9955** [comment]
Hi Maggie,
Thank you for the additional info. I've contacted the product team about this. 
I'll reply here with any info, advice, or questions that I get from them.  
 -- Paul

**Comment by paul9955** [comment]
Hi Maggie,

The team needs to find out more details about the problem that you're experiencing. Could you please do the following?

1.	Open [Workplace Analytics](https://workplaceanalytics.office.com).   
2.	In the upper right, select the **Feedback** option (the smiley face):
 
![image](https://user-images.githubusercontent.com/35980943/106999587-53b47980-673b-11eb-92eb-f917b933112d.png)

3.	In the options that appear, select the appropriate choice:
 
![image](https://user-images.githubusercontent.com/35980943/106999609-5e6f0e80-673b-11eb-94d6-076717a25820.png)

4.	In the dialog box that appears (pictured here is the one for **File a bug**), describe the issue, select the **You can contact me** checkbox, type your email address, and (optionally) include a screenshot. If there's an error code that accompanies the ice-cream-cone, that would be especially helpful to include.  
 , 
![image](https://user-images.githubusercontent.com/35980943/106999627-64fd8600-673b-11eb-9c37-1ace4504ab98.png)

Thank you,
 --  Paul

**Comment by mugwhumps** [comment]
Hello Paul, the link you provided is not working. I’ve reached out to our HelpDesk for more info and will try again later.
thanks

Maggie Kennedy MN, RN
Coordonnatrice des politiques et procédures organisationnelles et des ensemble d’ordonnances, Soins continus Bruyère
Coordinator of corporate policies, procedures and order sets, Bruyère Continuing Care
613-562-6262, poste/ext. 1018 (temporarily off-site; please leave voicemail)

**Comment by paul9955** [comment]
Hi Maggie,

I'm sorry. Yes -- that was an incorrect link that I gave you. Please try this: 

1.	Open the MyAnalytics dashboard at https://myanalytics.microsoft.com/.
2.	In the lower left, select the **Feedback** option:
 
![image](https://user-images.githubusercontent.com/35980943/107064712-b4ba6c80-6790-11eb-9037-fb520bea8ed7.png)

3.	In the **Feedback** dialog box, under **Have more to say?**, describe the problem.
4.	Select Submit. 

Thank you and please let me know whether this works for you, 
 -- Paul

**Comment by mugwhumps** [comment]
Hello Paul,
That link actually worked fine. Could it be that the wrong link is appended in the weekly email?

Maggie Kennedy MN, RN
Coordonnatrice des politiques et procédures organisationnelles et des ensemble d’ordonnances, Soins continus Bruyère
Coordinator of corporate policies, procedures and order sets, Bruyère Continuing Care
613-562-6262, poste/ext. 1018 (temporarily off-site; please leave voicemail)

**Comment by paul9955** [comment]
Hello Maggie, 
I really couldn't speculate on that, but the people I've been communicating with on the product/development team have access to the code and will know more. If you haven't already, please fill out and submit the feedback form. This will give them a work item with details to pursue. 
I hope this gets resolved quickly for you,
-- Paul
