### ISSUE TITLE
Need some update to complete Add-WpALicense.ps1

### ISSUE THREAD

**Issue by taisino** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#196]
Add-WpALicense.ps1 has some problematic code and the script always fails to run.

Problem1
On line 26, $LicenseSKU is declared as string, but Get-WorkplaceAnalyticsSku function returns Microsoft.Online.Administration.Account SkuDetails type of object.
This type mismatch causes the unexpected substitution to $LicenseSKU on line 120.
`$LicenseSku = Get-WorkplaceAnalyticsSku -searchString $wpaSearch`

And variables comparison on line 141 is always failed.
`if ($msolUser.Licenses.AccountSkuId -contains $WpaLicenseSku.AccountSkuId) {`

Solution is declaring new variable that isn't string type, and replace $LicenseSKU to new variable after the line 120.

Problem2
On line 153, $msolUser.UserPrincpalName isn't right property.
Should replace to $msolUser.UserPrincipalName. ("i" is missing)

The sample code I modified is attached.

[Add-WpALicense-Update.txt](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/files/5929664/Add-WpALicense-Update.txt)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efd0452b-0749-f944-84eb-1ffafb152528
* Version Independent ID: 0a88d1d5-18fd-4e3d-dba5-0d0db39eebe2
* Content: [Assigning Workplace Analytics licenses with PowerShell - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/use/assigning-licenses-with-powershell)
* Content Source: [WorkplaceAnalytics/Use/Assigning-licenses-with-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Use/Assigning-licenses-with-powershell.md)
* Product: **wpa**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**

**Comment by madehmer** [comment]
@taisino - Thank you for your great feedback. The docs have been updated accordingly!
