### ISSUE TITLE
Focus Plan Configuration

### ISSUE THREAD

**Issue by beychok-j** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#197]
This is a duplicate issue of #186 that got closed. 

The configuration options are not available to me, nor the others who commented on the previous issue. It seems that this is what we see.

![image](https://user-images.githubusercontent.com/60521876/107400189-92498b80-6acf-11eb-949f-95816130204d.png)

**Comment by paul9955** [comment]
Hello beychok-j,
Thank you for your interest in this feature and these config options and I'm sorry that they haven't shown up for you. The page with the expanded set of options is currently rolling out worldwide but it hasn't reached all users. Unfortunately, I do not know the ETA for general availability.
-- paul9955

**Comment by beychok-j** [comment]
Thanks Paul!
