### ISSUE TITLE
Focus Plan to support "Tentative" bookings for focus time

### ISSUE THREAD

**Issue by fishzle** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#200]
I have me-work time - which is the traditional definition of focus time.
I also have meeting-time - which is senior people that "require" me to attend something. (anyime of the day lol)

But I also want to have something in between that allows me to indicate when people _can_ book me for "meeting-time". Sort of like how doctors-clinic have hours that people can walk in.
If the focus-plan allowed a "tentative" booking setting, then I could have a daily 2h window where people could "walk in" to talk to me.

I think it would mean having 2 focus plans. I'd have the standard/existing focus-plan as the higher priority, then have this to mark out the "walk-in" time.

It wasn't an issue when I was in-the-office, but now that we're remote, everyone is missing the "Watercooler time"

**Comment by fishzle** [comment]
I think I've raised this in the wrong place 🤣. I'm sure there's a uservoice that would be a better match. Oops.

**Comment by paul9955** [comment]
Hi Francis,
No, this was a good place to raise it. In fact, shortly after you posted it, I sent it on to the product team and I've already received a response from them. Here's what they said:

> "This is a good customer ask that we can consider as we continue to explore different time categories. We will keep this feedback in mind as we work to improve employee experiences."

So, I thank you for your interest in this feature and your willingness to express this thoughtful request to us. 
I'm going to close the issue now, but feel free to re-open it if you have further details you'd like to share. 
 -- paul9955, MyAnalytics documentation

**Comment by CGossec** [comment]
Hello,
Just hijacking this thread to similarly mention interest in this possibility!
With two more years, has there been any progress made in that direction?

**Comment by mayanand** [comment]
@paul9955 any updates on this request?

**Comment by mgaryGCM** [comment]
@paul9955 Can this request be re-opened or is there a roadmap item we can track related to this?
