### ISSUE TITLE
Missing Book time to focus and Catch up on email sections.

### ISSUE THREAD

**Issue by ajkirchhoff** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#201]
You have links to features at the top of the page that do not exist as content in the page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bbb07c4-2770-4b71-f563-e8f9f5d3c157
* Version Independent ID: 9801de76-e9c2-9308-7a41-d517172c3e46
* Content: [Use Insights - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/use-the-insights)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/use-the-insights.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/use-the-insights.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **v-pausch**

**Comment by madehmer** [comment]
@ajkirchhoff  - It's all fixed. Thanks for your feedback!
