### ISSUE TITLE
Internet Explorer Dependancy

### ISSUE THREAD

**Issue by RichardMorris-Ideagen** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#202]
Hello,

I know that this has been looked at before in https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/issues/60 and https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/issues/74. I've looked at the replies and also at https://docs.microsoft.com/en-gb/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins referenced in https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/issues/74.

I'm still seeing the message -

ADD-IN ERROR

Sorry, we couldn't load the add-in because Internet Explorer is disabled. 

I'm using:
OS - 10.0.19042.804
Office - 13801.20274
Microsoft Edge WebView2 Runtime - 89.0.774.45
Edge - 89.0.774.45 

Which looks like it meets the requirements for Office Add-ins to use WebView2.

**Comment by madehmer** [comment]
@RichardMorris-Ideagen - Thank you for reaching out about this issue. I'm asking the team about this issue, so I can update our documentation accordingly. However, if you think this is a bug and you want an answer or access faster, please ask your Microsoft admin for help. Or if you are a Microsoft 365 admin, you can [ask for help](https://docs.microsoft.com/microsoft-365/admin/contact-support-for-business-products) with this in the Microsoft 365 admin center.

**Comment by madehmer** [comment]
@RichardMorris-Ideagen - Please report your issue through the admin center if you still can't access MyAnalytics through Microsoft Edge. Thanks again for your feedback.
