### ISSUE TITLE
cannot give comments "critical resource missing"

### ISSUE THREAD

**Issue by Efsee21** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#204]
[Enter feedback here]
on page https://docs.microsoft.com/en-us/briefing/be-overview , click on "this product" button at the bottom of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0a83186-6909-edb8-7de3-7a5c9307a0a1
* Version Independent ID: 9ba1d4d8-60ba-1c4d-f7e8-e9a92e74727d
* Content: [Briefing email overview - Cortana](https://docs.microsoft.com/en-us/briefing/be-overview)
* Content Source: [Briefing/be-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Briefing/be-overview.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**

**Comment by madehmer** [comment]
@Efsee21 - Hi, I tried each way of providing feedback and was able to submit it for both product and the doc from that page. Please try again and see if it works this time. If you still can't, please give me more details about your experience, what you're selecting, and a screenshot if you can, so I can provide them to the team to triage it on our end. Thanks for your time and feedback!

**Comment by Efsee21** [comment]
Good morning 

I tried again: only Firefox has that "critical resource missing", but after a rather long wait it behaves the same as Edge and Chrome: the button at the bottom of page [ https://docs.microsoft.com/en-us/briefing/be-overview | https://docs.microsoft.com/en-us/briefing/be-overview ] under the header "Feedback" and labelled "this product" does not go to some feedback page, but just to the settings page of Cortana Briefing. 

So the first error does not exist (or disappears), but the other button is not doing what it's labelled for. 

(and so I still cannot give my feedback on the product itself...) 

With best regards 

Frank Clarijs 
Hazelaarstraat 21 
2800 Mechelen, Belgium 
frank.clarijs@telenet.be 
Tel +32 15 21 84 95 


Van: "Michele Dehmer" <notifications@github.com> 
Aan: "MicrosoftDocs/OfficeDocs-WorkplaceAnalytics" <OfficeDocs-WorkplaceAnalytics@noreply.github.com> 
Cc: "Frank Clarijs" <frank.clarijs@telenet.be>, "Mention" <mention@noreply.github.com> 
Verzonden: Woensdag 10 maart 2021 19:21:03 
Onderwerp: Re: [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics] cannot give comments "critical resource missing" (#204) 





[ https://github.com/Efsee21 | @Efsee21 ] - Hi, I tried each way of providing feedback and was able to submit it for both product and the doc from that page. Please try again and see if it works this time. If you still can't, please give me more details about your experience, what you're selecting, and a screenshot if you can, so I can provide them to the team to triage it on our end. Thanks for your time and feedback!

**Comment by madehmer** [comment]
Hi Frank, I'll reply via email to carry this forward. Also, I removed your personal information here because this is a public site. Thanks again for reaching out!
