### ISSUE TITLE
Need to add Delay Deliver to bullets

### ISSUE THREAD

**Issue by karleesm** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#208]
Suggestion to add a bullet for Delay Delivery on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb01b39d-e42c-ddb0-442f-b4f840921f84
* Version Independent ID: a3a290d6-176c-a0af-5aa8-141c1cdb7508
* Content: [MyAnalytics key user interface elements - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/mya-elements)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/MyA-elements.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/MyA-elements.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **v-pausch**

**Comment by madehmer** [comment]
@karleesm - Thanks for your feedback. Delay delivery is only one of a few types of inline suggestions that are all listed in [Types of inline suggestions](https://docs.microsoft.com/workplace-analytics/myanalytics/use/mya-notifications#types-of-inline-suggestions). We'll look at maybe linking to the types in "MyAnalytics elements."
