### ISSUE TITLE
Where does Delay Delivery get it settings from for 'Consider sending this email on ' when typing email to team member

### ISSUE THREAD

**Issue by DavidTaig** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#209]
When typing up an email after hours, I don't always get the option to 'Consider sending this email on '

What settings in this coming from: https://myanalytics.microsoft.com/?v=settings or https://outlook.office365.com/mail/options/calendar/view

Can I get a report of all Team members who don't have this setting configured?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46f983da-af4c-d975-445b-77fb8f307848
* Version Independent ID: 0cf725f8-0abf-465e-b031-396344f54cb1
* Content: [Delay delivery in MyAnalytics - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/delay-delivery#opt-in-with-myanalytics)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/delay-delivery.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/delay-delivery.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**

**Comment by paul9955** [comment]
Hi DavidTaig,

I contacted the product team and learned a few things that might answer your questions.

- The user's settings on the MyAnalytics Dashboard configuration page will sync with the user's settings in Outlook.
- The default condition is that you can see a maximum of **two** Delay delivery suggestions per day (as described in [Delay delivery](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/delay-delivery)). 
- You can surpass the limit of two per day if you take the extra step of opting in to the Delay delivery service (as described in [Opt in with MyAnalytics](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/delay-delivery#opt-in-with-myanalytics)). 
- As for team members' settings, for privacy reasons, those settings cannot be divulged to others. 

Let me know if this didn't answer your questions or if you have any other questions or issues,
Thank you,
-- paul9955

**Comment by paul9955** [comment]
Hi DavidTaig,

I hope this suggestion (opting in to the Delay delivery service) worked for you -- or will work for you if you haven't tried it yet. I'll close this issue for now; feel free, of course, to re-open it if you're still having troubles with this feature. 

Thank you,
 -- paul9955
