### ISSUE TITLE
no way to manage cortana briefing emails using rules

### ISSUE THREAD

**Issue by mesdjian** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#210]
Please provide steps to manage these emails via OWA rules.

Since there is no header information within these emails, what rule configuration is needed to manage these emails via a rule created in Outlook on the web?

My interest is to move/categorize these emails.

Thanks, Ara

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0a83186-6909-edb8-7de3-7a5c9307a0a1
* Version Independent ID: 9ba1d4d8-60ba-1c4d-f7e8-e9a92e74727d
* Content: [Briefing email overview - Cortana](https://docs.microsoft.com/en-us/briefing/be-overview)
* Content Source: [Briefing/be-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Briefing/be-overview.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**

**Comment by madehmer** [comment]
@mesdjian - Thanks for asking. To use the Outlook Web app to set rules for the Briefing emails, see [Use inbox rules in Outlook on the web](https://support.microsoft.com/office/use-inbox-rules-in-outlook-on-the-web-8400435c-f14e-4272-9004-1548bb1848f2).

**Comment by mesdjian** [comment]
I know how to create inbox rules in OWA - what I need assistance with is troubleshooting why inbox rules for the Cortana Briefing emails do not work.

Ara

**Comment by madehmer** [comment]
Ah, ok. Please complete the feedback form and give them permission and your contact info for follow up help: [https://cortana.office.com/briefing?v=feedback](https://cortana.office.com/briefing?v=feedback).

**Comment by StAmourD** [comment]
I have similar feedback. 

I would like to "Always Move to Other". Right clicking this email and choosing this option only works momentarily. The Cortana email moves to the "Other" inbox section until it is read, then it moves itself back to "Focused" inbox.
