### ISSUE TITLE
Remove Insights icon from Outlook taskbar

### ISSUE THREAD

**Issue by WinArchitect** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#211]
I have disabled Insights following the instructions provided in Docs but icon remains in the toolbar. In fact, if I click the icon it shows me a pane that says "Turn on Insights". I have several M365 accounts and so I end up with several icons showing up which wastes precious space on my toolbar. How do I permanently remove these icons? There is no option for this that I can see anywhere. If there is no way at this time, this needs to be built!

**Comment by paul9955** [comment]
Hello WinArchitect,
I'm sorry that is happening and I'm happy to look into it for you. First, I'd like to verify one thing: In the MyAnalytics documentation, did you use the steps in the procedure [If you have multiple accounts](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/opt-out-of-mya#if-you-have-multiple-accounts)? If so and if you are still seeing this problem, let me know and I'll pursue the issue further for you.
Thank you! 
 -- paul9955

**Comment by WinArchitect** [comment]
Yes, all accounts are set for Opt-Out

Chaz Spahn
(425) 757-4079 | Cell
***@***.***D724A1.D0926A70]

**Comment by paul9955** [comment]
Thank you Chaz,
I've asked the product team about this and I'll let you know what I find out. 
 -- paul9955

**Comment by paul9955** [comment]
Chaz, I appreciate your asking about this! 
You found a gap in our documentation. 
I've now added the procedure to [remove the Insights icon](https://docs.microsoft.com/workplace-analytics/myanalytics/use/add-in#to-remove-the-insights-icon) after you opt out of the Insights feature. 
Thank you much,
 -- paul9955

**Comment by WinArchitect** [comment]
Paul,

You were my hero for a couple of days. I followed the instructions and removed the Add-In from My Add-Ins and indeed they all went away. But they came back a day or two later. I have had to go remove it two more times since Monday.

I have confirmed, yet again, that all accounts are set for Opt-Out in the dashboard.

Any more ideas?

**Comment by paul9955** [comment]
Hi Chaz,

Oh, man, I'm sorry to hear that. Let me contact the product team again. There might be another setting somewhere, or maybe it's a bug. In any case, I'll let you know. Watch this space. 

- Paul
