### ISSUE TITLE
Add network queries to the documentation

### ISSUE THREAD

**Issue by siliebal** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#212]
Hi WpA team, 
great documentation, really helping with clarifying the differences of the queries. 
I've noticed that the 2 new network queries (Network: p2p and Network: person) are not listed here yet. 

I'm not sure if those are GA for all our customers yet, however I've seen them at most of the customers I've been engaged with. Therefore, it would be great if we could add these to our documentation. 

Cheers, 
Simone
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1907bce9-501b-360b-e1ba-40b014bdd8f8
* Version Independent ID: 600f91b0-22f7-c2d5-b243-d4100d0d5342
* Content: [Workplace Analytics query overview - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/tutorials/query-basics)
* Content Source: [WorkplaceAnalytics/Tutorials/Query-basics.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Tutorials/Query-basics.md)
* Product: **wpa**
* GitHub Login: @paul9955
* Microsoft Alias: **v-mideh**

**Comment by madehmer** [comment]
@siliebal - Thanks for asking. Good point, those need to be added to that overview topic. They are documented: [Organizational network analysis (ONA) person queries](https://docs.microsoft.com/workplace-analytics/tutorials/ona-person-query) and [ONA person-to-person queries](https://docs.microsoft.com/workplace-analytics/tutorials/ona-person-to-person-query).
