### ISSUE TITLE
MyAnalytics shows incorrect time zone

### ISSUE THREAD

**Issue by wibek** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#213]
MyAnalytics shows timezone UTC-08:00. When I try to change this it opens Calendar. The timezone there is UTC+01:00, which is good. 

Because of this, Focus time is planned in the evening.

**Comment by paul9955** [comment]
Hello Wim,
I'm sorry that's happening. Let me verify what you're seeing happen. 
On the MyAnalytics dashboard, you select **Config Settings** and this opens the **Configurations** page. There, under **Time zone(s)**, you select **Change time zone** and this opens your Outlook calendar settings at outlook.office.com. On that page, you see **Current time zone** set to UTC-08:00, Pacific Time. You reset it to UTC +01:00, Amsterdam, but this setting doesn't stick? That is, if you leave and come back, your time-zone setting has returned to UTC -08:00?
(And consequently, your focus time blocks are being scheduled for the morning of UTC -8, not the morning of UTC +1.)
Thank you,
-- Paul

**Comment by wibek** [comment]
Hi Paul,
Almost correct. 

- On the MyAnalytics dashboard, I see the time zone is UTC-08.00. 
- On the Outlook calendar settings the time zone is set at UTC+01.00 (this differs from you post)
- Changing the timezone in Outlook settings does not change the time in MyAnalytics.
- Yes, focus time is set for the morning of UTC-8, which is evening in UTC+1.

**Comment by paul9955** [comment]
Thanks for the clarifications, Wim!
I'll contact the product team with this info and see if they have any insight into the problem.
-- Paul

**Comment by paul9955** [comment]
Hello Wim,
I'd like to give you an update on this. I've been communicating with the product team about it. There is a problem with the way this setting is presented, and we will meet (today) to discuss how to fix it. Thank you much for calling it to our attention! I will keep you posted on what we decide to do. 
Thanks again,
 -- paul9955
