### ISSUE TITLE
Wellbeing does not track meeting time in the meeting time calculation

### ISSUE THREAD

**Issue by shanaebr** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#214]
Wellbeing has not tracked any of my meetings towards its meeting calculation. Thus, the closer look estimations aren't accurate. What should be done to better track meetings and/or can this be changed manually?

**Comment by paul9955** [comment]
Hi shanaebr,
Particular meeting types are excluded from meeting metrics. Please take a look at this [Meetings](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/collaboration#meetings) section of the documentation, in particular [Meeting exclusions](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/collaboration#meeting-exclusions). Perhaps, for the time period in question, all of your meetings fall into those excluded categories. If not, let me know and I'll contact the product team to pursue this issue further for you. 
Thank you,
 -- paul9955

**Comment by paul9955** [comment]
I'm closing this issue for now. If my response didn't answer your question, please feel free to re-open the issue and I can pursue it further. Thank you,  -- paul9955
