### ISSUE TITLE
Mirror the metric definitions to be the same

### ISSUE THREAD

**Issue by Jasthin** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#215]
The metric definitions for the email & meeting hours doesn't mirror those of IM/call hours. This could lead to some confusion. 
Email hours should be:  Number of hours the person spent sending and receiving emails, during and outside of working hours. 
and meeting hours should be: Number of hours the person spent in meetings with at least one other person, during and outside of working hours. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e59345bb-9abb-9e5d-8613-01c0226dfc2e
* Version Independent ID: 493ac915-2a6a-a271-825a-43f40d1863e8
* Content: [Workplace Analytics metric definitions - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/use/metric-definitions)
* Content Source: [WorkplaceAnalytics/Use/Metric-definitions.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Use/Metric-definitions.md)
* Product: **wpa**
* GitHub Login: @paul9955
* Microsoft Alias: **v-mideh**

**Comment by paul9955** [comment]
Thank you Jasthin, for alerting us. 
It is now fixed. Please see **Email hours** and **Meeting hours** in [Metric definitions](https://docs.microsoft.com/workplace-analytics/use/metric-definitions).
 -- paul9955
