### ISSUE TITLE
Is there a way to manually use this rather than only when it chooses to offer it? Also how does this relate to https://support.microsoft.com/en-us/office/delay-or-schedule-sending-email-messages-026af69f-c287-490a-a72f-6c65793744ba

### ISSUE THREAD

**Issue by hoyty76** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#216]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46f983da-af4c-d975-445b-77fb8f307848
* Version Independent ID: 0cf725f8-0abf-465e-b031-396344f54cb1
* Content: [Delay delivery in MyAnalytics - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/delay-delivery)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/delay-delivery.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/delay-delivery.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**

**Comment by paul9955** [comment]
Hi hoyty76,

The two features are related only in that they let you delay the delivery of messages – usually, to better align with a recipient’s working hours. MyAnalytics can schedule email delivery that aligns with the working hours of the recipients in their respective time zones.
You can sign up at either of two levels: 
•	[Turn on inline suggestions](https://docs.microsoft.com/workplace-analytics/myanalytics/use/mya-notifications#why-dont-i-see-any-inline-suggestions) to get up to two delay reminders per day.
•	[Opt in to Delay delivery](https://docs.microsoft.com/workplace-analytics/myanalytics/use/delay-delivery#opt-in-with-myanalytics) to optionally get more than two reminders per day. 

Your first question was whether there’s a way to manually use this MyAnalytics inline-suggestions feature. You can directly respond to the inline suggestion by selecting **Delay send**, but other than that, the answer is no. You can manually delay delivery of mail that you’re about to send, but you do this in _Outlook_, not in _MyAnalytics_. And you are right in that these are the steps to use for that: [Delay or schedule sending email messages](https://support.microsoft.com/office/delay-or-schedule-sending-email-messages-026af69f-c287-490a-a72f-6c65793744ba). 

Please let me know if this doesn’t address your question,

Thank you,
-- Paul9955

**Comment by paul9955** [comment]
Closing this issue for now. Please let me know if I haven't answered your question. 
Thank you, - paul9955

**Comment by hoyty76** [comment]
The web version of outlook https://outlook.office.com/ seems to have a totally different delay send which happens on the server rather than client. Does the MyAnalytics Delay send rely on the Outlook Client being open as the the old style delay send?

**Comment by paul9955** [comment]
Hi hoyty76,

Yes, in the old-style delay send (as described in [Delay or schedule sending email messages](https://support.microsoft.com/en-us/office/delay-or-schedule-sending-email-messages-026af69f-c287-490a-a72f-6c65793744ba)), the delayed message remains in the **Outbox** folder of Outlook for the scheduled time, so Outlook must be online and connected for this to work.

In the MyAnalytics Delay-delivery feature, we do not have this dependency. The delayed email is kept in the Outlook **Sent items** folder until the scheduled delivery time, when it's automatically delivered for users.

Let me know if you have any more questions.

 -- paul9955
