### ISSUE TITLE
Document update  | PowerBI templates for Business continuity and Hourly collaboration currently do not support localized reports or localized language reports.

### ISSUE THREAD

**Issue by qaehtesh** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#217]
[Enter feedback here]

Engineering team confirmed that PowerBI templates for Business continuity and Hourly collaboration currently do not support localized reports or localized language reports.(In our case Japanese language did not work).
Requesting to update this documentation with above information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 208c8848-3e5a-2c94-d89f-fba11efdd208
* Version Independent ID: 054b67b2-f71f-4f71-f055-1b47362dc6e3
* Content: [Business continuity dashboard - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/tutorials/power-bi-bc)
* Content Source: [WorkplaceAnalytics/Tutorials/power-bi-bc.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Tutorials/power-bi-bc.md)
* Product: **wpa**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**

**Comment by paul9955** [comment]
Thank you qaehtesh,
I appreciate the information and will update the documentation accordingly.
 -- paul9955
