### ISSUE TITLE
Global Admin required for tenant-level configuration

### ISSUE THREAD

**Issue by MrAzureAD** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#219]
Documentation does not detail which admin is needed for tenant-level configuration.
The pre-requisites state that Exchange Service admin is sufficient. While this is true for individual user configuration, my tests showed that tenant-level configuration requires Global Admin.

My strong recommendation is to make this fact obvious as Global Admin changes are often treated differently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cee44a2-5742-83c0-ee3e-82a3a3f9417e
* Version Independent ID: ad800194-4e32-0529-6844-7529a0d670d7
* Content: [Configure Briefing email - Cortana](https://docs.microsoft.com/en-us/briefing/be-admin)
* Content Source: [Briefing/be-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Briefing/be-admin.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**

**Comment by madehmer** [comment]
@MrAzureAD - Thank you so much for your feedback. I've updated the docs accordingly.
