### ISSUE TITLE
Five-recipient minimum for read statistics doesn't count BCC

### ISSUE THREAD

**Issue by EricWilson-HV** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#220]
I sent an email to over 70 recipients (all BCC) from a distribution list, and when I sent it I opt'd into Insights and it gave me the message to "Check back later to see how many people have opened your email." The message was sent using delayed delivery, and now 2.5 hours after it went it I checked the insights and it says "This email doesn't meet the five-recipient minimum for read statistics."

**Comment by madehmer** [comment]
@EricWilson-HV - Thanks for your feedback. I'll pass this on to the team to consider adding as a setting for a future MyAnalytics release.
