### ISSUE TITLE
How to run the "example script" to create SAS URI?

### ISSUE THREAD

**Issue by rpanday** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#221]
There are no steps given to run the example script, just the contents of the script. It will be helpful to add the command line example and screenshots of azure portal for someone new to cloud shell. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 447eebe1-e8ba-8aa6-7fc7-79d9c18d8499
* Version Independent ID: 850ade3c-338b-e82a-f56c-48d95a92d1cc
* Content: [Workplace Analytics Data export - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/data-access/data-access)
* Content Source: [WorkplaceAnalytics/Data-Access/Data-Access.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Data-Access/Data-Access.md)
* Product: **wpa**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**

**Comment by madehmer** [comment]
@rpanday - I'll pass your feedback on to the team. Thanks!
