### ISSUE TITLE
Unclear if analytics and calculations are done or not when a user opts out.

### ISSUE THREAD

**Issue by dennish78** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#222]
What I am missing here is a crucial bit of privacy information (mostly peace of mind), being wether or not the analytics are performed when a user opts out, regardless of wether or not they would have access to the dashboard etc.
Or as one of my users asked me: "Does the system still snoop around in my mailbox when I am opted out?"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ede52900-0a1f-1713-9f9b-44af2fd64dbd
* Version Independent ID: fc2b7ff3-f708-c5ec-15da-c2cf7e01c677
* Content: [MyAnalytics privacy guide - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/overview/privacy-guide)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Overview/Privacy-Guide.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Overview/Privacy-Guide.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-pausch**

**Comment by paul9955** [comment]
Hi dennish78,

I had wondered this myself and I contacted the product team to look into it. Here's what I found out:  After you opt out of MyAnalytics, MyAnalytics stops processing your personal data. However, other Microsoft 365 services or features (such as [Cortana Briefing](https://docs.microsoft.com/en-us/briefing/be-overview) or Office.com) may continue to process this data to provide you with that functionality.

Let me know if you have further questions,
 -- paul9955

**Comment by paul9955** [comment]
Closing this for now. Please re-open if you have more questions. 
Thank you, -- paul9955

**Comment by lenakat** [comment]
Hello @paul9955,

I am researching MyAnalytics opt-out settings and wanted to clarify one of the aspects. You mentioned  that after user opts out of MyAnalytics, MyAnalytics stops processing personal data according to PG. Is this **opt-out** in MyAnalytics settings? Or is it opt-out through PrivacyMode parameter. This part of information is unclear in the documentation

**Comment by paul9955** [comment]
Hi lenakat,
You're right -- that point was unclear. Yes, processing stops in both cases. It stops if the user opts-out voluntarily (by using [Feature settings](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/overview/privacy-guide#how-employees-can-opt-in-and-opt-out)) and it also stops if an admin opts people out by using the PrivacyMode parameter to [configure user access](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/setup/configure-myanalytics#configure-access-at-the-user-level). 
I appreciate your question; it helped us close a gap in the documentation. See, for example, [Data processing consequences](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/overview/privacy-guide#data-processing-consequences).
Let me know if you have any further questions,
 -- paul9955
