### ISSUE TITLE
Directions for converting from other languages to English

### ISSUE THREAD

**Issue by juchacz** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#223]
On this page, we mention that the PBI templates are only available in English, but we do not explain how to generate query results in English if you are currently working in one of the other languages. To do this, the user needs to change the URL of the web application from:
https://workplaceanalytics.office.com/it-it/Analyze/Queries/NewQuery (for example, if they are using Italian)
to:
https://workplaceanalytics.office.com/en-us/Analyze/Queries/NewQuery

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fb96c86-8fe1-590b-266e-fc0d1dc6fa5b
* Version Independent ID: a4ac603f-03f6-feb3-7096-a8047f9ece22
* Content: [Workplace Analytics Power BI templates introduction - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/tutorials/power-bi-intro)
* Content Source: [WorkplaceAnalytics/Tutorials/power-bi-intro.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Tutorials/power-bi-intro.md)
* Product: **wpa**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**

**Comment by madehmer** [comment]
@juchacz - Excellent point. I'll reach out via email to confirm doc edits. Thanks!
