### ISSUE TITLE
Cortana Email Briefing in Outlook

### ISSUE THREAD

**Issue by RjrodG** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#225]
Hi there I would like to get some help regarding cortana email briefing, everytime I click done or remind later I get a message of "An error occured please try again later." and if I will open the outlook thru browser the buttons for done and remind later is not appearing same with android. Your help will be appreciated, thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0a83186-6909-edb8-7de3-7a5c9307a0a1
* Version Independent ID: 9ba1d4d8-60ba-1c4d-f7e8-e9a92e74727d
* Content: [Briefing email overview - Cortana](https://docs.microsoft.com/en-us/briefing/be-overview)
* Content Source: [Briefing/be-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Briefing/be-overview.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**
![Screenshot (7)](https://user-images.githubusercontent.com/32220931/117103109-4e071800-adac-11eb-8c99-72957120e2d3.png)

**Comment by madehmer** [comment]
@RjrodG - I'm sorry you're having issues. Please go to [Briefing feedback](https://cortana.office.com/briefing?v=feedback), explain this issue, select the checkbox that allows Microsoft to contact you about this issue, and then submit the form. The team will reach out for more info about your specific environment. Thanks for reaching out and I hope they can help you resolve this soon!
