### ISSUE TITLE
Delayed delivery option not appearing in config settings or add-on settings

### ISSUE THREAD

**Issue by joehallissey** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#226]
I'm not seeing delayed delivery in my config options or add-on settings. Is there an admin configuration that could block this feature? If so, can a note be added to mention that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46f983da-af4c-d975-445b-77fb8f307848
* Version Independent ID: 0cf725f8-0abf-465e-b031-396344f54cb1
* Content: [Delay delivery plan in MyAnalytics - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/delay-delivery)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/delay-delivery.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/delay-delivery.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-mideh**

**Comment by paul9955** [comment]
Hi Joe,
Delay delivery alerts are one type of inline suggestion. Are you seeing any inline suggestions at all? You might want to check [Why don't I see any inline suggestions?](https://docs.microsoft.com/workplace-analytics/myanalytics/use/mya-notifications#why-dont-i-see-any-inline-suggestions) to make sure your prerequisites are in place. If everything is in order and you're still not seeing them, let me know and I'll look into this further. 
Thank you,
 - Paul

**Comment by paul9955** [comment]
Hi Joe, 
I'm going to close this issue for now. If you're still seeing odd behavior with delay delivery, please re-open the issue, let me know, and I'll look into it more for you.
Thank you,
 -- Paul
