### ISSUE TITLE
Show working hours

### ISSUE THREAD

**Issue by janusdayorsted** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#227]
Is it possible to get an overview of the amount of hours that is identified as working time?

**Comment by madehmer** [comment]
@janusdayorsted - Thank you for your feedback. By default, all of our products use your [Outlook calendar settings](https://outlook.office.com/calendar/options/calendar/view/appearance) for working time. However, with MyAnalytics, you can change what your working time is in your dashboard's [Config settings](https://myanalytics.microsoft.com/?v=settings). What product document are you referencing that might need an edit?

**Comment by madehmer** [comment]
Please reach out if you need more information about working time.
