### ISSUE TITLE
Update video - outdated demo content

### ISSUE THREAD

**Issue by karleesm** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#230]
[Enter feedback here]
Hey team - one of the GBBs for Viva Insights here.  Wondering if we could get an updated video for this page which uses updated demo of the system in its current format.  Perhaps another interview with the same team ;)

Karlee

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34d12dbf-80f1-05ad-971b-1b39608778b3
* Version Independent ID: ef27c615-2c3b-49c0-6848-58d381767a57
* Content: [Workplace Analytics Videos - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/overview/videos)
* Content Source: [WorkplaceAnalytics/Overview/videos.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Overview/videos.md)
* Product: **wpa**
* GitHub Login: @paul9955
* Microsoft Alias: **v-mideh**

**Comment by paul9955** [comment]
Hi Karlee, 

Thank you for your comments. Yes, that video was quite outdated and I've removed it. We don't have a replacement for it, especially in interview format, but I've linked to several other more current and useful ones: [Workplace Analytics videos](https://docs.microsoft.com/en-us/workplace-analytics/overview/videos).  

Among the current videos, here's the one that I believe gives the best overall tour and therefore comes closest to the removed one: [Navigate Workplace Analytics](https://review.docs.microsoft.com/en-us/workplace-analytics/overview/get-started?branch=master#video-navigate-workplace-analytics).

I'm closing this issue. Feel free, of course, to re-open it if you have any more comments or questions. 

Thanks again,
 -- Paul
