### ISSUE TITLE
corrupted link

### ISSUE THREAD

**Issue by atagliacozzo** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#231]
The link to wpa teams page is corrupted

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fbc8581-509e-8a3b-e0e2-1fcf836f7315
* Version Independent ID: 877af892-d435-0487-a85c-92d4fc73cd75
* Content: [Explore Teams data in Workplace Analytics - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/use/explore-metrics-teams)
* Content Source: [WorkplaceAnalytics/Use/explore-metrics-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Use/explore-metrics-teams.md)
* Product: **wpa**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**

**Comment by madehmer** [comment]
@atagliacozzo - Thanks for your feedback. If you sign in to the Workplace Analytics app and then copy and paste the URL in the same window, it works. However, if you want to view it in a different language, you'll need to change the "/en-us" to the applicable language code in the URL: 
![image](https://user-images.githubusercontent.com/39922363/118681722-a8dd3e00-b7b4-11eb-8b16-e6bd195d725c.png)
