### ISSUE TITLE
Data Export to Blob using Private Link or Whitelisted IPs

### ISSUE THREAD

**Issue by prateek05** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#232]
How do we restrict our data export to use a Private Link between WPA and our storage container in Azure instead of our data flowing over the public internet?
Are there Whitelisted IPs which we can restrict in our storage firewall to only accept incoming connections from or is WPA included in the Trusted Microsoft https://docs.microsoft.com/en-us/azure/storage/common/storage-network-security?tabs=azure-portal#exceptions

**Comment by madehmer** [comment]
@prateek05 - This channel is for [Workplace Analytics documentation](https://docs.microsoft.com/workplace-analytics/overview/getting-support) questions or feedback. However, I think I might know what you're asking about:  For Internet connectivity to the app, you can use a Microsoft 365 endpoint connection to Workplace Analytics. For details, see [Office 365 URLs and IP address ranges](https://docs.microsoft.com/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide) and Workplace Analytics is listed in [Microsoft 365 Common and Office Online](https://docs.microsoft.com/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#microsoft-365-common-and-office-online). If you need further app help, ask your Microsoft 365 admin to contact [Support](https://docs.microsoft.com/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide). Alternatively, select the **smiley face** icon within the Workplace Analytics app, complete and submit the feedback form with your question, and don't forget to include your email address, so the team can contact you for more information and instructions. Thanks for your feedback and I hope you can get it all set up soon. Thanks for using Workplace Analytics!

**Comment by prateek05** [comment]
Thanks, I'll use the right support channel.
