### ISSUE TITLE
Download Activity Data

### ISSUE THREAD

**Issue by LNBaud** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#233]
Hello,

Is it possible to access the data that are used in Workplace Analytics ?
Is there an API to connect or a download button on the website ?

Thanks

**Comment by madehmer** [comment]
@LNBaud - Only Workplace Analytics licensed users can view Workplace Analytics data. Alternatively, you can ask your Workplace Analytics analyst to provide you data that you can view as Power BI data or reports. For details, see [Power BI templates in Workplace Analytics](https://docs.microsoft.com/workplace-analytics/tutorials/power-bi-intro).
