### ISSUE TITLE
Make insights available for email open rate even after 14-day window

### ISSUE THREAD

**Issue by MIWU-MSFT** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#234]
Once email passes 14 days after it was sent, there is no longer any insight data (open rates, etc.) about it.  Two recommendations:
1. Allow a 14 or 30-day window to see data
2. After the 14- or 30-days, then save the last available set of data (if only 14 days is available, we would still be able to see data, but it's simply not collected by the system after 14 days).

**Comment by madehmer** [comment]
@MIWU-MSFT - Thanks for your feedback. I'll pass it on to the team.
