### ISSUE TITLE
Missing explanation of reclassifying domains?

### ISSUE THREAD

**Issue by juchacz** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#235]
On the "Admin settings page" (https://docs.microsoft.com/en-us/workplace-analytics/use/admin-settings) we say, "you can use Admin settings to configure the following.: _System defaults_ - Set the system defaults for your organization, including time zone, working days and hours, the average hourly rate, and **external domains that require reclassification**, which are used for any person whose personal settings are not set up or inaccessible to Workplace Analytics."

When we click on System Defaults, though, there is no explanation of how to reclassify domains. Is this described somewhere else? I can't find it in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6454ba6f-5591-dd31-9b3e-c377166789ea
* Version Independent ID: 92ea85fb-b7cd-20cf-e788-3f445b260935
* Content: [System defaults for Workplace Analytics - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/use/system-defaults)
* Content Source: [WorkplaceAnalytics/Use/system-defaults.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Use/system-defaults.md)
* Product: **wpa**
* GitHub Login: @paul9955
* Microsoft Alias: **v-mideh**

**Comment by paul9955** [comment]
The section about reclassifying external domains has been reinstated. 
Thank you for notifying us about this! 
 - Paul
