### ISSUE TITLE
Definitions for long and large meetings

### ISSUE THREAD

**Issue by juchacz** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#236]
Hi! I was trying to help a partner answer a question about the 2x2 "Organize better meetings" matrix, which they wanted to replicate with a query. I noticed the definitions don't specify which category contain meetings that are exactly one hour in duration:

Long meeting | A long meeting is scheduled for more than one hour and has more than one but fewer than nine attendees. Also see Long and large meeting.
-- | --
Long and large meeting | A long and large meeting has more than eight attendees and is scheduled for longer than one hour.
-- | --
Decision-making meeting | A meeting that has between two and eight attendees and lasts less than one hour.
-- | --
Large meeting | A large meeting involves more than eight people and lasts less than one hour. Also see Long and large meeting.
-- | --

These should be MECE categories, which means that two of them should include one hour meetings (as it is, all four are either "more" or "less" than one hour). I actually don't know which categories need adjusted definitions - we might have to ask around.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7307881a-e155-144f-2932-6a8dd61fd494
* Version Independent ID: 9122cd36-984e-0ef0-0595-31656768044c
* Content: [Workplace Analytics Glossary - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/use/glossary#long-meeting-define)
* Content Source: [WorkplaceAnalytics/Use/Glossary.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Use/Glossary.md)
* Product: **wpa**
* GitHub Login: @paul9955
* Microsoft Alias: **v-mideh**

**Comment by paul9955** [comment]
Thanks for calling this to our attention, juchacz. I researched the true definitions for these terms (in particular to add "or equal to" to "greater than" or "less than" when appropriate) and updated them in the published docs on 21 July 2021. Closing the issue.
