### ISSUE TITLE
Duplicate word

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#238]
"Microsoft Microsoft 365"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 596b5d02-cd7f-7d55-71ef-ca7792922428
* Version Independent ID: 7e287c4b-5cdc-71ad-5359-b94baeef1ae6
* Content: [Improve your work patterns with personal productivity insights in MyAnalytics - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/overview/better-work-habits)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Overview/Better-work-habits.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Overview/Better-work-habits.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **v-pausch**

**Comment by paul9955** [comment]
Hi Dan,

Just fixed it: [Why use MyAnalytics?](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/overview/better-work-habits)

Thank you much for calling this to our attention! 
-- paul9955
