### ISSUE TITLE
Focus time is not correctly picked up when manually entered

### ISSUE THREAD

**Issue by jrkoop** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#239]
Hi, I manually schedule “focus time” for myself, during times on my calendar when it makes sense and doesn’t conflict with important business meetings. I expressly call these blocks of times “Focus time” in the hope your parser/interpreter picks it up as “real” focus time. Yet, each week it’s clear this is ignored because your report includes a reference to 0 (zero) focus time. It would be nice if there is a literal string you can use so that scheduled time is included in your focus time logic. Because I most definitely schedule focus time, and it was because I was prompted by your otherwise excellent tool. But your automated scheduling grabs way too much focus time so I don’t use it. Thank you

**Comment by paul9955** [comment]
Hello jrkoop,
Thank you for this suggestion! I have forwarded it to the program manager who's in charge of the focus-time feature. If I hear back from the product team that there's a workaround, or that your idea corresponds to an enhancement in the product pipeline, I'll post that info to this thread. 
I'll go ahead and close this thread for now. Feel free to re-open it if you have any further questions or suggestions. We appreciate them. 
-- paul9955

**Comment by paul9955** [comment]
Hello again jrkoop, 

I've received some information -- good news, actually -- from the product team. It appears that a capability corresponding to your suggestion is under development. We are working with Outlook to let people set appointment blocks as focus time, after which this time will be counted towards focus time. However, I have no estimate on how soon this enhancement might become available. 

Thanks again for your suggestion!
 -- paul9955
