### ISSUE TITLE
Insights Add-In:  Qualifying Messages

### ISSUE THREAD

**Issue by gitvpic** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#240]
Team,
I'm wondering about trying to collect analytics for an email newsletter I send to specific distribution lists (DLs).  I have read about [Qualifying Messages](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/use-the-insights#reporting-details), but  am looking for further understanding.  

In my case, I am looking to track the "Open" rates and (potentially) follow through clicks on links contained within the email message. 

When I check MyAnalytics for these specific email messages, I notice I can't find them showing up in the Insights Add-In.  So then I saw the "Exceptions to qualifying messages" and this is what my feedback relates to.  Of the four listed exceptions, the only one that applies to my use case is:

- Email that was sent more than 14 days ago -- **_is this something that can be expanded to, say, 90 days?  I'm looking for quarterly analytics._**

Additionally, when it comes to "Open Rate", do I understand correctly that MyAnalytics can only provide data if all recipients have opted into MyAnalytics?

**Comment by paul9955** [comment]
Hello gitvpic,

I contacted the product team with your questions. Here's the answer to your second one:

Q. Can MyAnalytics provide data on "Open rate" only if all recipients have opted into MyAnalytics?
A. The data for a recipient is reported only if that person has a MyAnalytics license and is opted in for processing. 

 - For info about MyAnalytics licenses, see [Assign licenses with a MyAnalytics service plan](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/setup/configure-myanalytics#assign-licenses-with-a-myanalytics-service-plan).
 - For info about opting in, see [Opt back in](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/opt-out-of-mya#if-i-opt-out-can-i-opt-back-in).

As for your first question, I need to ask for clarification: 

Do you mean that you want to see email-read data for all of the 90 days after the email was sent OR do you want to see that same 14 days of email-read data for up to 90 days after the email was sent?

Thank you,
 -- paul9955
