### ISSUE TITLE
Enable Leadership page

### ISSUE THREAD

**Issue by tgrosst** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#241]
If a user has previously selected _I'm not a manager_, because they were not a manager at the time, how can they turn this page back on, now that they are a manager? The user does have team members assigned to them in Azure Active Directory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6176ef14-1c23-0cac-93f6-3ec7f751e9d7
* Version Independent ID: c61079eb-6481-9936-f9c3-61b900039e44
* Content: [Leadership insights dashboard - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/leadership#confirming-your-team)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/leadership.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/leadership.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-pausch**

**Comment by paul9955** [comment]
Hello tgrosst,
I've contacted the product team to try to find an answer for you about this. I'll respond here after I hear back.
Thank you,
 -- paul9955

**Comment by talborough** [comment]
...

**Comment by talborough** [comment]
I would like to watch from this page.

**Comment by paul9955** [comment]
Good morning,
I have found out that we have a feature under consideration that would allow users to re-enroll to receive Leadership Insights. I do not know when this feature might become available. 
Thank you,
 -- paul9955
