### ISSUE TITLE
Link to share interactive dashboard not correct

### ISSUE THREAD

**Issue by karleesm** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#242]
Hi team - any way to update the Share link on the interactive dashboard in the Demonstration section with a specific link rather than a link to the general Docs site (https://docs.microsoft.com/)?  As a workaround I will share a link to the demonstration section but was testing out being more specific in what I was sharing and that was provding the above link to share.

Thanks

Karlee

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f956ef4d-db6f-aa40-3ed6-572893e49b68
* Version Independent ID: bef0b537-6004-ad42-1227-dea193ea8d27
* Content: [Ways of working assessment dashboard - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/tutorials/power-bi-collab-assess)
* Content Source: [WorkplaceAnalytics/Tutorials/power-bi-collab-assess.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Tutorials/power-bi-collab-assess.md)
* Product: **wpa**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**

**Comment by paul9955** [comment]
Hi Karlee,
I emailed someone who I believe worked on that Power BI demo to ask whether he can update the link. I added you in the Cc: line of that email, so you can see any progress that gets made.  
Thanks,
 -- paul9955
