### ISSUE TITLE
Add definition for Active Employees

### ISSUE THREAD

**Issue by karleesm** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#243]
I have been asked multiple times by customer what we mean by Active Employees - can we please add a definition to this page?  Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7307881a-e155-144f-2932-6a8dd61fd494
* Version Independent ID: 9122cd36-984e-0ef0-0595-31656768044c
* Content: [Workplace Analytics Glossary - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/use/glossary)
* Content Source: [WorkplaceAnalytics/Use/Glossary.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Use/Glossary.md)
* Product: **wpa**
* GitHub Login: @paul9955
* Microsoft Alias: **v-mideh**

**Comment by paul9955** [comment]
Hello Karlee,
Good catch. Although I found the term defined several times inline in the docs (mostly in the sections about queries), it wasn't in the glossary. It's there now: [Glossary / Active employee](https://docs.microsoft.com/workplace-analytics/use/glossary#acrive-employee-define).
Thank you for pointing this out! 
  -- paul9955
