### ISSUE TITLE
Scrolling in "Your daily briefing" email

### ISSUE THREAD

**Issue by MrBrianGale** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#244]
If you open the "Your daily breifing" email and mark off an item as "done" or "remind me later", the link to the email gets selected.  While the link is selected, scrolling past it becomes impossible with the scroll wheel.

The expected behavior is that I can scroll past the selected link using the scroll wheel on my mouse and review the remainder of the email, but as it is right now, I need to click on the scrollbar and scroll down with it.

This is a low priority bug as the main functionality of the addon still works and there is an easy workaround.

If more information is required, let me know and I can provide it.

**Comment by madehmer** [comment]
@MrBrianGale - We appreciate your feedback. Are you viewing the email in the Outlook Desktop app? The scroll wheel on my mouse works in my daily briefing, which I'm viewing in the Outlook desktop app. Thanks so much for your time on this!

**Comment by MrBrianGale** [comment]
I am using the desktop app of outlook, version 2107, build 14228.20226

Would it help if I were to record what is happening?  If so, I can do that tomorrow when I get the email.

**Comment by madehmer** [comment]
@MrBrianGale - Ah, I'm using version 2018. Actually, if you would please use [this feedback form](https://cortana.office.com/briefing?v=feedback) to report this issue and select the checkbox that allows Microsoft to contact you, then the team can follow up with you directly if they need more details. Thanks again for your time on this!

**Comment by MrBrianGale** [comment]
Sounds good.  Thanks for letting me know.
Are you wanting me to provide feedback on this issue on github as Microsoft works on it OR should I mark this issue as closed?

**Comment by madehmer** [comment]
@MrBrianGale - Hi, this forum is for documentation questions and edits, not for reporting bugs or product issues. So I'll close this as not a doc issue. Thanks for asking and following up!
