### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by bestephens** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#245]
Focus Time appointment only has options to update one or all, but not update this and all future instances. I use Focus to track assignments, and lost months of past assignments due to the "Update all" option. I also cannot change future appointments

**Comment by madehmer** [comment]
@bestephens - I'm sorry to hear you had that experience. Thanks for your feedback! Are you referring to updating or changing scheduled focus time in your Outlook calendar? There is an option in [Outlook to only change this and all following events](https://support.microsoft.com/en-us/office/create-modify-or-delete-a-meeting-request-or-appointment-in-outlook-com-541383fd-35b7-49a6-b4c8-2ee75af2f40a), which would avoid changing past events in your calendar.

**Comment by bestephens** [comment]
This is not an option when changing the "Focus Time" series appointments. The only options are "Just this one" or "The entire series".

**Comment by madehmer** [comment]
Ok. What app are you changing the "Focus Time" in?

**Comment by bestephens** [comment]
In Outlook Office 365. There is no way to change any option without
changing only a specific instance or all instances.

Becky A Stephens

**Comment by madehmer** [comment]
Ok. Thanks for your feedback. I'll pass it on to the team.
