### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by talborough** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#249]
[Enter feedback here]

This is interesting. Way too powerful for my liking but admittedly, highly interesting. Please be careful with the damn genie.

Tom
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6176ef14-1c23-0cac-93f6-3ec7f751e9d7
* Version Independent ID: c61079eb-6481-9936-f9c3-61b900039e44
* Content: [Leadership insights dashboard - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/leadership#confirming-your-team)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/leadership.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/leadership.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-mideh**

**Comment by madehmer** [comment]
Thanks for your feedback
