### ISSUE TITLE
data export and historical

### ISSUE THREAD

**Issue by dehaaz** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#25]
I have a couple questions that I couldn't find:
- Is it possible to export the data from the dashboard to another application? E.g. Microsoft Excel? I know there is the share option, but it does not give detailed information through the time;
- How long does the MyAnalytics keep track of? I wanted to check historical data from long ago to identify patterns and changes in the routine, as a change in roles activities and how that affect the work flow.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b35411c-e636-4b20-e6bf-be230abd0c26
* Version Independent ID: 67eb56ad-67ff-0122-d76e-e1b1acf4d565
* Content: [MyAnalytics dashboard - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/dashboard)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/Dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/Dashboard.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-pascha**

**Comment by paul9955** [comment]
Hi dehaaz,

I have answers to your questions:

Q1: Is it possible to export the data from the dashboard to another application?
A1: No, there is no way to export data. As you mentioned, there is a Share option; this is the only way to share data with others. 

Q2: How long does the MyAnalytics keep track of? 
A2: In the MyAnalytics dashboard you can page back through the data of previous weeks. This shows you trends data for as long as two years in the past. In addition, data is available for up to 80 days before activation of your MyAnalytics license. In other words, if you are brand new to MyAnalytics but you have already been active in Office 365, you will see 80 days of your trends data. As time passes, this display of trends data will grow to encompass the preceding two years of activity.

Thank you, and feel free to respond with any other questions that you might have.
