### ISSUE TITLE
Viva Insights = MyA (full)?

### ISSUE THREAD

**Issue by JeremyTyers** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#250]
If a user is licensed for Viva Insights does that then mean that they get access to MyA (Full)? if so this page should be updated to state that. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f1b78b4-21ad-2234-0822-149ffe88814b
* Version Independent ID: 5dad7085-6921-5392-f0a7-f5b6e9b5cc0b
* Content: [MyAnalytics plans and environments - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/overview/plans-environments)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Overview/plans-environments.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Overview/plans-environments.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-mideh**

**Comment by madehmer** [comment]
@JeremyTyers - Yes, I'm working with the team now on doc updates. Admins will see MyAnalytics (Full) change to Viva Insights (formerly MyAnalytics) in the Microsoft 365 admin center around Sept. 7, 2021 and I'll publish updated docs for that UX change. Thanks for asking about this!
