### ISSUE TITLE
Unable to unsend - From sent folder

### ISSUE THREAD

**Issue by neilbroo** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#252]
I am using this addon at MS and it says that i can unschedule delivery from the sent folder but there is no option anywhere to click. I have opened the email directly from the sent box and still i do not see a banner where i would click to send now or cancel delivery. Is there additional configuration i need to do in outlook?

**Comment by madehmer** [comment]
@neilbroo - I'm sorry to hear you're having problems. However, if the email has already been sent, it's too late to unschedule it. For scheduled, but unsent email, the email would be located in your Outbox folder in Outlook. Please ask your Microsoft admin to reach out to [Support](https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide) for immediate product help. Or if you think this product behavior is a bug, please report it through the **Feedback** icon (smiley face) within your Outlook Insights panel, and select the checkbox that says that Microsoft can contact you to follow up: 
![image](https://user-images.githubusercontent.com/39922363/133111924-598fbae2-9461-420d-9394-9df1cc95f36f.png)
Thanks for your feedback!

**Comment by neilbroo** [comment]
I am able to see the email before delivery in the sent box, however, when I attempt to cancel, there is no option on the email to cancel. So I can delay delivery, I am just unable to cancel that once it is set. I can see it when I am sending my email, but after the delay is configured, I do not see a change/cancel option from within the sent folder on the email, before the scheduled time.


Neil Broome
One Store Technical Duty Officer
Mobile: 904.309.3161
***@***.******@***.***>
***@***.***

**Comment by madehmer** [comment]
@neilbroo - Right, I meant to tell you earlier to simply delete the email from your sent folder if you want to cancel delivery. Thanks for asking!

**Comment by neilbroo** [comment]
Okay, will try that. How will I know if it is successful?


Neil Broome
One Store Technical Duty Officer
Mobile: 904.309.3161
***@***.******@***.***>
***@***.***

**Comment by madehmer** [comment]
@neilbroo - When you delete an email in Outlook, it won't be in the Sent items folder anymore. Thanks for using Microsoft products. :-)
