### ISSUE TITLE
Can you include other online meeting types?

### ISSUE THREAD

**Issue by Rod-in-NM** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#253]
I really like Workplace Analytics. For example, I have a gut feeling that meetings during the pandemic has gone up significantly, compared to what it was like pre-pandemic. However, although Workplace Analytics helps with knowing this, it is far from accurate. Most of my meetings with colleagues are done using Cisco's Webex. That isn't tracked nor traced by Workplace Analytics. For example, from Workplace Analytics view point my day today is free of all distractions and meetings. However, Workplace Analytics is ignorant of the multiple Webex meetings I've got this afternoon, all afternoon.

**Comment by madehmer** [comment]
@Rod-in-NM - Thanks for asking. Yeah, Workplace Analytics currently does not work with Cisco Webex. It's designed to use Microsoft 365 activity with Microsoft 365 apps. I'll pass your request to work with Webex to the team to consider for a future release.
