### ISSUE TITLE
Company's average vs Team's average

### ISSUE THREAD

**Issue by martinctc** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#256]
On Q5, where it says...

> If the team structure does not meet the minimum group size, then the company's average is not used or shown in the metrics.

By `company's average`, do we mean `team's average`? It does not seem to make sense.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d15defa-d3de-f039-f4fb-47eb0c77179e
* Version Independent ID: 9519e5ec-a5d5-eb0f-2d27-f0c72a7a95fe
* Content: [FAQs about Workplace Analytics insights for managers - Workplace Intelligence](https://docs.microsoft.com/en-us/viva/insights/use/insight-faqs)
* Content Source: [WorkplaceAnalytics/Use/insight-faqs.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Use/insight-faqs.md)
* Product: **wpa**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**

**Comment by paul9955** [comment]
Hi Martin,

Thank you for the question. Maybe we indeed have a typo there!  I've contacted the PMs on this to make sure before I change the wording. I appreciate your attention to this! 

 -- Paul

**Comment by paul9955** [comment]
Hi Martin,
Yes, you found a genuine typo; this was confirmed by the product team. I've fixed it in the docs here:  [FAQ / Q5](https://docs.microsoft.com/en-us/viva/insights/use/insight-faqs#q5-do-the-teams-like-yours-metrics-account-for-organizational-averages-and-minimum-group-size-settings).
Thank you, Martin! 
-- Paul
