### ISSUE TITLE
Documentation for "hourly rate" on settings page

### ISSUE THREAD

**Issue by juchacz** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#26]
Hi! The Settings page in WPA has a field to change the hourly rate. It would be helpful if the documentation had the definition, explained how it is used in Workplace Analytics, and explained how updates to the hourly rate are applied to the data (e.g. do they apply to past processed or future processed data or both? How quickly can the analyst expect to see the change reflected?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a311b001-b100-2cc5-2651-9324178605d7
* Version Independent ID: a687cfbe-9693-d0ae-1207-4a23ff7e26cf
* Content: [Workplace Analytics Setup Checklist - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/workplace-analytics/setup/set-up-workplace-analytics#feedback)
* Content Source: [WorkplaceAnalytics/Setup/Set-up-Workplace-Analytics.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Setup/Set-up-Workplace-Analytics.md)
* Product: **wpa**
* GitHub Login: @madehmer
* Microsoft Alias: **paul9955**

**Comment by madehmer** [comment]
Thanks for the feedback! The docs have been updated accordingly.
