### ISSUE TITLE
Update in the documentation 

### ISSUE THREAD

**Issue by Manjot9** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#262]
[
Update the document with this information: We don't currently have subsite support for viva topics crawling. You will need to select the site which will include the subsite
As per this ICM: https://portal.microsofticm.com/imp/v3/incidents/details/284557208/home
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c351a507-4e0d-41e7-91dc-440b34103ec1
* Version Independent ID: c351a507-4e0d-41e7-91dc-440b34103ec1
* Content: [Introduction to Microsoft Viva Topics](https://docs.microsoft.com/en-us/viva/topics/)
* Content Source: [Viva/topics/index.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/topics/index.md)
* Service: **viva**
* Sub-service: **viva-topics**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by chuckedmonson** [comment]
@Manjot9 -- Thank you for your feedback. Where specifically do you think this should be mentioned (article title and specific section)? Thanks again.

**Comment by Manjot9** [comment]
> @Manjot9 -- Thank you for your feedback. Where specifically do you think this should be mentioned (article title and specific section)? Thanks again.

Hey, It can be added as a special note in the main article. Thank you for looking into this :)

**Comment by chuckedmonson** [comment]
Vetting the recommendation with our subject matter experts. Thank you for your feedback.
