### ISSUE TITLE
Email Activity via Mobile

### ISSUE THREAD

**Issue by paw1523** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#27]
Hi!

Are you able to include into calculation email activities if done via local mail applications of IOS or Android? This is instead of using Outlook Mobile App

**Comment by Apisit2522** [comment]
iOS 12.1

**Comment by Apisit2522** [comment]
THAILAND

**Comment by Apisit2522** [comment]
THAILAND

**Comment by paul9955** [comment]
Hello paw1523,

Thank you for your interest in this functionality. The answer is Yes. You can configure the email app on iOS and on Android to work with email from your Office 365 account. If you do that, your Office 365 email activities on your mobile device will be included in your collaboration statistics. 

 - Workplace Analytics documentation team
