### ISSUE TITLE
Outbox vs Sent Items

### ISSUE THREAD

**Issue by m-m-powers** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#271]
[Enter feedback here]
Item 3 of this page states that 

> After you send the email, it's kept in your Outlook Sent items folder until the scheduled delivery time, when it's automatically delivered for you.

Isn't the email that will be delayed kept in the Outlook Outbox folder, rather than the Sent Items folder, until it is sent?

Recommend updating this verbiage from "Sent Items" to "Outbox"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e90e3dc0-1995-0752-d42f-bf29a1f225b6
* Version Independent ID: d2717304-5311-4778-a6a1-50ba6578725a
* Content: [Delay delivery plan in MyAnalytics](https://docs.microsoft.com/en-us/viva/insights/personal/use/delay-delivery)
* Content Source: [Viva/insights/personal/Use/delay-delivery.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/personal/Use/delay-delivery.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **helayne**

**Comment by get-itips** [comment]
Hello @m-m-powers Mark, how are you?
I tested this, to understand if we needed to adjust the verbiage, however, the mail goes for a couple of seconds to Outbox and then goes to Sent items, as the article says, if you select it, you will receive a notice saying when the email will be actually sent

![image](https://user-images.githubusercontent.com/36666927/157121437-faf49b1a-1953-4bef-b81e-a461b709647c.png)

Hope this information helps you and many thanks for your feedback!
