### ISSUE TITLE
Set up the Viva Connections experience in a specific language

### ISSUE THREAD

**Issue by vasanthkumarc94** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#275]
As mentioned in the Microsoft document I am trying to translate it to other country languages like French. But I am not able to see the content in French language even though my profile is in French. 
Followed this link https://docs.microsoft.com/en-us/viva/connections/viva-connections-language

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
