### ISSUE TITLE
Focus time status and category configurations

### ISSUE THREAD

**Issue by kacala** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#276]
I love using the focus time, it is a game changer. I don't think this is a bug, but more of a 'nice to have' additional options - I'd like to have a way to configure my focus time as 'tentative' slot, rather than 'busy', since I want people to be able to send me a meeting request for those timeslots as well (and not see me as busy in the Scheduling Assistant). Another thing is the category label (each category has different color) that would be nice to incorporate. I like seeing different colors in the calendar, so that I can easily know which is my focus time.

I am currently editing focus time status as tentative and category manually which is no big deal. The only struggle is when I get some additional meeting requests during the focus time and the automatic scheduler changes the focus time timeslot, and I need to change status and category manually again.

Do let me know what you think of these suggestions. Thank you for making this feature, I love it! :)

Cheers,
Katarina

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
