### ISSUE TITLE
Compliance & security regulations according EU laws

### ISSUE THREAD

**Issue by ToSur** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#28]
Hi,

Is the MyAnalytics & WorkplaceAnalytics in line with all EU regulations and privacy laws?

Cheers,

Tom

**Comment by paul9955** [comment]
Hi Tom,

Yes, MyAnalytics and Workplace Analytics comply with those regulations. For more detailed information, see the following articles: 
- https://docs.microsoft.com/en-us/workplace-analytics/privacy/data-protection-summary
- https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/overview/privacy-guide

Thank you! 
 - Workplace Analytics & MyAnalytics documentation team
