### ISSUE TITLE
Error in the KB, Settings not available to public

### ISSUE THREAD

**Issue by jordanmorinishi** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#284]
[Enter feedback here]
The options to opt in to the Delay Delivery plan is not avialable in the settings for either of the options. There is a forum post where other users are having the same issue as me. Please look into this and fix this issue. 

[https://answers.microsoft.com/en-us/msoffice/forum/all/delay-delivery-via-viva-insights/33569f54-95f1-41f0-81f5-c503d39f004b](url)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e90e3dc0-1995-0752-d42f-bf29a1f225b6
* Version Independent ID: d2717304-5311-4778-a6a1-50ba6578725a
* Content: [Delay delivery plan in MyAnalytics](https://docs.microsoft.com/en-us/viva/insights/personal/use/delay-delivery)
* Content Source: [Viva/insights/personal/Use/delay-delivery.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/personal/Use/delay-delivery.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **helayne**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
