### ISSUE TITLE
Request: Translation Update

### ISSUE THREAD

**Issue by v-hasa** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#29]
Hello team,
I have noticed that there are two different expressions for one word, nudge.
MyAnalytics nudges should be translated as MyAnalytics ナッジ and the current translation in this page is 微調整 or シェイク.
Could you kindly update the translation to ナッジ as soon as possible?
Thank you .

With best regards,
Haruka

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: ae5243bf-bda7-c9a6-1f36-7c011e17988b
* Version Independent ID: 5e5ff830-dc34-73e6-670d-acf9d5617b90
* Content: [Outlook で微調整する MyAnalytics - Workplace Analytics Office 365 ](https://docs.microsoft.com/ja-jp/Workplace-Analytics/myanalytics/use/mya-notifications#feedback)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/mya-notifications.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/mya-notifications.md)
* Product: **mya**
* GitHub Login: @buntus
* Microsoft Alias: **patboony**

**Comment by paul9955** [comment]
Thank you Haruka,
We have requested a new translation of this topic. I will update this thread to report on additional progress. We appreciate your interest in this content. 
- MyAnalytics documentation team

**Comment by paul9955** [comment]
Hello Haruka,
Thank you again for notifying us of this issue. We have corrected the translation. You can see the fixed topic [here](https://docs.microsoft.com/ja-jp/Workplace-Analytics/myanalytics/use/mya-notifications#feedback).

**Comment by v-hasa** [comment]
Hello Paul,

Thank you very much for taking care of the issue!

Haruka
