### ISSUE TITLE
Missing "self-organized meeting hours" metric definition

### ISSUE THREAD

**Issue by juchacz** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#33]
"Self-organized meeting hours" is a new metric in the person query, but it's missing from our definitions table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e59345bb-9abb-9e5d-8613-01c0226dfc2e
* Version Independent ID: 493ac915-2a6a-a271-825a-43f40d1863e8
* Content: [Workplace Analytics metric definitions - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/Workplace-Analytics/use/metric-definitions)
* Content Source: [WorkplaceAnalytics/Use/Metric-definitions.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Use/Metric-definitions.md)
* Product: **wpa**
* GitHub Login: @paul9955
* Microsoft Alias: **madehmer**

**Comment by madehmer** [comment]
@juchacz -thank you so much for your feedback. The Workplace Analytics Person metrics table is now updated with all the latest information, including "Time in self-organized meetings."
