### ISSUE TITLE
Plans & Feature Availability

### ISSUE THREAD

**Issue by ferrety2006** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#34]
Per this announcement: https://www.microsoft.com/en-us/microsoft-365/blog/2019/01/02/myanalytics-the-fitness-tracker-for-work-is-now-more-broadly-available/ 
There's not a specific explanation or delineation in the announcement between which features (as shown in the documentation above) will be available to what plans. Is the table here accurate in light of the upcoming changes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f1b78b4-21ad-2234-0822-149ffe88814b
* Version Independent ID: 5dad7085-6921-5392-f0a7-f5b6e9b5cc0b
* Content: [MyAnalytics plans and environments - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/overview/plans-environments)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Overview/plans-environments.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Overview/plans-environments.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-pascha**

**Comment by paul9955** [comment]
Yes, the plans and features [described here](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/overview/plans-environments) are accurate. Please refer to the product blog for any updated information about upcoming changes.
