### ISSUE TITLE
Timing of Welcome Email

### ISSUE THREAD

**Issue by ferrety2006** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#35]
How long does it take for the personal dashboard to become available?
The personal dashboard is available to a MyAnalytics user as soon as they receive their welcome email. This happens about three days after the MyAnalytics license was assigned to the participant. For more information, see Assign MyAnalytics licenses to users.

The documentation here does not clarify email timing from time of license assignment with the new upcoming changes (https://www.microsoft.com/en-us/microsoft-365/blog/2019/01/02/myanalytics-the-fitness-tracker-for-work-is-now-more-broadly-available/). For example, the announcement states that the licenses will be assigned Feb 12th to all applicable license holders of E1, E3, and E5, but per this documentation page, it says the welcome email comes out about 3 days after. SInce the Add-In feature does not become available until March 12th, per the announcement, does this truly mean that the welcome email will arrive three days after Feb 12th, even though they cannot use the feature until Mar 12th?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1531b80-1cd3-8654-27fd-1aa8f4a1c4cd
* Version Independent ID: ecc841f6-5f6b-8b26-0080-3f5288f92eaf
* Content: [MyAnalytics FAQ - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/overview/mya-faq)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Overview/MyA-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Overview/MyA-faq.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **madehmer**

**Comment by paul9955** [comment]
Hello ferrety2006, 
Only the Outlook add-in will be available on March 12. The Welcome email will not be sent. Other features, such as the welcome email, the personal dashboard, and the digest email, will become available to users at a future date. Once the exact dates of their availability is determined, we will announce those dates, most likely on the [product blog](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Fen-us%2Fmicrosoft-365%2Fblog%2F2019%2F01%2F02%2Fmyanalytics-the-fitness-tracker-for-work-is-now-more-broadly-available%2F&data=02%7C01%7Cv-pascha%40microsoft.com%7Ca6c37a2a0cbf4080be3208d68c5d4fa4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636850729741980797&sdata=qiwZkUUoEQVK0KsaVPDUIWm1RE9TRpzFLQEr2R7N8LU%3D&reserved=0). 
  - MyAnalytics documentation team
