### ISSUE TITLE
Will the MyAnalytics service be automatically assigned?

### ISSUE THREAD

**Issue by Serg1on** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#40]
Will the MyAnalytics service be automatically assigned to users in Admin Center - Active Users - Change licenses screen? If so, is there possibility to cancel Welcome email to users?

**Comment by Serg1on** [comment]
Hello Paul, 
Could you please give me expectations whether I will receive a reply, as it's very important for my customer?

Thank you.

**Comment by paul9955** [comment]
Hi Serg1on, Sorry not to have replied sooner. I'm working with the product team to verify the details of this before I respond. I should have an answer for you today.

**Comment by paul9955** [comment]
Hi Serg1on,
Yes, the service will be automatically assigned. In the Admin center, admins will start seeing MyAnalytics as a service for users who have been assigned qualifying licenses (such as E3 and E1). An admin will be able to turn off all emails from MyAnalytics (and this will include the welcome email) but they cannot turn off the welcome email individually.
Please let us know if you have any further questions!

**Comment by Serg1on** [comment]
Hi Paul,
Thanks so much for your reply. Do you probably know if it will be possible to turn off emails before it will be assigned to users?

**Comment by paul9955** [comment]
Hi Serg1on,
After the users have been assigned MyAnalytics licenses, admins can turn off emails for specific users. They will be able to do this at the end of February and therefore significantly before the email would be sent out. In any case, admins will receive advance notice before the Welcome emails are sent out.

**Comment by Serg1on** [comment]
Hi Paul,
Thank you for your anwers!
Have a nice day.
