### ISSUE TITLE
Applies to:

### ISSUE THREAD

**Issue by computx** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#41]
So, this doesn't include A1?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74c447e0-fae6-a016-c6bf-01438701ce17
* Version Independent ID: b6d82917-aee4-2808-00ce-df6c20b75766
* Content: [MyAnalytics Add-in - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/add-in)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/add-in.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/add-in.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-pascha**

**Comment by madehmer** [comment]
@computx, thank you for your interest in MyAnalytics. Unfortunately, the free online version of Office 365 A1 Education plan doesn’t include access to MyAnalytics.

**Comment by computx** [comment]
Thanks for the notification.  Any idea when it might be included?

**Comment by madehmer** [comment]
You're welcome. Sorry, I've not heard of any near future plans to add MyAnalytics to A1.
