### ISSUE TITLE
Site gives 500 error after sign in

### ISSUE THREAD

**Issue by amanjee** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#42]
Logging into https://workplaceanalytics.office.com/ shows a 500 error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a311b001-b100-2cc5-2651-9324178605d7
* Version Independent ID: a687cfbe-9693-d0ae-1207-4a23ff7e26cf
* Content: [Workplace Analytics setup - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/workplace-analytics/setup/set-up-workplace-analytics)
* Content Source: [WorkplaceAnalytics/Setup/Set-up-Workplace-Analytics.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Setup/Set-up-Workplace-Analytics.md)
* Product: **workplace analytics**
* GitHub Login: @paul9955
* Microsoft Alias: **paul9955**

**Comment by paul9955** [comment]
Hi amanjee,
I'm sorry this is happening. The first thing to try is to clear your browser cache and refresh the page. If that doesn't solve the problem, look into the resources that are described on the [Get support](https://docs.microsoft.com/en-us/workplace-analytics/overview/getting-support) page.
