### ISSUE TITLE
Does the O365 "Applies to" License at top need an update?

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#43]
Hi, I believe MyAnalytics is now available for E3 licenses.  Does the "Applies to" list above need to be updated?  Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b35411c-e636-4b20-e6bf-be230abd0c26
* Version Independent ID: 67eb56ad-67ff-0122-d76e-e1b1acf4d565
* Content: [MyAnalytics dashboard - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/dashboard)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/Dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/Dashboard.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **madehmer**

**Comment by paul9955** [comment]
Hi @chrisweis, Office 365 E3 makes the Outlook add-in available, but not the other elements of MyAnalytics. The “Applies to” notes are correct. For a summary of the availability of the MyAnalytics elements, see [Availability of features](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/overview/plans-environments). Thank you
