### ISSUE TITLE
Tag meetings and emails

### ISSUE THREAD

**Issue by jfkeane** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#45]
How can I indicate the type of meeting it is so it rolls up in a custom grouping in the dashboard? For example, I would like to indicate the team that I am meeting with and be able to show the distribution of time spent with various teams across my org.  I would also like to indicate the type of engagement with the team (e.g. standup, ship room, program review, leadership meeting with my boss ... etc.) and see how my time is distributed across a week/month/etc.

**Comment by paul9955** [comment]
Hi John, I am looking into this now and will respond as soon as I have the answer. Thank you

**Comment by paul9955** [comment]
Hi John, I hope the following information can be of help. 1) I've heard discussion around adding to MyAnalytics the ability to manually categorize meetings, but I have no ETA for this. 2) If your organization uses Workplace Analytics, you could pull a Workplace Analytics meeting query into PowerBI and then visualize the meeting subject lines (provided that they are not hashed) in a word cloud.
