### ISSUE TITLE
Book focus time in Outlook

### ISSUE THREAD

**Issue by mgartside** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#47]
There should be a way to book "focus time" in Outlook, to protect time to get focused work done. it should look different from meeting time, so that My Analytics can count it as focus time instead of meeting time.

**Comment by paul9955** [comment]
Hi mgartside, You can book focus time by using one of the insight cards in the MyAnalytics Outlook add-in. This capability is (briefly) described here: [Outlook add-in](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/add-in#insights-that-you-might-see). Please let me know if this does not answer your question. Thank you

**Comment by kschach** [comment]
Can we manually book Focus Time in the calendar? How are these events differentiated by MyAnalytics? If I manually add an entry with the title "Focus time" would that count? It looks as these get categorized as "Green category" in Outlook.

I'd like to be able to schedule Focus Time from Android as well if possible.

**Comment by loryanstrant** [comment]
I too would like to know what the elements are to make my own Focus time appointments so it sets my Teams presence!

**Comment by thiagoalz** [comment]
After lots of testings.... the only way I found to do that is to copy an event automatically created and paste it another day.
You can even freely edit the auto-created event it is always considered focus time.

**Comment by gpompeo** [comment]
I believe outlook and Insights uses a “Green Category” to identify focus appointments.  Nevertheless, this category is not available for selection. 

IMO, best way would be to map category (or categories) to focus time. On that thought, it would be nice to map different types as well. This would help get insights into how one’s  time is being used.

**Comment by narramadan** [comment]
> After lots of testings.... the only way I found to do that is to copy an event automatically created and paste it another day.
> You can even freely edit the auto-created event it is always considered focus time.

This worked !!!

**Comment by loryanstrant** [comment]
> > After lots of testings.... the only way I found to do that is to copy an event automatically created and paste it another day.
> > You can even freely edit the auto-created event it is always considered focus time.
> 
> This worked !!!

A few of us have figured out how to automate this with Power Automate and to incorporate it into our own workflows. Check out [this video series](https://www.youtube.com/playlist?list=PL4czZ5H6nIU8XcdGLBq26PyEAMFQeRv-f).
