### ISSUE TITLE
Metric Internal_Collaborators is missing

### ISSUE THREAD

**Issue by FlorineSegers** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#48]
2 customers asked me for the definition of Internal Collaborators in their query output and couldn't find it in the documentation. 

From Harshit I learned that if you select the metric “Time investors initiated meeting hours” you will see this special bucket since this metric only considers Internal collaborators. Definition of this metric: Number of meeting hours the time investors created for collaborators by organizing meetings. Which means time investors created X hours of meeting hours for collaborators. 

Would be great if it can be added to the documentation.

Florine (WpA CS team)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b98d89fb-d1d4-099b-aba6-376aba3b72f9
* Version Independent ID: 326633d4-7106-d59f-166e-195e512f1137
* Content: [Group-to-group queries in Workplace Analytics - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/workplace-analytics/tutorials/group-to-group-queries#feedback)
* Content Source: [WorkplaceAnalytics/Tutorials/Group-to-group-queries.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Tutorials/Group-to-group-queries.md)
* Product: **wpa**
* GitHub Login: @madehmer
* Microsoft Alias: **v-midehm**

**Comment by madehmer** [comment]
@FlorineSegers -Thanks so much for your feedback! The [Time investors initiated meeting hours](https://docs.microsoft.com/en-us/Workplace-Analytics/use/metric-definitions#group-to-group-metrics) metric definition is currently included in the docs. However, I’ll work with our team to update it to more accurately explain that the metric only includes internal collaborators based on the number of meeting hours that the time investor scheduled with them. The [Understand and interpret query output]( https://docs.microsoft.com/en-us/Workplace-Analytics/use/csv-query-output-file) also describes time investors and collaborators for group-to-group and person-to-group queries, so I’ll also update that accordingly.
