### ISSUE TITLE
Opt out of Insights by MyAnalytics

### ISSUE THREAD

**Issue by SCS-sysadmin** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#49]
This article states that you can opt out of MyAnalytics by selecting the option from Delve. However since Microsoft is broadly releasing the add-in to lower-tier licenses (e.g. Business premium, E1, E3, etc.) and ONLY the add-in, this option isn't available, because they don't have access to the MyAnalytics dashboard. How can such a user opt out of the data collection? I assume that disabling the add-in through OWA is not enough?

**Comment by paul9955** [comment]
Thank you, SCS-sysadmin, for your comments and questions. All users at any license tier can opt out by changing the settings in the new Dashboard preview at https://myanalytics.microsoft.com.
 To open the settings panel, select the gear icon in the upper right corner of the dashboard page; then, under “MyAnalytics,” click the word Settings. The steps to opt out are described in [MyAnalytics dashboard (preview)](https://docs.microsoft.com/en-us/Workplace-Analytics/myanalytics/use/dashboard-2#can-i-opt-out-of-myanalytics).
