### ISSUE TITLE
Add-in still unavailable for Office 365 Business

### ISSUE THREAD

**Issue by Chaasof** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#50]
From the admin portal we can assign licenses to users but the add-in still unavailable from outlook!

**Comment by paul9955** [comment]
Hi Chaasof, Thank you for your question. The add-in will become available starting in mid-May. 
For more information about the roll-out schedule, see [Plans and environments](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/overview/plans-environments).
