### ISSUE TITLE
[tests/repo/results/encoding-sb-dec]  BRIEF_TITLE_GOES_HERE

### ISSUE THREAD

**Issue by shadulsikder90** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#51]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45e60cc3-b429-c8f9-2c91-d1de47f9a3cb
* Version Independent ID: 21ecb09d-49ce-36f9-1332-318e96a99b82
* Content: [Meeting exclusion rules in Workplace Analytics - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-gb/workplace-analytics/tutorials/meeting-exclusions-intro)
* Content Source: [WorkplaceAnalytics/Tutorials/meeting-exclusions-intro.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Tutorials/meeting-exclusions-intro.md)
* Product: **wpa**
* GitHub Login: @paul9955
* Microsoft Alias: **v-pascha**

**Comment by paul9955** [comment]
Hello shadulsikder90, Your comment didn't come through. I'll close this issue for now. Feel free, of course, to re-open it with a comment. Thank you
