### ISSUE TITLE
No information about which PowerShell Module contains PS Cmdlets

### ISSUE THREAD

**Issue by Eric2XU** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#53]
Its great that there are powershell cmdlets to make changes, however which module do they come from? How about a link to the module?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6072f5d-bc88-72e8-44eb-12f65b4671c8
* Version Independent ID: 02f1c840-e9ad-e7f3-66ff-1bd45f3aeb63
* Content: [MyAnalytics setup for Office 365 Administrators - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/setup/mya-setup-checklist#feedback)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Setup/Mya-setup-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Setup/Mya-setup-checklist.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **v-midehm**

**Comment by a-unique-username** [comment]
It's the Exchange Online PowerShell Module. It's mentioned at the No. 3 of "Set PrivacyMode for multiple users".

**Comment by Eric2XU** [comment]
Oh yeah well would you look at that. I think given the powershell code itself is before that I didn't bother to read on. It really needs to be expressed at the top of the document as well as mentioned in any new sections that refer to a cmdlet.

**Comment by paul9955** [comment]
Thank you, Eric2XU and a-unique-username! We'll look at the article with this in mind to see how best to make it clearer, including adding the module name where you mentioned.
