### ISSUE TITLE
Insights Add-In verbiage regarding third-party

### ISSUE THREAD

**Issue by soyalejolopez** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#54]
![image](https://user-images.githubusercontent.com/28953579/57881431-e6ceb280-77e6-11e9-8bc8-866b8b9c7e7d.png)

Hey team, the insights add-in has the following verbiage: ""The add-in may also send data to a third-party service. (See the Privacy Policy for the add-in.)" Can we provide additional information in this article or update the verbiage if incorrect? I could't find a mention of a third-party service in the privacy policy for the add-in. Thanks!

**Comment by paul9955** [comment]
Hello Alejandro,
Thank you for your helpful question! 
I looked into this. It turns out that this text is in error. **No data is shared with third parties.** We have begun the process to get the text removed.  
 - MyAnalytics doc team

**Comment by soyalejolopez** [comment]
Great! Thank you team.
