### ISSUE TITLE
Opt out requires access to the Dashboard, but E3/E1 Insights users don't have access to the dashboard

### ISSUE THREAD

**Issue by soyalejolopez** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#55]
We point users to this article to opt out of MyAnalytics: https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/dashboard-2#can-i-opt-out-of-myanalytics

However, E3/E1 Insights users won't have access to the dashboard. At least not until later in 2019 it seems: https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/overview/mya-faq

In the meantime though, this could cause confusion among users.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74c447e0-fae6-a016-c6bf-01438701ce17
* Version Independent ID: b6d82917-aee4-2808-00ce-df6c20b75766
* Content: [Insights Outlook add-in - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/add-in#feedback)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/add-in.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/add-in.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-midehm**

**Comment by paul9955** [comment]
Hello Alejandro, I'm looking into this for you and I'll respond to this space as soon as I have the answer. Thank you for your question! - paul9955

**Comment by paul9955** [comment]
Hi Alejandro, 
I heard back from the product team. Here was the response: "All users have access to the dashboard Settings screen. E3/E1 users will now see a “placeholder” experience in the dashboard, but they can access the Settings page to opt-out." 
Alejandro, please let me know if this does not work for you, and I'll look into it further. 
thank you,
  -- paul9955

**Comment by soyalejolopez** [comment]
Thank you Paul9955 - if users can access the dashboard, that should do the trick. We may want to clarify that "placeholder" experience in our documentation to make it easier to understand. Currently, we have the following in the FAQ which insinuates users wouldn't have access to the dashboard:  

"The dashboard button will not appear until the dashboard becomes available to E3/E1 users, to take place later in 2019."

**Comment by paul9955** [comment]
Hi Alejandro,
I've been discussing this with the PMs. They plan on adding a link in the product to a doc topic that should explain this better. (I'm not sure when that link will appear.) In the meantime, the answer about opting out is that you do it in the <b>Feature settings</b> panel. You reach this panel from the placeholder page by selecting <b>Manage settings</b>. You reach this panel from the dashboard by selecting the Settings (gear) icon and then selecting <b>Settings</b> under the word <b>MyAnalytics</b>.

**Comment by soyalejolopez** [comment]
Good stuff, thank you @paul9955 for all your help!
