### ISSUE TITLE
Is there a uservoice of MyAnalytics?

### ISSUE THREAD

**Issue by rdiazjimenez** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#56]
I have a suggestion, where do I post it?

**Comment by paul9955** [comment]
Hello Ricardo,
I will look into this for you, and I'll respond to this thread. 
In the meantime, you can always post suggestions right here in GitHub. 
Thank you,
 - MyAnalytics doc team

**Comment by rdiazjimenez** [comment]
Thank you Paul. When allocating time in calendar it'd help to allow to choose which calendar the newly created appointments should go to. I use at least two calendar folders.

**Comment by paul9955** [comment]
Hi again Ricardo,
Are you referring to the addition of _focus time_ to the calendar? If so, I believe MyAnalytics always adds it to the [default calendar](https://support.office.com/en-ie/article/set-default-calendar-7c546486-0c7c-4870-964a-0d6eb4de83e0). However, I'm getting this confirmed with the team, and I'll reply back here when I know the definite answer. - paul9955

**Comment by rdiazjimenez** [comment]
Yes Paul, goes to the default. My suggestion is to allow to choose to which one is sent

**Comment by paul9955** [comment]
Hi Ricardo,
I have relayed that request to the product team. I appreciate your interest in MyAnalytics and I agree with you that, if they take this on as a development task, it would improve the product. If that happens, we'll reflect the new capability in the product docs (and also, mostly likely, in the [product blog](https://techcommunity.microsoft.com/t5/Workplace-Analytics-MyAnalytics/bg-p/Office365AnalyticsBlog)) as soon as it becomes available. Thanks again!
- paul9955
