### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by derekadk** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#58]
The insights pane should follow the selected Outlook theme.  eg: Dark mode.

**Comment by paul9955** [comment]
Hi Derek, 
I've relayed your comment to the MyAnalytics team. I'll let you know if I find out about adjusting the theme for the Insights panel. 
Thank you, 
 -- paul9955

**Comment by paul9955** [comment]
Hello again Derek, 
You're right that the Insights panel does not currently recognize and adhere to the Outlook theme. I've let the team know of this as a customer request. I cannot estimate a date for a corresponding product enhancement but if I find out that it's happening, I'll replay here to let you know. 
Thank you for letting us know about this concern!  - paul9955

**Comment by Schvifty** [comment]
This would be awesome, was just going to post the same suggestion.

Now when Outlook on Mac have dark mode everywhere, even on the reading pane, it looks off to have an add-on on the right side with white color.
