### ISSUE TITLE
Insights lacks a control panel ...

### ISSUE THREAD

**Issue by ewhishaw** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#59]
It is very unsettling not having a control panel to be able to see what types of analytics are on or off.

**Comment by paul9955** [comment]
Hello ewhishaw,
I will look into this for you, but I do not understand your request completely. For "types of analytics," are you referring to the kinds of data that are aggregated to produce the Insights? For example, number of emails, length of meetings, and so on?  
Thank you,
 -- paul9955

**Comment by paul9955** [comment]
Hi ewhishaw,
I'm going to close this issue for now. Please feel free to re-open it if you still have concerns. I'm happy to help and I can do so once I understand your question better. Thank you,  -- paul9955
