### ISSUE TITLE
What is the URL for accessing Workplace Analytics?!?

### ISSUE THREAD

**Issue by TheWojan** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#6]
All these instructions are great, but you leave out step one: What is the URL you need to access in order to effect any changes to the settings!?!? I can't find the URL to get into the feature in the first place.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa2bc8a5-1bfe-b610-b76c-47887510ca63
* Version Independent ID: ef31e4c9-77e3-5fcd-5834-d08846e00cbb
* Content: [Configure settings for Workplace Analytics - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/workplace-analytics/use/settings)
* Content Source: [WorkplaceAnalytics/Use/Settings.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics-pr/blob/live/WorkplaceAnalytics/Use/Settings.md)
* Product: **wpa**
* GitHub Login: @rodonahu
* Microsoft Alias: **rodonahu**

**Comment by buntus** [comment]
Good catch! We have now addressed this issue by publishing the specific steps required to access the Workplace Analytics Settings page. Thank you for your valuable feedback!

johtob
