### ISSUE TITLE
Please remove dependency for IE

### ISSUE THREAD

**Issue by JoakimOfficial** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#60]
After uninstalling IE it's not longer possible to use Insights in Outlook since "Internet Explorer is not activated".

**Comment by paul9955** [comment]
Hello JoakimOfficial,
I checked into this with the product team for you. Their response was that this behavior is part of Outlook. "We currently have a strict dependency on Internet Explorer being activated, and we will internalize your feedback on this behavior for future releases of Outlook." 
Although this is now on their radar, I'm unfortunately unable to give any ETA for a change in this regard. Thank you for notifying us about this concern. 
 -- paul9955
