### ISSUE TITLE
Details needed

### ISSUE THREAD

**Issue by Tyr03** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#61]
What is the exact outcome of : 

> This lets you receive notifications when you've missed an email from someone on your list or not followed up on a to-do task for that person

- What is the trigger to be a missed email ?
- What is the outcome ? Desktop notification, system email ?
- By to-do task you mean a planner assigned task ?

This is not very clear to me

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80727439-3ac9-b80a-17ee-8a598371aabe
* Version Independent ID: de45c03a-a9b7-19d0-33b8-d017a0559ee4
* Content: [Managing the important people list in MyAnalytics - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/overview/important-people#feedback)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Overview/Important-people.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Overview/Important-people.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-pascha**

**Comment by paul9955** [comment]
Hello Tyr03,
I looked into this for you. The trigger is that you have not read an email from someone in your Important people list. The outcome is that Insights shows a card called **Catch up on email** that provides details such as "You have 5 unread emails from important people." You can also click this card to see more information about the emails. 
The to-do tasks appear in the Tasks section of Outlook (not in the planner). 
Please let me know if you have more questions. 
Thank you,  -- paul9955
