### ISSUE TITLE
Can't permently remove Insights from Ribbon Menu?

### ISSUE THREAD

**Issue by RCGms** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#63]
Look, I 've searched and get that the Administrator can disable for everyone .. but what about for the individuals that just don't care one f**king iota about the insights garbage?

There are MANY of us, that understand how much time they lose working with some emails and how many times we email one person vs another, and sure I bet insights has some wonderful graphics to help us understand the pigs our email have become .. *BUT* when a user removes said icon from their ribbon bar ... and then subsequently removes it from the Email pane's ribbon too ... don't you think that user's wish should be respected?

AND what about having the plug-in be a regular run of the mill add in that a user can go to OPTIONS -> ADD INS .. to remove it or disable it or what ever .. for THEIR account?

I mean.. I don't get it microsft.. WTF is wrong with you?  You have a page that CLEARLY identifies the Insights' analytics are personal .. 

https://docs.microsoft.com/en-us/workplace-analytics/insights-in-outlook

> Privacy by design
> 
> The Outlook add-in preserves all the data-subject rights afforded by GDPR. The insights you see in the add-in are only available to you. No admin or manager can see these insights. They are computed as needed, from the your email and meeting information, and are never stored outside your mailbox.
> 
> Additionally, the add-in begins processing data for insights only after the first time you open it. Learn more about how Microsoft protects your privacy.
> 

Really???  SO THEN WTF!??   If my manager won't see them .. and *I* don't f**king want them... then why cant *WE* the *USER*of the system disable this f**king P.O.S. plugin, add on, or what ever the f**k you want to call it??

Jesus does this stuff really not make it through to you people?

**Comment by madehmer** [comment]
@RCGms -Thanks for your feedback. We're sorry to see you go. You can follow [these steps to remove Insights from Outlook](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/add-in#to-remove-insights-from-outlook) and [these steps to opt out of MyAnalytics](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/add-in#to-remove-insights-from-outlook).
