### ISSUE TITLE
Office 2019 information?

### ISSUE THREAD

**Issue by Weychris** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#64]
works like 2016?

**Comment by paul9955** [comment]
Hi Weychris,
Take a look at [Overview of Office 2019](https://docs.microsoft.com/en-us/deployoffice/office2019/overview), in particular the sections [What's changed in Office 2019?](https://docs.microsoft.com/en-us/deployoffice/office2019/overview#whats-changed-in-office-2019), [What's stayed the same in Office 2019?](https://docs.microsoft.com/en-us/deployoffice/office2019/overview#whats-stayed-the-same-in-office-2019), and [What are the new features in Office 2019?](https://docs.microsoft.com/en-us/deployoffice/office2019/overview#what-are-the-new-features-in-office-2019). 
Please let me know if this article -- and the articles it links to -- do not answer your question.
Thank you,
 - paul9955, Workplace Analytics documentation
