### ISSUE TITLE
Automated Welcome email

### ISSUE THREAD

**Issue by mag210** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#65]
Can this email be turned off by default? We want to enable My Analytics but we do not want to push it to users. When My Analytics is rolled out to an Organisation, is My Analytics licensed by default? If so, do all users get a welcome email?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0f8fdd8-ac12-267d-019c-5a07dc7bbea6
* Version Independent ID: 5928cf60-0b4c-a78e-0d41-102513be5caa
* Content: [MyAnalytics welcome email - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/mya-welcome-email#feedback)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/MyA-Welcome-email.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/MyA-Welcome-email.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **v-midehm**

**Comment by madehmer** [comment]
@mag210 --Currently, you cannot turn off the MyAnalytics welcome email. After you assign licenses with the MyAnalytics service plan to users, MyAnalytics is automatically enabled by default. These users will get a welcome email a few days (up to four weeks) after licensing. For more details, see [Assign licenses with the MyAnalytics service plan](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/setup/mya-setup-checklist#step-2-assign-licenses-with-the-myanalytics-service-plan). Thank you for your valuable feedback! I'll pass on your request to add this option for MyAnalytics admins.

**Comment by adamfowlerit** [comment]
+1 to this request!
