### ISSUE TITLE
Myanalytics user feedback feature request 

### ISSUE THREAD

**Issue by ivanemadrigal** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#66]
I could not find anyway on the internet to provide MS with product feedback. Ugh. 

The concept of MyAnalytics is a good one however it is really DOA for me without the ability to track voice. All of my data is totally skewed since I have the majority of my work done via telephone. I have over a dozen MS apps on my phone including Office, PowerBI, etc. etc. etc. Surely the functionality can be developed into one of the many apps to track my phone call usage and look up in exchange who I am speaking with and add that to the collaboration activity. Otherwise I am looking at a tremendous product, a potential "killer app" as much as it could be for an O365 product potential to be a killer app. But without this feature it literally has zero benefit without it. Reach out to me anytime at ivan.e.madrigal@gmail.com. I am a diehard MS shop. I am the CEO of a $30M company and we built out Dynamics ERP ourselves, we are 100% MS shop in everything we do. I would love to be a regular submitter of feedback since I likely fit the profile of one of the types of customers your want feedback from. I grew up in tech and was a software quality assurance engineer for years at some big startups and Dell. I want to be a part of the development process as one data point in the voice of the customer. MS while for business is and will remain King there are lessons to be learned from Apple.....

**Comment by madehmer** [comment]
@ivanemadrigal -I've forwarded your feedback to our team to reach out to you via email. Thanks so much for your feedback!
