### ISSUE TITLE
What next?

### ISSUE THREAD

**Issue by SteveRose2019** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#68]
Should include steps to take if the addin is not visible.  For example as a result of https://docs.microsoft.com/en-us/Workplace-Analytics/myanalytics/setup/mya-disable-insights.

**Comment by madehmer** [comment]
@SteveRose2019 -Thanks so much for your feedback! I've[ added steps on how to add the Insights add-in back to your Outlook ribbon ](https://docs.microsoft.com/en-us/Workplace-Analytics/myanalytics/use/add-in#add-the-insights-add-in) just below the remove steps.

**Comment by SteveRose2019** [comment]
Thanks Michele - that looks good.
What to do if it is not visible under "Get Addins"? (I'm on E3)
Regards STeve
________________________________

**Comment by madehmer** [comment]
Hi Steve, Good question. This is an admin-enabled add-in. Do you see it listed in your "Admin-enabled" list in Outlook? If not, you might not have a license assigned to you through your admin for the Insights add-in. Reach out and point your admin to [these steps](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/setup/configure-myanalytics) to assign you a license for the add-in.
