### ISSUE TITLE
Do we also have official videos updates on channel9.msdn.com?

### ISSUE THREAD

**Issue by GITAhmad123** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#7]
Do we also have official videos updates on channel9.msdn.com? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34d12dbf-80f1-05ad-971b-1b39608778b3
* Version Independent ID: ef27c615-2c3b-49c0-6848-58d381767a57
* Content: [Workplace Analytics Getting Started Checklist - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/workplace-analytics/overview/videos)
* Content Source: [WorkplaceAnalytics/Overview/videos.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics-pr/blob/live/WorkplaceAnalytics/Overview/videos.md)
* Product: **mya**
* GitHub Login: @rodonahu
* Microsoft Alias: **rodonahu**

**Comment by madehmer** [comment]
**@GITAhmad123** -We’d like to broadcast Workplace Analytics news wherever possible. Do you currently use Workplace Analytics and/or MyAnalytics? Do you work with or are you affiliated with the MSDN Channel 9 team?
