### ISSUE TITLE
Group to group metrics doesn't match the product

### ISSUE THREAD

**Issue by juchacz** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#70]
The product only has 7 metrics - email hours, meeting hours, collaboration hours, meeting attendee count, meeting invitee count, meetings, and time investor initiated meeting hours. Group to group doesn't have LastTimeContacted, Employees Engaged, or Network size. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e59345bb-9abb-9e5d-8613-01c0226dfc2e
* Version Independent ID: 493ac915-2a6a-a271-825a-43f40d1863e8
* Content: [Workplace Analytics metric definitions - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/Workplace-Analytics/use/metric-definitions#feedback)
* Content Source: [WorkplaceAnalytics/Use/Metric-definitions.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Use/Metric-definitions.md)
* Product: **wpa**
* GitHub Login: @madehmer
* Microsoft Alias: **v-midehm**

**Comment by madehmer** [comment]
@juchacz -Thanks for your feedback. I updated the docs accordingly.
