### ISSUE TITLE
Person to group time calculations

### ISSUE THREAD

**Issue by juchacz** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#72]
Hi! I was reviewing the P2G documentation, and found this description of time allocation for a time investor group to a different collaborator group: https://docs.microsoft.com/en-us/Workplace-Analytics/use/csv-query-output-file#group-c-to-group-t

"Where Group C represents a collaborator group and Group T represents the time-investor group, totals include time generated by the time-investor group for all other groups in the company. These totals do not include the time-investor group's time spent in the meetings."

I don't think this is correct. It seems to be describing time investor initiated meeting hours, not time allocation methodology. Am I mistaken?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a26c288f-50c3-8b08-7fb1-2799aa2f0065
* Version Independent ID: 01117d81-a16c-d5bd-bb80-20062a07052c
* Content: [How to interpret query output in Workplace Analytics - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/Workplace-Analytics/use/csv-query-output-file#group-c-to-group-t)
* Content Source: [WorkplaceAnalytics/Use/csv-query-output-file.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Use/csv-query-output-file.md)
* Product: **wpa**
* GitHub Login: @madehmer
* Microsoft Alias: **v-midehm**

**Comment by madehmer** [comment]
@juchacz -Thanks for your feedback. Great question. I'll work with you via email to correct the docs accordingly.
