### ISSUE TITLE
Dependency on Office Graph

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#73]
Given that the Office Graph can be disabled in O365, what will happen to MyAnalytics in this scenario? Are there any dependencies on the Office Graph?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ede52900-0a1f-1713-9f9b-44af2fd64dbd
* Version Independent ID: fc2b7ff3-f708-c5ec-15da-c2cf7e01c677
* Content: [Privacy guide for MyAnalytics - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/overview/privacy-guide)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Overview/Privacy-Guide.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Overview/Privacy-Guide.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-midehm**

**Comment by madehmer** [comment]
@DeanGross -Great question. If Office graph is turned off, MyAnalytics is not impacted because it uses an internal Graph endpoint that's unaffected by the external graph configuration. Thanks for asking!
