### ISSUE TITLE
Insights Outlook add-in

### ISSUE THREAD

**Issue by robaxm** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#74]
Hi

I have trouble with Insights Outlook add-in! Keeps getting the following error message:
![Insights_Add-In Error](https://user-images.githubusercontent.com/22213007/64949016-8c1e9380-d878-11e9-8e7a-48bb1bb79f6c.jpg)

It works fine in web-version!

#Outlook #Insights #Windows10 #MyAnalytics 
Regards 
Robert Eriksson

**Comment by madehmer** [comment]
@robaxm --MyAnalytics doesn't work on older versions of Internet Explorer, please upgrade to [Microsoft Edge](https://www.microsoft.com/windows/microsoft-edge) and try again. I've asked the team to confirm that's the likely problem. If you need faster, more efficient help in troubleshooting your issues with the add-in, please reach out to [Microsoft Support](https://support.microsoft.com/). Thanks for your question! I'll add browser support to our MyAnalytics FAQ doc for future reference.

**Comment by robaxm** [comment]
But I don't use Internet Explorer and this is in the Outlook Windows 10 app.

**Comment by madehmer** [comment]
@robaxm --Ok. I'll ask the team what else might be causing your error.

**Comment by madehmer** [comment]
@robaxm --The Insights Outlook Add-In uses Internet Explorer v11, so you need to enable IE11, which is automatically installed as part of Windows 10, and have the applicable privacy settings. For more details, see [Browsers used by Office Add-ins](https://docs.microsoft.com/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins).

**Comment by madehmer** [comment]
@robaxm --Hey, I found you also need to confirm you have [Enhanced Protection Mode ENABLED](https://support.microsoft.com/help/2761180/apps-for-office-don-t-start-if-you-disable-protected-mode-for-the-rest) in your Internet Explorer 11 settings. Thanks again for asking!

**Comment by robaxm** [comment]
Hi

I managed to solve it myself [!](https://twitter.com/robaxm/status/1173934026689785856?s=20) It's was the same issue as presented by you, with Internet Explorer 11 disabled in Windows 10. 

Thanks for the help.👍😃
