### ISSUE TITLE
email signature

### ISSUE THREAD

**Issue by bcrogs** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#75]
The analytics should try to recognize an email signature and typical "tasks" associated with it on  every email and not associate a task with it. Examples include "Please consider the environment before printing," "If you are not the intendedrecipient, please forward the message to postmaster@xxxxxxxx.com and delete it from your computer and network"

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74c447e0-fae6-a016-c6bf-01438701ce17
* Version Independent ID: b6d82917-aee4-2808-00ce-df6c20b75766
* Content: [Insights Outlook add-in - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/add-in)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/add-in.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/add-in.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-midehm**

**Comment by madehmer** [comment]
@bcrogs --I'll pass this on to the team. Thanks for your feedback!
