### ISSUE TITLE
my analytics and education timetables

### ISSUE THREAD

**Issue by LorrieUWB** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#78]
hi
The my analytics package doesn't recognise my teaching slots within my outlook calendar. I've checked that they are defined as busy, which they are. So I think they are not counted as non-focus time because formally they have no other person allocated to it.

They are centrally synchronised by our timetable unit and just have a location and a timeslot. - So there are no and individuals pencilled against it although of course in reality I have my class and thus  erosion of my focus time.
Can anything done to be fix this? As the my analytics generally seems really useful functionality.

Lorrie

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 596b5d02-cd7f-7d55-71ef-ca7792922428
* Version Independent ID: 7e287c4b-5cdc-71ad-5359-b94baeef1ae6
* Content: [Improve your work patterns with personal productivity insights in MyAnalytics - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/overview/better-work-habits#feedback)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Overview/Better-work-habits.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Overview/Better-work-habits.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **v-midehm**

**Comment by madehmer** [comment]
@LorrieUWB -Great question. Unfortunately, today's Outlook and MyAnalytics cannot distinguish an appointment as meeting time and not focus time. Two workarounds you could use to avoid that time being counted as focus time are:

- Book the appointment as **Out of Office**, which will inflate your Wellbeing metrics. 
- Schedule a meeting with your personal email, which will inflate your Network metrics.

We realize these aren't great options. Our team added "classroom time" as a feature request to consider for future releases, so thank you so much for asking!
