### ISSUE TITLE
Is the claim that no one else can access the information true every time?

### ISSUE THREAD

**Issue by curious-me2** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#79]
I know that there is a disclaimer that this information cannot be accessed by other individuals aside from the person it is intended but is this true all the time? What if the report is opened using a system where e-mail/online traffic is monitored (like most companies now, I assume)? Can the admin or someone else, using another software (like screen capture), then get access to what information you are looking at? Just curious.

**Comment by madehmer** [comment]
@curious-me2 - MyAnalytics stores and processes your data inside your personal Exchange Online mailbox. So your MyAnalytics information is protected the same as the rest of your personal Office 365 data in compliance with your organization's data security and privacy policies.
