### ISSUE TITLE
Setting default working hours

### ISSUE THREAD

**Issue by juchacz** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#8]
Hi - I noticed that the documentation includes a screenshot with the working hours limits set to 10:30pm to 6:30am. This looks like it's specifying NON-working hours, but the documentation says: "the Workplace Analysis administrator can set default working days and working hours," suggesting that it's working hours they should put in there.

I think both the documentation and the interface should be adjusted to make it more clear which hours are being specified (I don't think the "Weekend days" label is sufficient to indicate that the range below is really non-working hours.")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a311b001-b100-2cc5-2651-9324178605d7
* Version Independent ID: a687cfbe-9693-d0ae-1207-4a23ff7e26cf
* Content: [Workplace Analytics Setup Checklist - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/workplace-analytics/setup/set-up-workplace-analytics#feedback)
* Content Source: [WorkplaceAnalytics/Setup/Set-up-Workplace-Analytics.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics-pr/blob/live/WorkplaceAnalytics/Setup/Set-up-Workplace-Analytics.md)
* Product: **wpa**
* GitHub Login: @paul9955
* Microsoft Alias: **v-leash**

**Comment by madehmer** [comment]
@juchacz -Great feedback. The team is investigating changes to resolve this. Thanks so much for your time on this!
