### ISSUE TITLE
Grammar Fix

### ISSUE THREAD

**Issue by rasputin243** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#80]
In the quoted sentence from the first section, the word "shares" should read "share"

&gt; "MyAnalytics has no mechanism or option that allows anyone but you to access the personalized information that is displayed through these surfaces, unless you purposefully and independently shares it."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 591e6c92-6639-75d7-4152-2ef0f730b8e5
* Version Independent ID: cff84842-9b6a-861b-1d0e-fd8c30a49df8
* Content: [Privacy guide for MyAnalytics users - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/overview/privacy-guide-users#feedback)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Overview/privacy-guide-users.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Overview/privacy-guide-users.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-pascha**

**Comment by madehmer** [comment]
@rasputin243 -Great catch. I'll fix it. Thanks so much for your feedback!
