### ISSUE TITLE
where is my email digest

### ISSUE THREAD

**Issue by alexale510** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#82]
i would love to see email digests!? i don't see them in my office365 inbox... this is confusing. can you have some info to tell users when to expect them and/or troubleshoot if they are not showing up?? thx!!! love this product btw

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f9fb980-d675-54ce-d70f-d796219c420b
* Version Independent ID: 59f35d62-c63e-76f8-772d-dbc24fcc9667
* Content: [MyAnalytics email digests - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/Workplace-Analytics/myanalytics/use/email-digest-2#feedback)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/email-digest-2.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/email-digest-2.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **v-midehm**

**Comment by madehmer** [comment]
@alexale510 --Your admin might've set email digests Off by default for your team. Follow these steps to turn your personal email digests On: 

  1. Open your [MyAnalytics dashboard](https://myanalytics.microsoft.com/).
  2. Select the **Settings** (gear) icon at the top right.
  3. Under **MyAnalytics**, select **Settings**.
  4. Under **Email digest**, change the setting to **On**.
  5. Select **Save** to save your changes.

After you turn them On, you should see weekly email digests in your inbox as early as next week. If you don't, be sure to ask your Office 365 Admin why you are not receiving them. Thanks for your great question and feedback!
