### ISSUE TITLE
Missing definitions for "default" meeting metrics

### ISSUE THREAD

**Issue by juchacz** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#83]
There's a handful of meeting metrics (e.g. TotalNoDoubleBooked) that you can add to the meeting query (via the organizational attribute selection interface, weirdly) that used to be "default metrics" that were returned to the query. It looks like we're missing their definitions - these metrics can also be used to filter meetings or customize a meeting metric in the person query.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e59345bb-9abb-9e5d-8613-01c0226dfc2e
* Version Independent ID: 493ac915-2a6a-a271-825a-43f40d1863e8
* Content: [Workplace Analytics metric definitions - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/Workplace-Analytics/use/metric-definitions)
* Content Source: [WorkplaceAnalytics/Use/Metric-definitions.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Use/Metric-definitions.md)
* Product: **wpa**
* GitHub Login: @paul9955
* Microsoft Alias: **v-midehm**

**Comment by madehmer** [comment]
@juchacz -Because we're working with you via email to get this updated, I'm going to close it here. Thanks for helping us keep the docs up-to-date!
