### ISSUE TITLE
Opt out vs Unsubscribe

### ISSUE THREAD

**Issue by JessWonga** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#85]
It would be helpful to include on this page: What is the fundamental difference between Opt-out and unsubscribing from emails?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49f5c4ac-08a4-a373-47ca-50755bcfd9e2
* Version Independent ID: 7a2bd341-9138-02ca-e8f8-8289be7a3b09
* Content: [MyAnalytics dashboard - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/dashboard-2#feedback)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/dashboard-2.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/dashboard-2.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **madehmer**

**Comment by madehmer** [comment]
@JessWonga -I'll add some context and link to [Opt out in the FAQ](https://docs.microsoft.com/workplace-analytics/myanalytics/overview/mya-faq#opt-out) for more details. Thanks for your feedback!
