### ISSUE TITLE
Need explanation of $LicenseSKU parameter of Add-WpALicense.ps1

### ISSUE THREAD

**Issue by taisino** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#86]
Please see the step 3 in "Script Execution" section. $LicenseSKU parameter is missing in the command sample.

Acutual: C:\Scripts\Add-WpALicense.ps1 -CSV
Expected: C:\Scripts\Add-WpALicense.ps1 -CSV &lt;CSVLocation&gt; -$LicenseSKU &lt;Something&gt;

Additionally we aren't sure how to idetify the value giving $LicenseSKU parameter, so explanation is necessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efd0452b-0749-f944-84eb-1ffafb152528
* Version Independent ID: 0a88d1d5-18fd-4e3d-dba5-0d0db39eebe2
* Content: [Assigning Workplace Analytics licenses with PowerShell - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/use/assigning-licenses-with-powershell#feedback)
* Content Source: [WorkplaceAnalytics/Use/Assigning-licenses-with-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Use/Assigning-licenses-with-powershell.md)
* Product: **wpa**
* GitHub Login: @madehmer
* Microsoft Alias: **v-midehm**

**Comment by madehmer** [comment]
@taisino -So sorry for the delayed response. Thank you so much for asking about this! You are right. The team is testing an updated PowerShell script now and as soon as it's approved, I'll update the docs accordingly. Do you still need help or the updated script? I can push to get it to you sooner, in case you're stuck waiting for this.

**Comment by taisino** [comment]
@madehmer 
Thank you very much for your reply. I solved by myself, and my customer doesn't have problem regarding this.
But this update would also help other customer. I'm not push you, but looking forward to the update.

**Comment by madehmer** [comment]
@taisino -This doc is now updated with new PowerShell script that's been tested and approved. Thank you again for your feedback!
