### ISSUE TITLE
Proposing tool for OS-wide activity tracking

### ISSUE THREAD

**Issue by craiglspencer** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#87]
I would love to see an optional feature that tells me how much time I spend with each program and how often I switch between tasks. Here is some sample code from a homegrown feature of this type:

Option Explicit
Declare Function GetForegroundWindow Lib "user32" () As Long
Declare Function GetWindowText Lib "user32" Alias "GetWindowTextA" _
    (ByVal Hwnd As Long, ByVal lpString As String, ByVal cch As Long) As Long

Function getActivity() As String
On Error GoTo itsNothing
    Dim ActiveWindowHandle As Long
    Dim titleArray() As String
    'get the handle of the active window
    ActiveWindowHandle = GetForegroundWindow()
    Dim title As String * 255
    ' get the title of the active window
    GetWindowText ActiveWindowHandle, title, Len(title)
    titleArray = Split(title, Chr(0), , vbBinaryCompare)
    getActivity = titleArray(0)
getActivity = Replace(getActivity, "'", "")
Exit Function
itsNothing:
Debug.Print Err.Number & ": " & Err.Description
Err.Clear
getActivity = "nothing"
End Function

Function logActivity(tblName As String)
Dim actySQL As String
actySQL = "INSERT INTO " & tblName & " (program, user, machine, DTG) VALUES ('" & getActivity & _
          "', '" & fOSUserName() & "', '" & fOSMachineName() & "', #" & Now() & "#)"
DoCmd.RunSQL actySQL
End Function

**Comment by madehmer** [comment]
@craiglspencer -Thanks for your feedback. You can actually [use the activity feed REST API](https://docs.microsoft.com/graph/api/resources/activity-feed-api-overview) to do this now.
