### ISSUE TITLE
Org Insights shutting down as soon as launched.

### ISSUE THREAD

**Issue by MattZoc78** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#88]
![SharedScreenshot](https://user-images.githubusercontent.com/60108396/72744124-988e6200-3b72-11ea-965b-8b7c97690c7c.jpg)

**Comment by madehmer** [comment]
@MattZoc78 -I'm sorry to hear about your issues with Insights. Did you reach out and get a resolution from Outlook Support? This Feedback channel is for documentation edits and feedback and not for resolving these types of urgent product issues or errors. However, I can ask my team if they know about this issue and if there's a known resolution if you are still waiting for help with this?

**Comment by MattZoc78** [comment]
Thanks so much for responding, Michele! Honestly, not even sure how a ticket was created... or when 🙂🙂

Insights is working, thank you again for checking!

-Matt
________________________________
