### ISSUE TITLE
Timezone configuration change. 

### ISSUE THREAD

**Issue by raddy2** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#9]
"This setting takes effect the next time organizational data is received and processed for the following month. A change in this setting does not affect any historical data."

Is this still accurate?

**Comment by madehmer** [comment]
Great question! It’s accurate assuming your organizational data is refreshed monthly. And yes, it does not affect historical data. However, you can set the organizational data to refresh whenever you like, daily, weekly, monthly, or anytime really. So we updated the note accordingly. Thank you so much for your feedback!
