### ISSUE TITLE
Configuring Focus Time

### ISSUE THREAD

**Issue by WeirNixie** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#91]
I have configured Focus Plan to allow automatic suggestions for booking focus time. This worked for two weeks, then stopped.  I have read this page - and see that I should be able to configure Focus. However, my screen does not have any options showing plan configuration 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40f032f9-30a5-b801-b3c2-602a6ef552d3
* Version Independent ID: bffa68c6-76a6-3de4-ec42-ab75c6a264d2
* Content: [Focus plan - Workplace Intelligence](https://docs.microsoft.com/en-us/Workplace-Analytics/myanalytics/use/focus-plan#feedback)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/focus-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/focus-plan.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **paul9955**

**Comment by madehmer** [comment]
@WeirNixie -Thank you so much for your feedback. This might be a bug. Would you please go to [your dashboard](https://myanalytics.microsoft.com), select **Feedback** near the bottom of the left navigation pane, and then fill out and submit your issue there? Please select the checkbox that allows them to contact you about your feedback. Then the team can follow up and confirm if it's a bug and/or how they can help you get your focus plan back on track! 
![image](https://user-images.githubusercontent.com/39922363/74489859-822aac00-4e7b-11ea-8fc7-56b5b5dfdc66.png)

**Comment by paul9955** [comment]
Hi Michele,

Thanks for replying to these. I’m still not getting notified of them.
For now, I’ll go to the Issues<https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/issues> page to look for new ones.


  *   Paul
