### ISSUE TITLE
Opt out screen shot is out of date

### ISSUE THREAD

**Issue by JeremyTyers** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#94]
the new UI has several options; this article needs to be updated with correct screenshots. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ede52900-0a1f-1713-9f9b-44af2fd64dbd
* Version Independent ID: fc2b7ff3-f708-c5ec-15da-c2cf7e01c677
* Content: [Privacy guide for MyAnalytics admins - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/overview/privacy-guide#feedback)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Overview/Privacy-Guide.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Overview/Privacy-Guide.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **madehmer**

**Comment by madehmer** [comment]
@JeremyTyers -Ok. This article is now updated accordingly. Thanks for your time on this!
