### ISSUE TITLE
Page Update

### ISSUE THREAD

**Issue by RexHead** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#95]
This page needs updated to reflect the Exchange admin center no longer has this option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f5cd86b-7906-3d5f-2118-6e20dea18a61
* Version Independent ID: 5a3d9884-4cca-4555-e5c5-6fabdb0580ae
* Content: [Disable the Insights Outlook add-in - Workplace Intelligence](https://docs.microsoft.com/en-us/Workplace-Analytics/myanalytics/setup/mya-disable-insights#feedback)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Setup/mya-disable-insights.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Setup/mya-disable-insights.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-midehm**

**Comment by madehmer** [comment]
@RexHead -According to our team these steps are still accurate. Please confirm that you're looking for "**Insights**" in the **Microsoft 365 admin center** -> **Exchange Admin Center** -> **Add-ins** page. Thanks for your time on this!

**Comment by RexHead** [comment]
Sorry.  Should have been more clear that **Add-ins** are being moved to the **Services and Add-ins** page and maybe that should be added to the content.  I have pretty much stopped using the Exchange Admin Center.

**Comment by madehmer** [comment]
@RexHead -Thanks for the clarification. Well, according to the product team, Insights is not yet available on the Services and Add-ins page in the M365 Admin Center. It's currently only available in the Exchange Admin Center. It'll eventually move to the M365 Admin Center, but we don't yet know when.
