### ISSUE TITLE
Change myanalytics language

### ISSUE THREAD

**Issue by ingd** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#96]
Hello guys,

One of my users is receiving the myanalytics email in a different language than the native language. There is a way to change this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b610fa2-972c-0986-f636-7df427aae23b
* Version Independent ID: 54d31361-8c93-2dec-e377-54404c1ad6f9
* Content: [MyAnalytics languages - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/overview/mya-languages?source=docs)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Overview/mya-languages.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Overview/mya-languages.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **madehmer**

**Comment by madehmer** [comment]
@ingd -Sometimes the mail client and server settings don't synch. Please ask the user to check/change the language in the [Outlook language and time settings](https://outlook-sdf.office.com/mail/options/general/timeAndLanguage/regional). If that doesn't resolve it, please ask the user to go to the [MyAnalytics dashboard](https://myanalytics.microsoft.com/), select **Feedback** near the bottom of the left navigation pane, and then fill out and submit this issue. Please ask the user to select the checkbox that allows us to contact the user about this issue. The team can then follow up and confirm if it's a bug and/or how to correct this issue. Thank you for your feedback!
